# Auto-generated by zosapi-stubgen — do not edit by hand.
# Re-run `zosapi-stubgen` to refresh after an OpticStudio upgrade.
from __future__ import annotations
from typing import (
    Any, Dict, Generic, Iterable, Iterator, List,
    Optional, overload, Sequence, Set, Tuple, TypeVar, Union,
)
from enum import IntEnum, IntFlag
from datetime import datetime, timedelta

import ZOSAPI.Common
import ZOSAPI.SystemData
import ZOSAPI.Tools.General
import ZOSAPI.Tools.Optimization
import ZOSAPI.Tools.RayTrace
import ZOSAPI.Tools.Tolerancing

from . import General as General
from . import LMx as LMx
from . import Optimization as Optimization
from . import RayTrace as RayTrace
from . import Tolerancing as Tolerancing

class CriticalRayType(IntEnum):
    """ZOSAPI.Tools.CriticalRayType"""
    Chief = 0
    Marginal = 1
    Grid = 2
    Ring = 3
    Y_Fan = 4
    X_Fan = 5
    XY_Fan = 6
    List = 7

class HPCEnvironments(IntEnum):
    """ZOSAPI.Tools.HPCEnvironments"""
    OnPremise = 0
    AWSKubernetes = 1
    AzureKubernetes = 2

class HPCNodeSize(IntEnum):
    """ZOSAPI.Tools.HPCNodeSize"""
    Default = 0
    Tiny = 1
    Small = 2
    Medium = 3
    Large = 4
    XLarge = 5

class HPCRunState(IntEnum):
    """ZOSAPI.Tools.HPCRunState"""
    NotRunning = 0
    Initializing = 1
    ClusterAllocating = 2
    UploadingData = 3
    Queued = 4
    RunStarting = 5
    WaitingForResults = 6
    Complete = 7

class IConvertToNSCGroup(ISystemTool):
    """ZOSAPI.Tools.IConvertToNSCGroup

    Interfaces and methods for converting the sequential surfaces to a non-sequential group. This interface can be accessed via the IOpticalSystemTools interface.
    """
    @property
    def FirstSurface(self) -> int: ...
    @FirstSurface.setter
    def FirstSurface(self, value: int) -> None: ...
    @property
    def LastSurface(self) -> int: ...
    @LastSurface.setter
    def LastSurface(self, value: int) -> None: ...
    @property
    def IgnoreErrors(self) -> bool: ...
    @IgnoreErrors.setter
    def IgnoreErrors(self, value: bool) -> None: ...
    @property
    def ConvertFileToNSC(self) -> bool: ...
    @ConvertFileToNSC.setter
    def ConvertFileToNSC(self, value: bool) -> None: ...
    @property
    def CreateSourcesAndDetectors(self) -> bool: ...
    @CreateSourcesAndDetectors.setter
    def CreateSourcesAndDetectors(self, value: bool) -> None: ...
    @property
    def ConvertToGlobalCoordinates(self) -> bool: ...
    @ConvertToGlobalCoordinates.setter
    def ConvertToGlobalCoordinates(self, value: bool) -> None: ...
    @property
    def OverfillFactor(self) -> float: ...
    @OverfillFactor.setter
    def OverfillFactor(self, value: float) -> None: ...

class ICriticalRaysetGenerator(ISystemTool):
    """ZOSAPI.Tools.ICriticalRaysetGenerator

    Interfaces and methods for generating a 'critical rayset'; these rays can be used after converting to non-sequential in order to verify that the conversion did not fundamentally alter the geometries. This interface can be accessed via the IOpticalSystemTools interface.
    """
    @property
    def RayPattern(self) -> RayPatternOption:
        """The pattern used to generate the critical rays."""
        ...
    @RayPattern.setter
    def RayPattern(self, value: RayPatternOption) -> None: ...
    @property
    def NumRays(self) -> int:
        """The number of rays to include in the critical ray bundle. Note that this is not necessarily the same as the number of total rays generated, and will be used differently for different ray patterns."""
        ...
    @NumRays.setter
    def NumRays(self, value: int) -> None: ...
    @property
    def MinimumEfectiveInputDistance(self) -> float:
        """Gets the minimum efective input distance."""
        ...
    @property
    def EffectiveInputDistance(self) -> float:
        """The pre-progation distance used with infinite conjugate systems; must be >= MinimumEfectiveInputDistance."""
        ...
    @EffectiveInputDistance.setter
    def EffectiveInputDistance(self, value: float) -> None: ...
    @property
    def UseAllFields(self) -> bool:
        """If true, all fields will be included in the critical ray set; otherwise, only the on-axis fields will be included."""
        ...
    @UseAllFields.setter
    def UseAllFields(self, value: bool) -> None: ...
    @property
    def UseAllWavelengths(self) -> bool:
        """If true, all wavelengths will be included in the critical ray set; otherwise, only the primary wavelength will be included."""
        ...
    @UseAllWavelengths.setter
    def UseAllWavelengths(self, value: bool) -> None: ...
    @property
    def ReadRaysFromFilename(self) -> str:
        """Input ray file (including path) to use when RayPattern is equal to List."""
        ...
    @ReadRaysFromFilename.setter
    def ReadRaysFromFilename(self, value: str) -> None: ...
    @property
    def SaveCriticalRaysFilename(self) -> str:
        """Critial rayset output file name, including path."""
        ...
    @SaveCriticalRaysFilename.setter
    def SaveCriticalRaysFilename(self, value: str) -> None: ...
    @property
    def RayScale(self) -> float: ...
    @RayScale.setter
    def RayScale(self, value: float) -> None: ...

class IDesignLockdown(ISystemTool):
    """ZOSAPI.Tools.IDesignLockdown

    Interfaces and methods for validating a sequential design, prior to manufacturing or conversion to non-sequential. This interface can be accessed via the IOpticalSystemTools interface.
    """
    @property
    def DecimalPrecision(self) -> int:
        """Controls how many decimal places are included when UsePrecisionRounding is turned on."""
        ...
    @DecimalPrecision.setter
    def DecimalPrecision(self, value: int) -> None: ...
    @property
    def ExcludePickups(self) -> bool:
        """If true, pickup solves will be retained in the converted system; otherwise all solves will be removed including pickups."""
        ...
    @ExcludePickups.setter
    def ExcludePickups(self, value: bool) -> None: ...
    @property
    def UsePrecisionRounding(self) -> bool:
        """Controls whether or not editor values will be rounded in the output system."""
        ...
    @UsePrecisionRounding.setter
    def UsePrecisionRounding(self, value: bool) -> None: ...
    @property
    def FixModelGlasses(self) -> bool:
        """Controls whether any model glass solves will be converted to the nearest material in the selected catalogs."""
        ...
    @FixModelGlasses.setter
    def FixModelGlasses(self, value: bool) -> None: ...
    @property
    def ConvertSDToMaxApertures(self) -> bool:
        """Controls whether floating semi-diamters will be treating as if the have a Maximum solve attached."""
        ...
    @ConvertSDToMaxApertures.setter
    def ConvertSDToMaxApertures(self, value: bool) -> None: ...

class IHPCSettings:
    """ZOSAPI.Tools.IHPCSettings"""
    @property
    def IsHPCConfigured(self) -> bool: ...
    @property
    def NodeCount(self) -> int: ...
    @property
    def MaxNodeCount(self) -> int: ...
    @property
    def InstanceType(self) -> HPCNodeSize: ...
    @property
    def ThreadsPerTask(self) -> int: ...
    @property
    def ShutdownTimeTicks(self) -> int: ...

class IMFCalculator(ISystemTool):
    """ZOSAPI.Tools.IMFCalculator

    Interfaces and methods for calculating the current Merit Function value. This interface can be accessed via the IOpticalSystemTools interface.
    """
    @property
    def MeritFunctionCalculation(self) -> float: ...

class IMaterialsCatalog(ISystemTool):
    """ZOSAPI.Tools.IMaterialsCatalog"""
    @property
    def SelectedCatalog(self) -> str: ...
    @SelectedCatalog.setter
    def SelectedCatalog(self, value: str) -> None: ...
    @property
    def SelectedMaterial(self) -> str: ...
    @SelectedMaterial.setter
    def SelectedMaterial(self, value: str) -> None: ...
    @property
    def NumberOfFitCoefficients(self) -> int: ...
    @property
    def CatalogComment(self) -> str: ...
    @CatalogComment.setter
    def CatalogComment(self, value: str) -> None: ...
    @property
    def MaterialFormula(self) -> MaterialFormulas: ...
    @MaterialFormula.setter
    def MaterialFormula(self, value: MaterialFormulas) -> None: ...
    @property
    def MaterialStatus(self) -> MaterialStatuses: ...
    @MaterialStatus.setter
    def MaterialStatus(self, value: MaterialStatuses) -> None: ...
    @property
    def D0(self) -> float: ...
    @D0.setter
    def D0(self, value: float) -> None: ...
    @property
    def D1(self) -> float: ...
    @D1.setter
    def D1(self, value: float) -> None: ...
    @property
    def D2(self) -> float: ...
    @D2.setter
    def D2(self, value: float) -> None: ...
    @property
    def E0(self) -> float: ...
    @E0.setter
    def E0(self, value: float) -> None: ...
    @property
    def E1(self) -> float: ...
    @E1.setter
    def E1(self, value: float) -> None: ...
    @property
    def Ltk(self) -> float: ...
    @Ltk.setter
    def Ltk(self, value: float) -> None: ...
    @property
    def TCE(self) -> float: ...
    @TCE.setter
    def TCE(self, value: float) -> None: ...
    @property
    def Temp(self) -> float: ...
    @Temp.setter
    def Temp(self, value: float) -> None: ...
    @property
    def p(self) -> float: ...
    @p.setter
    def p(self, value: float) -> None: ...
    @property
    def dPgF(self) -> float: ...
    @dPgF.setter
    def dPgF(self, value: float) -> None: ...
    @property
    def MinimumWavelength(self) -> float: ...
    @MinimumWavelength.setter
    def MinimumWavelength(self, value: float) -> None: ...
    @property
    def MaximumWavelength(self) -> float: ...
    @MaximumWavelength.setter
    def MaximumWavelength(self, value: float) -> None: ...
    @property
    def IgnoreThermalExpansion(self) -> bool: ...
    @IgnoreThermalExpansion.setter
    def IgnoreThermalExpansion(self, value: bool) -> None: ...
    @property
    def ExcludeSubstitution(self) -> bool: ...
    @ExcludeSubstitution.setter
    def ExcludeSubstitution(self, value: bool) -> None: ...
    @property
    def MetaMaterial(self) -> bool: ...
    @MetaMaterial.setter
    def MetaMaterial(self, value: bool) -> None: ...
    @property
    def MeltFreq(self) -> str: ...
    @MeltFreq.setter
    def MeltFreq(self, value: str) -> None: ...
    @property
    def Comment(self) -> str: ...
    @Comment.setter
    def Comment(self, value: str) -> None: ...
    @property
    def RelCost(self) -> str: ...
    @RelCost.setter
    def RelCost(self, value: str) -> None: ...
    @property
    def CR(self) -> str: ...
    @CR.setter
    def CR(self, value: str) -> None: ...
    @property
    def FR(self) -> str: ...
    @FR.setter
    def FR(self, value: str) -> None: ...
    @property
    def SR(self) -> str: ...
    @SR.setter
    def SR(self, value: str) -> None: ...
    @property
    def AR(self) -> str: ...
    @AR.setter
    def AR(self, value: str) -> None: ...
    @property
    def PR(self) -> str: ...
    @PR.setter
    def PR(self, value: str) -> None: ...
    @property
    def Nd(self) -> float: ...
    @property
    def Vd(self) -> float: ...
    def GetAllCatalogs(self) -> List[str]: ...
    def GetAllMaterials(self) -> List[str]: ...
    def GetCoefficientName(self, coeff: int) -> str: ...
    def GetFitCoefficient(self, coeff: int) -> float:
        """Returns the individual dispersion coefficient (0-indexed)

        Args:
            coeff
        """
        ...
    def SaveCatalog(self) -> bool:
        """Saves modified Material data. Needs to be applied for each modified glass"""
        ...
    def SetFitCoefficient(self, coeff: int, Value: float) -> None:
        """Changes the individual dispersion coefficient (0-indexed)

        Args:
            coeff
            Value
        """
        ...

class IOpticalSystemTools:
    """ZOSAPI.Tools.IOpticalSystemTools

    Methods to run various system-wide tools. This interface can be accessed via the IOpticalSystem interface. Note that only one ISystemTool can be open at a time; the previous tool must be closed using Close before a new one can be opened.
    """
    @property
    def CurrentTool(self) -> ISystemTool:
        """Gets the currently open tool. Note that if a tool is already open, all attempts to open a new tool will fail."""
        ...
    @property
    def Progress(self) -> int:
        """Gets the progress of the currently running tool, if the tool reports incremental progress."""
        ...
    @property
    def Status(self) -> str:
        """Gets the status of the currently running tool, if the tool reports incremental status messages."""
        ...
    @property
    def IsRunning(self) -> bool:
        """Gets a value indicating whether the CurrentTool is currently running asynchronously."""
        ...
    def CreateDoubleMatrix(self, Rows: int, Cols: int) -> List[float]:
        """Creates a 2D matrix double doubles. This is primarily useful when you need to create a SAFEARRAY for access to the API from a COM-based interface.

        Args:
            Rows: The number of rows in the output matrix.
            Cols: The number of columns in the output matrix.
        """
        ...
    def CreateDoubleVector(self, numElements: int) -> List[float]:
        """Creates a 1D array of doubles. This is primarily useful when you need to create a SAFEARRAY for access to the API from a COM-based interface.

        Args:
            numElements: The number elements in the output array.
        """
        ...
    def GetConversionFromSystemUnits(self, toUnits: ZOSAPI.SystemData.ZemaxSystemUnits) -> float:
        """Enum parameter:
            toUnits -> ZOSAPI.SystemData.ZemaxSystemUnits

        Gets the conversion factor from system units to the specified units. Returns s such that [x' = s * x] where x is in system units and x' is in "toUnits".

        Args:
            toUnits: To units.
        """
        ...
    def GetConversionToSystemUnits(self, fromUnits: ZOSAPI.SystemData.ZemaxSystemUnits) -> float:
        """Enum parameter:
            fromUnits -> ZOSAPI.SystemData.ZemaxSystemUnits

        Gets the conversion factor from the specified units to system units. Returns s such that [x' = s * x] where x is in "fromUnits" and x' is in system units.

        Args:
            fromUnits: From units.
        """
        ...
    def GetHPCSettingsCustom(self, nodeCount: int, instanceType: HPCNodeSize) -> IHPCSettings:
        """Enum parameter:
            instanceType -> ZOSAPI.Tools.HPCNodeSize
        """
        ...
    def GetHPCSettingsFromPrefs(self) -> IHPCSettings: ...
    def OpenBatchRayTrace(self) -> ZOSAPI.Tools.RayTrace.IBatchRayTrace:
        """Opens the Batch Ray Trace tool."""
        ...
    def OpenConvertToNSCGroup(self) -> IConvertToNSCGroup:
        """Opens the Convert to NSC Group tool."""
        ...
    def OpenCreateZAR(self) -> ZOSAPI.Tools.General.ICreateArchive:
        """Opens the Create Zemax Archive (ZAR) tool."""
        ...
    def OpenCriticalRaysetGenerator(self) -> ICriticalRaysetGenerator:
        """Opens the critical rayset generator tool."""
        ...
    def OpenDesignLockdown(self) -> IDesignLockdown:
        """Opens the Design Lockdown tool."""
        ...
    def OpenExportCAD(self) -> ZOSAPI.Tools.General.IExportCAD:
        """Opens the Export to Cad tool."""
        ...
    def OpenGlobalOptimization(self) -> ZOSAPI.Tools.Optimization.IGlobalOptimization:
        """Opens the Global Optimization tool."""
        ...
    def OpenGlobalOptimization_HPC(self, hpcSettings: IHPCSettings) -> ZOSAPI.Tools.Optimization.IGlobalOptimization: ...
    def OpenHammerOptimization(self) -> ZOSAPI.Tools.Optimization.IHammerOptimization:
        """Opens the Hammer Optimization tool."""
        ...
    def OpenHammerOptimization_HPC(self, hpcSettings: IHPCSettings) -> ZOSAPI.Tools.Optimization.IHammerOptimization: ...
    def OpenLensCatalogs(self) -> ZOSAPI.Tools.General.ILensCatalogs:
        """Opens the Lens Catalogs tool."""
        ...
    def OpenLightningTrace(self) -> ZOSAPI.Tools.RayTrace.ILightningTrace:
        """Opens the Lightning Trace tool."""
        ...
    def OpenLocalOptimization(self) -> ZOSAPI.Tools.Optimization.ILocalOptimization:
        """Opens the Local Optimization tool."""
        ...
    def OpenMaterialsCatalog(self) -> IMaterialsCatalog: ...
    def OpenMeritFunctionCalculator(self) -> IMFCalculator:
        """Opens the Merit Function Calculator tool."""
        ...
    def OpenNSCRayTrace(self) -> ZOSAPI.Tools.RayTrace.INSCRayTrace:
        """Creates a new NSC Ray Trace instance. Note -- only one instance of this tool can be open at a time. See the INSCRayTrace documentation for more information."""
        ...
    def OpenNSCRayTrace_HPC(self, hpcSettings: IHPCSettings) -> ZOSAPI.Tools.RayTrace.INSCRayTrace: ...
    def OpenQuickAdjust(self) -> ZOSAPI.Tools.General.IQuickAdjust:
        """Opens the Quick Adjust tool."""
        ...
    def OpenQuickFocus(self) -> ZOSAPI.Tools.General.IQuickFocus:
        """Opens the Quick Focus tool."""
        ...
    def OpenQuickSensitivity(self) -> ZOSAPI.Tools.Tolerancing.IQuickSensitivity: ...
    def OpenRMSSpotRadiusCalculator(self) -> ZOSAPI.Tools.General.IComputeRMSSpotSize:
        """Opens the RMS spot radius calculator. Note that this is only valid in sequential mode."""
        ...
    def OpenRayDatabaseReader(self) -> ZOSAPI.Tools.RayTrace.IZRDReader: ...
    def OpenRestoreZAR(self) -> ZOSAPI.Tools.General.IRestoreArchive:
        """Opens the Restore Zemax Archive (ZAR) tool."""
        ...
    def OpenScale(self) -> ZOSAPI.Tools.General.IScale:
        """Opens the Scale Lens tool."""
        ...
    def OpenShadedModelVisualizationExport(self) -> IShadedModelVisualizationExport:
        """Opens the Shaded Model Visualization export tool. This tool allows retreieving a list of triangles representing the solid models used for Shaded Model visualization."""
        ...
    def OpenToleranceDataViewer(self) -> ZOSAPI.Tools.Tolerancing.IToleranceDataViewer: ...
    def OpenTolerancing(self) -> ZOSAPI.Tools.Tolerancing.ITolerancing:
        """Opens the Tolerancing tool."""
        ...
    def OpenTolerancing_HPC(self, hpcSettings: IHPCSettings) -> ZOSAPI.Tools.Tolerancing.ITolerancing: ...
    def RemoveAllVariables(self) -> bool:
        """Removes all variables in the system."""
        ...
    def SetAllRadiiVariable(self) -> int:
        """Makes all radii in the system variable."""
        ...
    def SetAllThicknessesVariable(self) -> int:
        """Makes all thicknesses in the system variable."""
        ...

class IShadedModelTriangleList:
    """ZOSAPI.Tools.IShadedModelTriangleList"""
    @property
    def NumberOfTriangles(self) -> int:
        """The number of Triangles available."""
        ...
    @property
    def NumberOfSurfaces(self) -> int: ...
    @property
    def TotalNumberOfObjects(self) -> int: ...
    @property
    def XCoords(self) -> ZOSAPI.Common.IVectorData:
        """The X coordinates for all vertices of all triangles"""
        ...
    @XCoords.setter
    def XCoords(self, value: ZOSAPI.Common.IVectorData) -> None: ...
    @property
    def YCoords(self) -> ZOSAPI.Common.IVectorData:
        """The Y coordinates for all vertices of all triangles"""
        ...
    @YCoords.setter
    def YCoords(self, value: ZOSAPI.Common.IVectorData) -> None: ...
    @property
    def ZCoords(self) -> ZOSAPI.Common.IVectorData:
        """The Z coordinates for all vertices of all triangles"""
        ...
    @ZCoords.setter
    def ZCoords(self, value: ZOSAPI.Common.IVectorData) -> None: ...
    @property
    def XNormals(self) -> ZOSAPI.Common.IVectorData: ...
    @XNormals.setter
    def XNormals(self, value: ZOSAPI.Common.IVectorData) -> None: ...
    @property
    def YNormals(self) -> ZOSAPI.Common.IVectorData: ...
    @YNormals.setter
    def YNormals(self, value: ZOSAPI.Common.IVectorData) -> None: ...
    @property
    def ZNormals(self) -> ZOSAPI.Common.IVectorData: ...
    @ZNormals.setter
    def ZNormals(self, value: ZOSAPI.Common.IVectorData) -> None: ...
    @property
    def SurfaceIndex(self) -> ZOSAPI.Common.IVectorData: ...
    @SurfaceIndex.setter
    def SurfaceIndex(self, value: ZOSAPI.Common.IVectorData) -> None: ...
    @property
    def ObjectIndex(self) -> ZOSAPI.Common.IVectorData: ...
    @ObjectIndex.setter
    def ObjectIndex(self, value: ZOSAPI.Common.IVectorData) -> None: ...
    def GetVertex(self, TriangleNumber: int, Vertex: VertexOrder) -> Tuple[bool, float, float, float, float, float, float, int, int]:
        """Enum parameter:
            Vertex -> ZOSAPI.Tools.VertexOrder

        Retrieve the X, Y, and Z position for the Vertex of the specified triangle.

        Args:
            TriangleNumber: The triangle index to retrieve (0 to NumberOfTriangles-1).
            Vertex: The index for the Vertex of the triangle. Valid values 0-2
            X: The X coordinates for the specified triangle Vertex.
            Y: The Y coordinates for the specified triangle Vertex.
            Z: The Z coordinates for the specified triangle Vertex.
            XNormal: The Normal for the X coordinates for the specified triangle Vertex.
            YNormal: The Normal for the Y coordinates for the specified triangle Vertex.
            ZNormal: The Normal for the Z coordinates for the specified triangle Vertex.
            Surface
            Object

        Returns:
            true if the triangleNumber was valid, false otherwise.
        """
        ...
    def NumberOfObjects(self, Surface: int) -> List[int]: ...

class IShadedModelVisualizationExport(ISystemTool):
    """ZOSAPI.Tools.IShadedModelVisualizationExport

    Interfaces and methods for getting a set of triangles for selected parts of the system. This interface can be accessed via the IOpticalSystemTools interface.
    """
    @property
    def StartSurface(self) -> int:
        """The first surface which will be available in the output triangles. If set to -1, every surface from the beginning to the EndSurface will be available."""
        ...
    @StartSurface.setter
    def StartSurface(self, value: int) -> None: ...
    @property
    def EndSurface(self) -> int:
        """The last surface which will be available in the output triangles. If set to -1, every surface after the StartSurface will be available."""
        ...
    @EndSurface.setter
    def EndSurface(self, value: int) -> None: ...
    @property
    def Object(self) -> int:
        """The Object index from a non-sequential surface which will be available in the output triangles. If specified as -1, all objects will be available."""
        ...
    @Object.setter
    def Object(self, value: int) -> None: ...
    def GetResults(self) -> IShadedModelTriangleList:
        """Gets the triangles for the specified surfaces/objects, if available.

        Returns:
            IShadedModelTriangleList
        """
        ...

class ISystemTool:
    """ZOSAPI.Tools.ISystemTool

    Base interface for all system tools. See IOpticalSystemTools for access to specific tools.
    """
    @property
    def Progress(self) -> int:
        """Gets the progress of the current tool, if supported."""
        ...
    @property
    def Status(self) -> str:
        """Gets the status of the current tool, if supporoted."""
        ...
    @property
    def IsRunning(self) -> bool:
        """Gets a value indicating whether the tool is currently running asynchronously."""
        ...
    @property
    def CanCancel(self) -> bool:
        """Gets a value indicating whether the tool can be cancelled."""
        ...
    @property
    def IsAsynchronous(self) -> bool:
        """Gets a value indicating whether the tool runs asynchronously (i.e. on a thread)."""
        ...
    @property
    def IsFiniteDuration(self) -> bool:
        """Gets a value indicating whether this tool will complete on its own."""
        ...
    @property
    def IsValid(self) -> bool:
        """Gets a value indicating whether the input settings are valid."""
        ...
    @property
    def Succeeded(self) -> bool:
        """Gets a value indicating whether the tool execution succeeded."""
        ...
    @property
    def ErrorMessage(self) -> str:
        """If Succeeded is false, get the error messages; otherwise, null."""
        ...
    def Cancel(self) -> bool:
        """Cancels the currently running asynchronous tool.

        Returns:
            true if the tool is asynchronous and is currently running; otherwise, false
        """
        ...
    def Close(self) -> bool:
        """Closes this tool and frees up and associated resources.

        Returns:
            true if the tool is not currently running; otherwise, false.
        """
        ...
    def Run(self) -> bool:
        """Start the tool. Note that for synchronous tools (see IsAsynchronous), this call will block until completion. If it is asynchronous it will start running but return immediately.

        Returns:
            true if the tool successfully started (and, for synchronous tools, completed); otherwise, false. Note that if the tool is already running this will return false .
        """
        ...
    def RunAndWaitForCompletion(self) -> bool:
        """Sames as calling Run followed by WaitForCompletion.

        Returns:
            true if the call to Run succeeded, IsAsynchronous is true, and IsFiniteDuration is false; otherwise, false
        """
        ...
    def RunAndWaitWithTimeout(self, timeOutSeconds: float) -> RunStatus:
        """Starts the tool running, and waits for it to complete with the specified timeout value. Note that if the timeout is exceeded this method will return, however the tool will continue to run.

        Args:
            timeOutSeconds: The time out value (seconds). Note that this value must be greater than zero, else a InvalidTimeout value will be returned.

        Returns:
            A RunStatus value indicating the tool state.///
        """
        ...
    def WaitForCompletion(self) -> bool:
        """Waits for the asynchronous tool to complete.

        Returns:
            true if the tool is running, it is asynchronous, and it has a finite run duration; otherwise, false.
        """
        ...
    def WaitWithTimeout(self, timeOutSeconds: float) -> RunStatus:
        """Waits for the currently running tool to complete, with a specified time out value. Note that if the timeout is exceeded this method will return, however the tool will continue to run. Also note that this method will not start the tool running if it is not already.

        Args:
            timeOutSeconds: The time out value (seconds). Note that this value must be greater than zero, else a InvalidTimeout value will be returned.

        Returns:
            A RunStatus value indicating the tool state.///
        """
        ...

class MaterialFormulas(IntEnum):
    """ZOSAPI.Tools.MaterialFormulas"""
    Schott = 1
    Sellmeier1 = 2
    Herzberger = 3
    Sellmeier2 = 4
    Conrady = 5
    Sellmeier3 = 6
    Handbook1 = 7
    Handbook2 = 8
    Sellmeier4 = 9
    Extended = 10
    Sellmeier5 = 11
    Extended2 = 12
    Extended3 = 13

class MaterialStatuses(IntEnum):
    """ZOSAPI.Tools.MaterialStatuses"""
    Standard = 0
    Preferred = 1
    Obsolete = 2
    Special = 3
    Melt = 4

class RayPatternOption(IntEnum):
    """ZOSAPI.Tools.RayPatternOption"""
    XyFan = 0
    XFan = 1
    YFan = 2
    ChiefAndRing = 3
    List = 4
    Grid = 6
    ChiefAndMarginals = 8

class RunStatus(IntEnum):
    """ZOSAPI.Tools.RunStatus"""
    Completed = 0
    """The tool completed running."""
    FailedToStart = 1
    """The tool either failed to start, or a wait was requested on a tool that was not already running."""
    TimedOut = 2
    """The time out value was exceeded; note that the tool will continue running."""
    InvalidTimeout = 3
    """An invalid timeout value was specified."""

class VertexOrder(IntEnum):
    """ZOSAPI.Tools.VertexOrder"""
    First = 0
    Second = 1
    Third = 2
