# Auto-generated by zosapi-stubgen — do not edit by hand.
# Re-run `zosapi-stubgen` to refresh after an OpticStudio upgrade.
from __future__ import annotations
from typing import (
    Any, Dict, Generic, Iterable, Iterator, List,
    Optional, overload, Sequence, Set, Tuple, TypeVar, Union,
)
from enum import IntEnum, IntFlag
from datetime import datetime, timedelta

class DataType(IntEnum):
    """ZOSAPI.Analysis.Settings.RMS.RMSField.DataType"""
    Wavefront = 0
    SpotRadius = 1
    Spot_X = 2
    Spot_Y = 3
    StrehlRation = 4
