# Auto-generated by zosapi-stubgen — do not edit by hand.
# Re-run `zosapi-stubgen` to refresh after an OpticStudio upgrade.
from __future__ import annotations
from typing import (
    Any, Dict, Generic, Iterable, Iterator, List,
    Optional, overload, Sequence, Set, Tuple, TypeVar, Union,
)
from enum import IntEnum, IntFlag
from datetime import datetime, timedelta

import ZOSAPI.Common
import ZOSAPI.Editors
import ZOSAPI.Wizards

class ITDERow(ZOSAPI.Editors.IEditorRow):
    """ZOSAPI.Editors.TDE.ITDERow

    All data for a Tolerance Data Editor operand. This interface can be accessed via the IToleranceDataEditor interface.
    """
    @property
    def IsActive(self) -> bool:
        """Gets a value indicating whether this instance is active (i.e. refers to a valid surface in the system)."""
        ...
    @property
    def OperandNumber(self) -> int:
        """Gets the operand number for this row."""
        ...
    @property
    def TypeName(self) -> str: ...
    @property
    def Type(self) -> ToleranceOperandType:
        """Gets the current operand type. Use ChangeType to change the operand type."""
        ...
    @property
    def DoNotAdjustDuringInverseTolerancing(self) -> bool: ...
    @DoNotAdjustDuringInverseTolerancing.setter
    def DoNotAdjustDuringInverseTolerancing(self, value: bool) -> None: ...
    @property
    def IgnoreThisOperandDuringTolerancing(self) -> bool: ...
    @IgnoreThisOperandDuringTolerancing.setter
    def IgnoreThisOperandDuringTolerancing(self, value: bool) -> None: ...
    @property
    def RowColor(self) -> ZOSAPI.Common.ZemaxColor: ...
    @RowColor.setter
    def RowColor(self, value: ZOSAPI.Common.ZemaxColor) -> None: ...
    @property
    def Min(self) -> float: ...
    @Min.setter
    def Min(self, value: float) -> None: ...
    @property
    def MinCell(self) -> ZOSAPI.Editors.IEditorCell: ...
    @property
    def IsMinUsed(self) -> bool: ...
    @property
    def Max(self) -> float: ...
    @Max.setter
    def Max(self, value: float) -> None: ...
    @property
    def MaxCell(self) -> ZOSAPI.Editors.IEditorCell: ...
    @property
    def IsMaxUsed(self) -> bool: ...
    @property
    def Comment(self) -> str: ...
    @Comment.setter
    def Comment(self, value: str) -> None: ...
    @property
    def CommentCell(self) -> ZOSAPI.Editors.IEditorCell: ...
    @property
    def Param1(self) -> int: ...
    @Param1.setter
    def Param1(self, value: int) -> None: ...
    @property
    def Param1Cell(self) -> ZOSAPI.Editors.IEditorCell: ...
    @property
    def IsParam1Used(self) -> bool: ...
    @property
    def Param2(self) -> int: ...
    @Param2.setter
    def Param2(self, value: int) -> None: ...
    @property
    def Param2Cell(self) -> ZOSAPI.Editors.IEditorCell: ...
    @property
    def IsParam2Used(self) -> bool: ...
    @property
    def Param3(self) -> int: ...
    @Param3.setter
    def Param3(self, value: int) -> None: ...
    @property
    def Param3Cell(self) -> ZOSAPI.Editors.IEditorCell: ...
    @property
    def IsParam3Used(self) -> bool: ...
    @property
    def Nominal(self) -> float: ...
    @property
    def NominalCell(self) -> ZOSAPI.Editors.IEditorCell: ...
    @property
    def IsNominalUsed(self) -> bool: ...
    def AvailableOperandTypes(self) -> List[ToleranceOperandType]: ...
    def ChangeType(self, type_: ToleranceOperandType) -> bool:
        """Enum parameter:
            type_ -> ZOSAPI.Editors.TDE.ToleranceOperandType

        Changes the current operand to the specified type.

        Args:
            type: The new type.
        """
        ...
    def GetOperandCell(self, Col: ToleranceColumn) -> ZOSAPI.Editors.IEditorCell:
        """Enum parameter:
            Col -> ZOSAPI.Editors.TDE.ToleranceColumn

        Gets the specified operand cell data.

        Args:
            Col: The column.
        """
        ...

class IToleranceDataEditor(ZOSAPI.Editors.IEditor):
    """ZOSAPI.Editors.TDE.IToleranceDataEditor

    This interface defines all properties and methods needed to interact with the Tolerance Data Editor. This interface can be accessed via the IOpticalSystem interface.
    """
    @property
    def RowToOperandOffset(self) -> int:
        """Offset from a row index to operand index (always 1)."""
        ...
    @property
    def NumberOfOperands(self) -> int:
        """Gets the total number of operands in the current system."""
        ...
    @property
    def FirstColumn(self) -> ToleranceColumn:
        """Gets the first available column."""
        ...
    @property
    def LastColumn(self) -> ToleranceColumn:
        """Gets the last available column."""
        ...
    @property
    def NSCToleranceWizard(self) -> ZOSAPI.Wizards.INSCToleranceWizard:
        """The Nonsequential Tolerance Wizard"""
        ...
    @property
    def SEQToleranceWizard(self) -> ZOSAPI.Wizards.ISEQToleranceWizard:
        """The Sequential Tolerance Wizard"""
        ...
    def AddOperand(self) -> ITDERow:
        """Adds a new operand as the last operand in the system."""
        ...
    def CopyOperands(self, fromOperandNumber: int, NumberOfOperands: int, toOperandNumber: int) -> int:
        """Copy and paste the specified number of operands from one location to another. Note that it is okay for the source and destination to overlap.

        Args:
            fromOperandNumber: First operand number to copy (1 to NumberOfOperands).
            NumberOfOperands: The number of operands to copy.
            toOperandNumber: Row to start inserting the operands (1 to NumberOfOperands+1).

        Returns:
            The number of operands actually copied.
        """
        ...
    def CopyOperandsFrom(self, fromEditor: IToleranceDataEditor, fromOperandNumber: int, NumberOfOperands: int, toOperandNumber: int) -> int:
        """Copy and paste the specified number of operands from one location (in the specified system) to another location (in this system). Note that it is okay for the source and destination to overlap.

        Args:
            fromEditor: System to copy the operands from.
            fromOperandNumber: First operand number to copy (1 to NumberOfOperands).
            NumberOfOperands: The number of operands to copy.
            toOperandNumber: To operand number (1 to NumberOfOperands+1).

        Returns:
            The number of operands actually copied.
        """
        ...
    def GetOperandAt(self, OperandNumber: int) -> ITDERow:
        """Gets the data for the specified operand.

        Args:
            OperandNumber: The operand number (1 to NumberOfOperands).
        """
        ...
    def HideTDE(self) -> None:
        """Closes this editor in the UI. Note that this only has an effect if the Mode is Plugin."""
        ...
    def InsertNewOperandAt(self, OperandNumber: int) -> ITDERow:
        """Inserts a new operand at the specified position.

        Args:
            OperandNumber: The operand number (1 to NumberOfOperands+1).
        """
        ...
    def LoadToleranceFile(self, fileName: str) -> bool:
        """Loads a tolerance file, replacing the tolerances in the current lens.

        Args:
            fileName: Name of the input file. If the file name contains the complete path, such as C:\\MYDIR\\MYLENS.TOL, then the specified file will be loaded. If the path is left off, then the [data]\\Tolerance folder will be used.
        """
        ...
    def RemoveOperandAt(self, OperandNumber: int) -> bool:
        """Removes the operand at the specified location.

        Args:
            OperandNumber: The operand number (1 to NumberOfOperands).

        Returns:
            true if the operand was successfully remove; otherwise, false.
        """
        ...
    def RemoveOperandsAt(self, OperandNumber: int, numOperands: int) -> int:
        """Removes one or more operands at the specified location.

        Args:
            OperandNumber: The first operand number to remove (1 to NumberOfOperands).
            numOperands: The number operands to remove.

        Returns:
            The number of operands actually removed.
        """
        ...
    def SaveToleranceFile(self, fileName: str) -> None:
        """Saves the current tolerances to a file.

        Args:
            fileName: Name of the output file. If the file name contains the complete path, such as C:\\MYDIR\\MYLENS.TOL, then the specified file will be created. If the path is left off, then the [data]\\Tolerance folder will be used.
        """
        ...
    def ShowTDE(self) -> bool:
        """Shows this editor in the UI. Note that this only has an effect if the Mode is Plugin."""
        ...

class ToleranceColumn(IntEnum):
    """ZOSAPI.Editors.TDE.ToleranceColumn"""
    Param1 = 2
    Param2 = 3
    Param3 = 4
    Nominal = 5
    Min = 6
    Max = 7
    Comment = 8

class ToleranceOperandType(IntEnum):
    """ZOSAPI.Editors.TDE.ToleranceOperandType"""
    TOFF = 0
    TRAD = 1
    TCUR = 2
    TFRN = 3
    TTHI = 4
    TCON = 5
    TSDI = 6
    TSDX = 7
    TSDY = 8
    TSDR = 9
    TSTX = 10
    TSTY = 11
    TIRX = 12
    TIRY = 13
    TIRR = 14
    TPAR = 15
    TEDV = 16
    TEDX = 17
    TEDY = 18
    TEDR = 19
    TETX = 20
    TETY = 21
    TETZ = 22
    TUDX = 23
    TUDY = 24
    TUTX = 25
    TUTY = 26
    TUTZ = 27
    TIND = 28
    TABB = 29
    TEXI = 30
    SAVE = 31
    COMP = 32
    CPAR = 33
    CEDV = 34
    CMCO = 35
    STAT = 36
    TWAV = 37
    TNPS = 38
    TNPA = 39
    TMCO = 40
    TEZI = 41
    TCMU = 42
    SEED = 43
    COMM = 44
    TPAI = 45
    TCIO = 46
    TCEO = 47
    TNMA = 48
    CNPA = 49
    CNPS = 50
    TRLX = 51
    TRLY = 52
    TRLR = 53
    TARX = 54
    TARY = 55
    TARR = 56
