# Auto-generated by zosapi-stubgen — do not edit by hand.
# Re-run `zosapi-stubgen` to refresh after an OpticStudio upgrade.
from __future__ import annotations
from typing import (
    Any, Dict, Generic, Iterable, Iterator, List,
    Optional, overload, Sequence, Set, Tuple, TypeVar, Union,
)
from enum import IntEnum, IntFlag
from datetime import datetime, timedelta

import ZOSAPI.Analysis

class IAS_QYField:
    """ZOSAPI.Analysis.Tolerancing.QuickYield.IAS_QYField

    Provides methods for setting and inspecting the field configuration for a Quick Yield analysis.
    """
    @property
    def IsFieldUser(self) -> bool:
        """Gets a value indicating whether the field Quick Analysis is configured to use comes from the set of user-defined fields."""
        ...
    @property
    def IsFieldSymmetricXY(self) -> bool:
        """Gets a value indicating whether the field Quick Analysis is configured to use comes from the set of XY-symmetric fields."""
        ...
    @property
    def IsFieldSymmetricY(self) -> bool:
        """Gets a value indicating whether the field Quick Analysis is configured to use comes from the set of Y-symmetric fields."""
        ...
    def GetFieldSymmetricXY(self) -> XYSymmetricField:
        """Gets a value which specifies the XY-symmetric field the Quick Yield analysis is configured to use.

        Returns:
            The XY-symmetric field the Quick Yield analysis is configured to use.
        """
        ...
    def GetFieldSymmetricY(self) -> YSymmetricField:
        """Gets a value which specifies the Y-symmetric field the Quick Yield analysis is configured to use.

        Returns:
            The Y-symmetric field the Quick Yield analysis is configured to use.
        """
        ...
    def GetFieldUser(self) -> int:
        """Gets a value which specifies the User Defined field the Quick Yield analysis is configured to use.

        Returns:
            The 1-based field number the Quick Yield analysis is configured to use. A value of 0 means "all fields" when there are at most twelve user-defined fields and "first 12" when there are more than twelve user-defined fields.
        """
        ...
    def SetFieldSymmetricXY(self, field: XYSymmetricField) -> ZOSAPI.Analysis.IMessage:
        """Enum parameter:
            field -> ZOSAPI.Analysis.Tolerancing.QuickYield.XYSymmetricField

        Configures the Quick Yield analysis to use a field from the XY-symmetric set of fields.

        Args:
            field: The field to use in the Quick Yield analysis.

        Returns:
            A message indicating the success or failure of the operation. Null indicates success.
        """
        ...
    def SetFieldSymmetricY(self, field: YSymmetricField) -> ZOSAPI.Analysis.IMessage:
        """Enum parameter:
            field -> ZOSAPI.Analysis.Tolerancing.QuickYield.YSymmetricField

        Configures the Quick Yield analysis to use a field from the Y-symmetric set of fields.

        Args:
            field: The field to use in the Quick Yield analysis.

        Returns:
            A message indicating the success or failure of the operation. Null indicates success.
        """
        ...
    def SetFieldUser(self, fieldNumber: int) -> ZOSAPI.Analysis.IMessage:
        """Configures the Quick Yield analysis to use a user-defined field.

        Args:
            fieldNumber: The (1-based) field number or 0. The value 0 means "All" for a system with at most twelve user-defined fields; it means "First 12" for a system with more than twelve user- defined fields.

        Returns:
            A message indicating the success or failure of the operation. Null indicates success.
        """
        ...

class XYSymmetricField(IntEnum):
    """ZOSAPI.Analysis.Tolerancing.QuickYield.XYSymmetricField

    Specifies which field from the XY-symmetric set to use for a Quick Yield analysis.
    """
    All = 0
    """All XY-symmetric fields."""
    Zero = 1
    """The field whose (X, Y) coordinates are (0, 0)."""
    YPositive70Percent = 2
    """The field whose (X, Y) coordinates are (0, 0.7×MaximumField.Y)."""
    YNegative70Percent = 3
    """The field whose (X, Y) coordinates are (0, -0.7×MaximumField.Y)."""
    YPositive100Percent = 4
    """The field whose (X, Y) coordinates are (0, MaximumField.Y)."""
    YNegative100Percent = 5
    """The field whose (X, Y) coordinates are (0, -MaximumField.Y)."""
    XPositive70Percent = 6
    """The field whose (X, Y) coordinates are (0.7×MaximumField.X, 0)."""
    XNegative70Percent = 7
    """The field whose (X, Y) coordinates are (-0.7×MaximumField.X, 0)."""
    XPositive100Percent = 8
    """The field whose (X, Y) coordinates are (MaximumField.X, 0)."""
    XNegative100Percent = 9
    """The field whose (X, Y) coordinates are (-MaximumField.X, 0)."""

class YSymmetricField(IntEnum):
    """ZOSAPI.Analysis.Tolerancing.QuickYield.YSymmetricField

    Specifies which field from the Y-symmetric set to use for a Quick Yield analysis.
    """
    All = 0
    """All Y-symmetric fields"""
    Zero = 1
    """The field whose (X, Y) coordinates are (0, 0)."""
    Positive70Percent = 2
    """The field whose (X, Y) coordinates are (0, 0.7×MaximumField.Y)."""
    Negative70Percent = 3
    """The field whose (X, Y) coordinates are (0, -0.7×MaximumField.Y)."""
    Positive100Percent = 4
    """The field whose (X, Y) coordinates are (0, MaximumField.Y)."""
    Negative100Percent = 5
    """The field whose (X, Y) coordinates are (0, -MaximumField.Y)."""
