# Auto-generated by zosapi-stubgen — do not edit by hand.
# Re-run `zosapi-stubgen` to refresh after an OpticStudio upgrade.
from __future__ import annotations
from typing import (
    Any, Dict, Generic, Iterable, Iterator, List,
    Optional, overload, Sequence, Set, Tuple, TypeVar, Union,
)
from enum import IntEnum, IntFlag
from datetime import datetime, timedelta

import ZOSAPI.Analysis
import ZOSAPI.Tools

class BatchRayTraceDataEntry:
    """ZOSAPI.Tools.RayTrace.BatchRayTraceDataEntry"""
    ...

class BatchRayTraceDataHolder:
    """ZOSAPI.Tools.RayTrace.BatchRayTraceDataHolder"""
    def __init__(self) -> None: ...
    def __init__(self, data: List[BatchRayTraceDataEntry]) -> None: ...
    def __init__(self, info: Any, context: Any) -> None: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...

class IBatchRayTrace(ZOSAPI.Tools.ISystemTool):
    """ZOSAPI.Tools.RayTrace.IBatchRayTrace

    Interfaces and methods for running a ray trace on multiple rays at a time. This interface can be accessed via the IOpticalSystemTools interface.
    """
    def CreateDirectPol(self, MaxRays: int, rayType: RaysType, Ex: float, Ey: float, phax: float, phay: float, startSurface: int, toSurface: int) -> IRayTraceDirectPolData:
        """Enum parameter:
            rayType -> ZOSAPI.Tools.RayTrace.RaysType

        Performs a batch polarized ray trace, using direct x/y/z coordinates; this is similar to the DDE ray trace command, mode 3. See the OpticStudio help manual for more information.

        Args:
            MaxRays: The maximum rays.
            rayType: Type of the ray.
            Ex: ex.
            Ey: ey.
            phax: phase x.
            phay: phase y.
            startSurface: The start surface.
            toSurface: To surface.
        """
        ...
    def CreateDirectUnpol(self, MaxRays: int, rayType: RaysType, startSurface: int, toSurface: int) -> IRayTraceDirectUnpolData:
        """Enum parameter:
            rayType -> ZOSAPI.Tools.RayTrace.RaysType

        Performs a batch unpolarized ray trace, using direct x/y/z coordinates; this is similar to the DDE ray trace command, mode 1. See the OpticStudio help manual for more information.

        Args:
            MaxRays: The maximum rays.
            rayType: Type of the ray.
            startSurface: The start surface.
            toSurface: To surface.
        """
        ...
    def CreateNSC(self, MaxRays: int, maxSegments: int, coherenceLength: float) -> IRayTraceNSCData:
        """Creates a interface to define custom non-sequential rays.

        Args:
            MaxRays: The maximum rays.
            maxSegments: The maximum segments.
            coherenceLength: The coherence length to use if performing a polarized ray trace. If set to 0, the same coherence value will be used for all rays. Any other value will result in a random coherence value for each ray (for more information, see the OpticStudio documentation regarding Coherence Length).
        """
        ...
    def CreateNSCSourceData(self, maxSegments: int, coherenceLength: float) -> IRayTraceNSCSourceData: ...
    def CreateNormPol(self, MaxRays: int, rayType: RaysType, Ex: float, Ey: float, phaX: float, phaY: float, toSurface: int) -> IRayTraceNormPolData:
        """Enum parameter:
            rayType -> ZOSAPI.Tools.RayTrace.RaysType

        Performs a batch polarized ray trace, using normalized pupil coordinates; this is similar to the DDE ray trace command, mode 2. See the OpticStudio help manual for more information.

        Args:
            MaxRays: The maximum rays.
            rayType: Type of the ray.
            Ex: ex.
            Ey: ey.
            phaX: phase x.
            phaY: phase y.
            toSurface: To surface.
        """
        ...
    def CreateNormUnpol(self, MaxRays: int, rayType: RaysType, toSurface: int) -> IRayTraceNormUnpolData:
        """Enum parameter:
            rayType -> ZOSAPI.Tools.RayTrace.RaysType

        Performs a batch unpolarized ray trace, using normalized pupil coordinates; this is similar to the DDE ray trace command, mode 0. See the OpticStudio help manual for more information.

        Args:
            MaxRays: The maximum rays.
            rayType: Type of the ray.
            toSurface: To surface.
        """
        ...
    def GetDirectFieldCoordinates(self, waveNumber: int, rayType: RaysType, Hx: float, Hy: float, Px: float, Py: float) -> Tuple[bool, float, float, float, float, float, float]:
        """Enum parameter:
            rayType -> ZOSAPI.Tools.RayTrace.RaysType

        Convert from Normalized pupil coordinates to X/Y/Z coordinates.

        Args:
            waveNumber: The wave number.
            rayType: Type of the ray.
            Hx: hx.
            Hy: hy.
            Px: px.
            Py: py.
            X: x.
            Y: y.
            Z: z.
            L: l.
            M: m.
            N: n.
        """
        ...
    def GetPhase(self, L: float, M: float, N: float, jx: float, jy: float, xPhaseDeg: float, yPhaseDeg: float, intensity: float) -> Tuple[float, float, float, float, float, float]: ...
    def SingleRayDirectPol(self, rayType: RaysType, Ex: float, Ey: float, phaX: float, phaY: float, startSurface: int, toSurface: int, waveNumber: int, X: float, Y: float, Z: float, L: float, M: float, N: float) -> Tuple[bool, int, int, float, float, float, float, float, float, float]:
        """Enum parameter:
            rayType -> ZOSAPI.Tools.RayTrace.RaysType

        Performs the same calculation as CreateDirectPol, but for one ray at a time.

        Args:
            rayType: Type of the ray.
            Ex: ex.
            Ey: ey.
            phaX: phase x.
            phaY: phase y.
            startSurface: The start surface.
            toSurface: To surface.
            waveNumber: The wave number.
            X: x.
            Y: y.
            Z: z.
            L: l.
            M: m.
            N: n.
            ErrorCode: The error code.
            vignetteCode: The vignette code.
            exro: exro.
            exio: exio.
            eyro: eyro.
            eyio: eyio.
            ezro: ezro.
            ezio: ezio.
            intensity: The intensity.
        """
        ...
    def SingleRayDirectPolFull(self, rayType: RaysType, Ex: float, Ey: float, phaX: float, phaY: float, startSurface: int, toSurface: int, waveNumber: int, X: float, Y: float, Z: float, L: float, M: float, N: float) -> Tuple[bool, int, int, float, float, float, float, float, float, float, float, float, float, float, float, float]:
        """Enum parameter:
            rayType -> ZOSAPI.Tools.RayTrace.RaysType

        Performs the same calculation as CreateDirectPol, but for one ray at a time.

        Args:
            rayType: Type of the ray.
            Ex: ex.
            Ey: ey.
            phaX: phase x.
            phaY: phase y.
            startSurface: The start surface.
            toSurface: To surface.
            waveNumber: The wave number.
            X: x.
            Y: y.
            Z: z.
            L: l.
            M: m.
            N: n.
            ErrorCode: The error code.
            vignetteCode: The vignette code.
            xo: output x.
            yo: output y.
            zo: output z.
            lo: output l.
            mo: output m.
            no: output n.
            exro: output exr.
            exio: output exi.
            eyro: output eyr.
            eyio: output eyi.
            ezro: output ezr.
            ezio: output ezi.
            intensity: The intensity.
        """
        ...
    def SingleRayDirectUnpol(self, rayType: RaysType, startSurface: int, toSurface: int, waveNumber: int, X: float, Y: float, Z: float, L: float, M: float, N: float) -> Tuple[bool, int, int, float, float, float, float, float, float, float, float, float, float]:
        """Enum parameter:
            rayType -> ZOSAPI.Tools.RayTrace.RaysType

        Performs the same calculation as CreateDirectUnpol, but for one ray at a time.

        Args:
            rayType: Type of the ray.
            startSurface: The start surface.
            toSurface: To surface.
            waveNumber: The wave number.
            X: x.
            Y: y.
            Z: z.
            L: l.
            M: m.
            N: n.
            ErrorCode: The error code.
            vignetteCode: The vignette code.
            xo: xo.
            yo: yo.
            zo: zo.
            lo: lo.
            mo: mo.
            no: no.
            l2o: l2o.
            m2o: m2o.
            n2o: n2o.
            intensity: The intensity.
        """
        ...
    def SingleRayNormPol(self, rayType: RaysType, Ex: float, Ey: float, phaX: float, phaY: float, toSurf: int, waveNumber: int, Hx: float, Hy: float, Px: float, Py: float, exr: float, exi: float, eyr: float, eyi: float, ezr: float, ezi: float) -> Tuple[bool, int, float, float, float, float, float, float, float]:
        """Enum parameter:
            rayType -> ZOSAPI.Tools.RayTrace.RaysType

        Performs the same calculation as CreateNormPol, but for one ray at a time.

        Args:
            rayType: Type of the ray.
            Ex: ex.
            Ey: ey.
            phaX: phase x.
            phaY: phase y.
            toSurf: To surf.
            waveNumber: The wave number.
            Hx: hx.
            Hy: hy.
            Px: px.
            Py: py.
            exr: exr.
            exi: exi.
            eyr: eyr.
            eyi: eyi.
            ezr: ezr.
            ezi: ezi.
            ErrorCode: The error code.
            exro: exro.
            exio: exio.
            eyro: eyro.
            eyio: eyio.
            ezro: ezro.
            ezio: ezio.
            intensity: The intensity.
        """
        ...
    def SingleRayNormPolFull(self, rayType: RaysType, Ex: float, Ey: float, phaX: float, phaY: float, toSurf: int, waveNumber: int, Hx: float, Hy: float, Px: float, Py: float, exr: float, exi: float, eyr: float, eyi: float, ezr: float, ezi: float) -> Tuple[bool, int, float, float, float, float, float, float, float, float, float, float, float, float, float]:
        """Enum parameter:
            rayType -> ZOSAPI.Tools.RayTrace.RaysType

        Performs the same calculation as CreateNormPol, but for one ray at a time.

        Args:
            rayType: Type of the ray.
            Ex: ex.
            Ey: ey.
            phaX: phase x.
            phaY: phase y.
            toSurf: To surf.
            waveNumber: The wave number.
            Hx: hx.
            Hy: hy.
            Px: px.
            Py: py.
            exr: exr.
            exi: exi.
            eyr: eyr.
            eyi: eyi.
            ezr: ezr.
            ezi: ezi.
            ErrorCode: The error code.
            xo: output x.
            yo: output y.
            zo: output z.
            lo: output l.
            mo: output m.
            no: output n.
            exro: output exr.
            exio: output exi.
            eyro: output eyr.
            eyio: output eyi.
            ezro: output ezr.
            ezio: output ezi.
            intensity: The intensity.
        """
        ...
    def SingleRayNormUnpol(self, rayType: RaysType, toSurf: int, waveNumber: int, Hx: float, Hy: float, Px: float, Py: float, calcOPD: bool) -> Tuple[bool, int, int, float, float, float, float, float, float, float, float, float, float, float]:
        """Enum parameter:
            rayType -> ZOSAPI.Tools.RayTrace.RaysType

        Performs the same calculation as CreateNormUnpol, but for one ray at a time.

        Args:
            rayType: Type of the ray.
            toSurf: To surf.
            waveNumber: The wave number.
            Hx: hx.
            Hy: hy.
            Px: px.
            Py: py.
            calcOPD: if set to true the Optical Path Difference will be calculated. Note that this can only be done when tracing rays to the Image surface.
            ErrorCode: The error code.
            vignetteCode: The vignette code.
            xo: xo.
            yo: yo.
            zo: zo.
            lo: lo.
            mo: mo.
            no: no.
            l2o: l2o.
            m2o: m2o.
            n2o: n2o.
            opd: The OPD, if calculated.
            intensity: The intensity.
        """
        ...

class ILightningTrace(ZOSAPI.Tools.ISystemTool):
    """ZOSAPI.Tools.RayTrace.ILightningTrace

    Interfaces and methods for running the LightningTrace tool. This interface can be accessed via the IOpticalSystemTools interface.
    """
    @property
    def RaySampling(self) -> LTRaySampling: ...
    @RaySampling.setter
    def RaySampling(self, value: LTRaySampling) -> None: ...
    @property
    def EdgeSampling(self) -> LTEdgeSasmpling: ...
    @EdgeSampling.setter
    def EdgeSampling(self, value: LTEdgeSasmpling) -> None: ...

class INSCRayTrace(ZOSAPI.Tools.ISystemTool):
    """ZOSAPI.Tools.RayTrace.INSCRayTrace

    Interfaces and methods for running a non-sequential ray trace. This interface can be accessed via the IOpticalSystemTools interface. NOTE - due to architectural limitations, currently only one INSCRayTrace instance can be used at a time, across all IOpticalSystem instances. The first call to OpenNSCRayTrace will succeed, while all further calls will return null until the the single INSCRayTrace instance is closed. It is anticipated that this limiation will be removed in future versions of the API.
    """
    @property
    def AutoUpdate(self) -> bool: ...
    @AutoUpdate.setter
    def AutoUpdate(self, value: bool) -> None: ...
    @property
    def NumberOfCores(self) -> int: ...
    @NumberOfCores.setter
    def NumberOfCores(self, value: int) -> None: ...
    @property
    def UsePolarization(self) -> bool: ...
    @UsePolarization.setter
    def UsePolarization(self, value: bool) -> None: ...
    @property
    def IgnoreErrors(self) -> bool: ...
    @IgnoreErrors.setter
    def IgnoreErrors(self, value: bool) -> None: ...
    @property
    def SplitNSCRays(self) -> bool: ...
    @SplitNSCRays.setter
    def SplitNSCRays(self, value: bool) -> None: ...
    @property
    def ScatterNSCRays(self) -> bool: ...
    @ScatterNSCRays.setter
    def ScatterNSCRays(self, value: bool) -> None: ...
    @property
    def SaveRays(self) -> bool: ...
    @SaveRays.setter
    def SaveRays(self, value: bool) -> None: ...
    @property
    def SaveRaysFile(self) -> str:
        """Gets or sets the save rays filename (only used when SaveRays is true)."""
        ...
    @SaveRaysFile.setter
    def SaveRaysFile(self, value: str) -> None: ...
    @property
    def SavePaths(self) -> bool: ...
    @SavePaths.setter
    def SavePaths(self, value: bool) -> None: ...
    @property
    def SavePathsFile(self) -> str:
        """Gets or sets the save rays filename (only used when SavePaths is true)."""
        ...
    @SavePathsFile.setter
    def SavePathsFile(self, value: str) -> None: ...
    @property
    def ZRDFormat(self) -> ZRDFormatType: ...
    @ZRDFormat.setter
    def ZRDFormat(self, value: ZRDFormatType) -> None: ...
    @property
    def Filter(self) -> str: ...
    @Filter.setter
    def Filter(self, value: str) -> None: ...
    @property
    def DeadRayErrors(self) -> float: ...
    @property
    def DeadRayThreshold(self) -> float: ...
    @property
    def IsHPCEnabled(self) -> bool: ...
    @property
    def HPCEstimatedTimeS(self) -> float: ...
    @property
    def HPCRemainingTimeS(self) -> float: ...
    @property
    def HPCTimeToStartS(self) -> float: ...
    @property
    def HPCQueuePosition(self) -> int: ...
    @property
    def HPCState(self) -> ZOSAPI.Tools.HPCRunState: ...
    @property
    def HPCHasTimeEstimate(self) -> bool: ...
    @property
    def RayMultiplier(self) -> float: ...
    @RayMultiplier.setter
    def RayMultiplier(self, value: float) -> None: ...
    @property
    def HasHPCUnsupportedDetectors(self) -> bool: ...
    def ClearDetectorObject(self, ObjectNumber: int) -> ZOSAPI.Analysis.ErrorType:
        """Clears the detector data on the specified object.

        Args:
            ObjectNumber: object number of the detector to clear. Use 0 for all detectors.
        """
        ...
    def ClearDetectors(self, DetectorNumber: int) -> ZOSAPI.Analysis.ErrorType:
        """Clears the specified detectors.

        Args:
            DetectorNumber: number of the detector to clear. Use 0 for all detectors. Note that detector number 1 is the first object that functions as a detector, not object number 1. To clear a specific object, use ClearDetectorObject.///
        """
        ...
    def EstimateHPCTime(self) -> bool: ...
    def GetTotalRayEnergy(self) -> float: ...
    def ResetRandomSeed(self) -> None:
        """Clear any previously set random seed, so that each new ray trace uses a new random seed value."""
        ...
    def SetPartialRTMode(self, seed: int, group: int) -> None: ...
    def SetRandomSeed(self, seed: int) -> None:
        """Usually the NSC Ray Trace uses a new random seed each time it is run. This function allows the user to explicitly set the random seed that is used, in order to trace a reproducible set of rays.

        Args:
            seed: Any non-zero seed value
        """
        ...

class IRayTraceDirectPolData:
    """ZOSAPI.Tools.RayTrace.IRayTraceDirectPolData"""
    @property
    def NumberOfRays(self) -> int: ...
    @property
    def MaxRays(self) -> int: ...
    @property
    def HasResultData(self) -> bool: ...
    def AddRay(self, waveNumber: int, X: float, Y: float, Z: float, L: float, M: float, N: float) -> bool: ...
    def ClearData(self) -> None: ...
    def ReadNextResult(self) -> Tuple[bool, int, int, int, float, float, float, float, float, float, float]: ...
    def ReadNextResultFull(self) -> Tuple[bool, int, int, int, float, float, float, float, float, float, float, float, float, float, float, float, float]: ...
    def StartReadingResults(self) -> bool: ...

class IRayTraceDirectUnpolData:
    """ZOSAPI.Tools.RayTrace.IRayTraceDirectUnpolData"""
    @property
    def NumberOfRays(self) -> int: ...
    @property
    def MaxRays(self) -> int: ...
    @property
    def HasResultData(self) -> bool: ...
    def AddRay(self, waveNumber: int, X: float, Y: float, Z: float, L: float, M: float, N: float) -> bool: ...
    def ClearData(self) -> None: ...
    def ReadNextResult(self) -> Tuple[bool, int, int, int, float, float, float, float, float, float, float, float, float, float]: ...
    def StartReadingResults(self) -> bool: ...

class IRayTraceNSCData:
    """ZOSAPI.Tools.RayTrace.IRayTraceNSCData"""
    @property
    def NumberOfRays(self) -> int: ...
    @property
    def MaxRays(self) -> int: ...
    @property
    def HasResultData(self) -> bool: ...
    def AddRay(self, waveNumber: int, surf: int, mode: NSCTraceOptions, X: float, Y: float, Z: float, L: float, M: float, N: float, InsideOf: int, exr: float, exi: float, eyr: float, eyi: float, ezr: float, ezi: float) -> bool:
        """Enum parameter:
            mode -> ZOSAPI.Tools.RayTrace.NSCTraceOptions

        Note - as the input intensity is always assumed to be equal to 1.0, the e-field magnitude (if used) should also be 1.0.

        Args:
            waveNumber
            surf
            mode
            X
            Y
            Z
            L
            M
            N
            InsideOf
            exr
            exi
            eyr
            eyi
            ezr
            ezi
        """
        ...
    def ClearData(self) -> None: ...
    def ReadNextResult(self) -> Tuple[bool, int, int, int, int]: ...
    def ReadNextSegment(self) -> Tuple[bool, int, int, int, int, float, float, float, float, float, float, float, float, float, float, float, float, float, float]: ...
    def StartReadingResults(self) -> bool: ...

class IRayTraceNSCSourceData:
    """ZOSAPI.Tools.RayTrace.IRayTraceNSCSourceData"""
    @property
    def UseSingleSource(self) -> bool: ...
    @UseSingleSource.setter
    def UseSingleSource(self, value: bool) -> None: ...
    @property
    def SurfaceNumber(self) -> int: ...
    @SurfaceNumber.setter
    def SurfaceNumber(self, value: int) -> None: ...
    @property
    def ObjectNumber(self) -> int: ...
    @ObjectNumber.setter
    def ObjectNumber(self, value: int) -> None: ...
    @property
    def MaxRays(self) -> int: ...
    @MaxRays.setter
    def MaxRays(self, value: int) -> None: ...
    @property
    def TraceOptions(self) -> NSCTraceOptions: ...
    @TraceOptions.setter
    def TraceOptions(self, value: NSCTraceOptions) -> None: ...
    @property
    def Wavelength(self) -> int: ...
    @Wavelength.setter
    def Wavelength(self, value: int) -> None: ...
    @property
    def HasResultData(self) -> bool: ...
    def ReadNextResult(self) -> Tuple[bool, int, int, int, int]: ...
    def ReadNextSegment(self) -> Tuple[bool, int, int, int, int, float, float, float, float, float, float, float, float, float, float, float, float, float, float]: ...
    def StartReadingResults(self) -> bool: ...
    def UseAnyWavelength(self) -> None: ...
    def UsePrimaryWavelength(self) -> None: ...

class IRayTraceNormPolData:
    """ZOSAPI.Tools.RayTrace.IRayTraceNormPolData"""
    @property
    def NumberOfRays(self) -> int: ...
    @property
    def MaxRays(self) -> int: ...
    @property
    def HasResultData(self) -> bool: ...
    def AddRay(self, waveNumber: int, Hx: float, Hy: float, Px: float, Py: float, exr: float, exi: float, eyr: float, eyi: float, ezr: float, ezi: float) -> bool: ...
    def ClearData(self) -> None: ...
    def ReadNextResult(self) -> Tuple[bool, int, int, float, float, float, float, float, float, float]: ...
    def ReadNextResultFull(self) -> Tuple[bool, int, int, float, float, float, float, float, float, float, float, float, float, float, float, float]: ...
    def StartReadingResults(self) -> bool: ...

class IRayTraceNormUnpolData:
    """ZOSAPI.Tools.RayTrace.IRayTraceNormUnpolData"""
    @property
    def NumberOfRays(self) -> int: ...
    @property
    def MaxRays(self) -> int: ...
    @property
    def HasResultData(self) -> bool: ...
    def AddRay(self, waveNumber: int, Hx: float, Hy: float, Px: float, Py: float, calcOPD: OPDMode) -> bool:
        """Enum parameter:
            calcOPD -> ZOSAPI.Tools.RayTrace.OPDMode
        """
        ...
    def ClearData(self) -> None: ...
    def ReadNextResult(self) -> Tuple[bool, int, int, int, float, float, float, float, float, float, float, float, float, float, float]: ...
    def StartReadingResults(self) -> bool: ...

class IZRDReader(ZOSAPI.Tools.ISystemTool):
    """ZOSAPI.Tools.RayTrace.IZRDReader"""
    @property
    def ZRDFile(self) -> str: ...
    @ZRDFile.setter
    def ZRDFile(self, value: str) -> None: ...
    @property
    def Filter(self) -> str: ...
    @Filter.setter
    def Filter(self, value: str) -> None: ...
    def GetResults(self) -> IZRDReaderResults: ...

class IZRDReaderResults:
    """ZOSAPI.Tools.RayTrace.IZRDReaderResults"""
    @property
    def IsValid(self) -> bool: ...
    def ReadNextResult(self) -> Tuple[bool, int, int, float, int]: ...
    def ReadNextSegment(self) -> Tuple[bool, int, int, int, int, int, RayStatus, float, float, float, float, float, float, float, float, float, float, float, float, float, float]: ...
    def ReadNextSegmentFull(self) -> Tuple[bool, int, int, int, int, int, RayStatus, float, float, float, float, float, float, float, float, float, float, float, float, float, float, int, int, float, float, float, float, float, float, float]: ...

class LTEdgeSasmpling(IntEnum):
    """ZOSAPI.Tools.RayTrace.LTEdgeSasmpling"""
    S_1X_Low = 0
    S_4X = 1
    S_16X = 2
    S_64X = 3
    S_256X = 4

class LTRaySampling(IntEnum):
    """ZOSAPI.Tools.RayTrace.LTRaySampling"""
    S_1X_Low = 0
    S_4X = 1
    S_16X = 2
    S_64X = 3
    S_256X = 4
    S_1024X = 5

class NSCTraceOptions(IntEnum):
    """ZOSAPI.Tools.RayTrace.NSCTraceOptions"""
    None_ = 0
    UsePolarization = 1
    UseSplitting = 2
    UseScattering = 4

class OPDMode(IntEnum):
    """ZOSAPI.Tools.RayTrace.OPDMode"""
    None_ = 0
    Current = 1
    CurrentAndChief = 2

class RayPathDataEntry:
    """ZOSAPI.Tools.RayTrace.RayPathDataEntry"""
    ...

class RayPathDataHolder:
    """ZOSAPI.Tools.RayTrace.RayPathDataHolder"""
    def __init__(self) -> None: ...
    def __init__(self, offset: int, size: int) -> None: ...
    def __init__(self, info: Any, context: Any) -> None: ...
    def GetData(self, mmf: Any) -> Tuple[bool, List[RayPathDataEntry]]: ...
    def GetObjectData(self, info: Any, context: Any) -> None: ...
    @staticmethod
    def SetData(mmf: Any, data: List[RayPathDataEntry], index: int) -> RayPathDataHolder: ...

class RayStatus(IntFlag):
    """ZOSAPI.Tools.RayTrace.RayStatus"""
    Parent = 0
    Terminated = 1
    Reflected = 2
    Transmitted = 4
    Scattered = 8
    Diffracted = 16
    GhostedFrom = 32
    DiffractedFrom = 64
    ScatteredFrom = 128
    RayError = 256
    BulkScattered = 512
    WaveShifted = 1024
    OrdinaryRay = 65536
    ExtraordinaryRay = 131072
    WaveShiftPL = 262144

class RaysType(IntEnum):
    """ZOSAPI.Tools.RayTrace.RaysType"""
    Real = 0
    Paraxial = 1

class ZRDFormatType(IntEnum):
    """ZOSAPI.Tools.RayTrace.ZRDFormatType"""
    UncompressedFullData = 0
    CompressedBasicData = 1
    CompressedFullData = 2
