# Auto-generated by zosapi-stubgen — do not edit by hand.
# Re-run `zosapi-stubgen` to refresh after an OpticStudio upgrade.
from __future__ import annotations
from typing import (
    Any, Dict, Generic, Iterable, Iterator, List,
    Optional, overload, Sequence, Set, Tuple, TypeVar, Union,
)
from enum import IntEnum, IntFlag
from datetime import datetime, timedelta

import ZOSAPI.Analysis.Data
import ZOSAPI.Analysis.Settings
import ZOSAPI.Common

from . import Data as Data
from . import PhysicalOptics as PhysicalOptics
from . import RayTracing as RayTracing
from . import Settings as Settings
from . import Tolerancing as Tolerancing

class AnalysisIDM(IntEnum):
    """ZOSAPI.Analysis.AnalysisIDM

    All available analysis types. See the I_Analyses interface for more information.
    """
    XXXTemplateXXX = -1
    RayFan = 0
    """Ray Fan"""
    OpticalPathFan = 1
    """OPD Fan"""
    PupilAberrationFan = 2
    """Pupil Aberration Fan"""
    FieldCurvatureAndDistortion = 3
    """Field Curv/Dist"""
    FocalShiftDiagram = 4
    """Focal Shift"""
    GridDistortion = 5
    """Grid Distortion"""
    LateralColor = 6
    """Lateral Color"""
    LongitudinalAberration = 7
    """Longitudinal Aberration"""
    RayTrace = 8
    """Single Ray Trace"""
    SeidelCoefficients = 9
    """Seidel Coefficients"""
    SeidelDiagram = 10
    """Seidel Diagram"""
    ZernikeAnnularCoefficients = 11
    """Zernike Annular Coefficients"""
    ZernikeCoefficientsVsField = 12
    """Zernike Coefficients vs. Field"""
    ZernikeFringeCoefficients = 13
    """Zernike Fringe Coefficients"""
    ZernikeStandardCoefficients = 14
    """Zernike Standard Coefficients"""
    FftMtf = 15
    """FFT MTF"""
    FftThroughFocusMtf = 16
    """FFT Through Focus MTF"""
    GeometricThroughFocusMtf = 17
    """Through Focus Geometric MTF"""
    GeometricMtf = 18
    """Geometric MTF"""
    FftMtfMap = 19
    """FFT MTF Map"""
    GeometricMtfMap = 20
    """Geometric MTF Map"""
    FftSurfaceMtf = 21
    """FFT Surface MTF"""
    FftMtfvsField = 22
    """FFT MTF vs. Field"""
    GeometricMtfvsField = 23
    """Geometric MTF vs. Field"""
    HuygensMtfvsField = 24
    """Huygens MTF vs. Field"""
    HuygensMtf = 25
    """Huygens MTF"""
    HuygensSurfaceMtf = 26
    """Huygens Surface MTF"""
    HuygensThroughFocusMtf = 27
    """Huygens Through Focus MTF"""
    FftPsf = 28
    """FFT PSF"""
    FftPsfCrossSection = 29
    """FFT PSF Cross Section"""
    FftPsfLineEdgeSpread = 30
    """FFT Line/Edge Spread"""
    HuygensPsfCrossSection = 31
    """Huygens PSF Cross Section"""
    HuygensPsf = 32
    """Huygens PSF"""
    DiffractionEncircledEnergy = 33
    """Diffraction Encircled Energy"""
    GeometricEncircledEnergy = 34
    """Geometric Encircled Energy"""
    GeometricLineEdgeSpread = 35
    """Line/Edge Spread"""
    ExtendedSourceEncircledEnergy = 36
    """Extended Source Encircled Energy"""
    SurfaceCurvatureCross = 37
    """Surface Curvature Cross Section"""
    SurfacePhaseCross = 38
    """Surface Phase Cross Section"""
    SurfaceSagCross = 39
    """Surface Sag Cross Section"""
    SurfaceCurvature = 40
    """Surface Curvature"""
    SurfacePhase = 41
    """Surface Phase"""
    SurfaceSag = 42
    """Surface Sag"""
    StandardSpot = 43
    """Spot Diagram"""
    ThroughFocusSpot = 44
    """Through Focus Spot Diagram"""
    FullFieldSpot = 45
    """Full Field Spot Diagram"""
    MatrixSpot = 46
    """Matrix Spot Diagram"""
    ConfigurationMatrixSpot = 47
    """Configuration Matrix Spot Diagram"""
    RMSField = 48
    """RMS vs. Field"""
    RMSFieldMap = 49
    """RMS Field Map"""
    RMSLambdaDiagram = 50
    """RMS vs. Wavelength"""
    RMSFocus = 51
    """RMS vs. Focus"""
    Foucault = 52
    """Foucault Analysis"""
    Interferogram = 53
    """Interferogram"""
    WavefrontMap = 54
    """Wavefront Map"""
    DetectorViewer = 55
    """Detector Viewer"""
    Draw2D = 56
    """Layout"""
    Draw3D = 57
    """3D Layout"""
    ImageSimulation = 58
    """Image Simulation"""
    GeometricImageAnalysis = 59
    """Geometric Image Analysis"""
    IMABIMFileViewer = 60
    """IMA/BIM File Viewer"""
    GeometricBitmapImageAnalysis = 61
    """Geometric Bitmap Image Analysis"""
    BitmapFileViewer = 62
    """Bitmap File Viewer"""
    LightSourceAnalysis = 63
    """Light Source Analysis"""
    PartiallyCoherentImageAnalysis = 64
    """Partially Coherent Image Analysis"""
    ExtendedDiffractionImageAnalysis = 65
    """Extended Diffraction Image Analysis"""
    BiocularFieldOfViewAnalysis = 66
    """Biocular Field Of View Analysis"""
    BiocularDipvergenceConvergence = 67
    """Biocular Dipvergence/Convergence"""
    RelativeIllumination = 68
    """Relative Illumination"""
    VignettingDiagramSettings = 69
    """Vignetting Diagram"""
    FootprintSettings = 70
    """Footprint Diagram"""
    YYbarDiagram = 71
    """Y-Ybar Diagram"""
    PowerFieldMapSettings = 72
    """Power Field Map"""
    PowerPupilMapSettings = 73
    """Power Pupil Map"""
    IncidentAnglevsImageHeight = 74
    """Incident Angle vs. Image Height"""
    FiberCouplingSettings = 75
    """Fiber Coupling"""
    YNIContributions = 76
    """YNI Contributions"""
    SagTable = 77
    """Sag Table"""
    CardinalPoints = 78
    """Cardinal Point Data"""
    DispersionDiagram = 79
    """Dispersion Diagram"""
    GlassMap = 80
    """Glass Map"""
    AthermalGlassMap = 81
    """Athermal Glass Map"""
    InternalTransmissionvsWavelength = 82
    """Internal Transmission"""
    DispersionvsWavelength = 83
    """Dispersion vs. Wavelength"""
    GrinProfile = 84
    """Grin Profile"""
    GradiumProfile = 85
    """Gradium Profile"""
    UniversalPlot1D = 86
    """Universal Plot 1D"""
    UniversalPlot2D = 87
    """Universal Plot 2D"""
    PolarizationRayTrace = 88
    """Polarization Ray Trace"""
    PolarizationPupilMap = 89
    """Polarization Pupil Map"""
    Transmission = 90
    """Transmission"""
    PhaseAberration = 91
    """Phase Aberration"""
    TransmissionFan = 92
    """Transmission Fan"""
    ParaxialGaussianBeam = 93
    """Paraxial Gaussian Beam Data"""
    SkewGaussianBeam = 94
    """Skew Gaussian Beam Data"""
    PhysicalOpticsPropagation = 95
    """Physical Optics Propagation"""
    BeamFileViewer = 96
    """Beam File Viewer"""
    ReflectionvsAngle = 97
    """Reflection vs. Angle"""
    TransmissionvsAngle = 98
    """Transmission vs. Angle"""
    AbsorptionvsAngle = 99
    """Absorption vs. Angle"""
    DiattenuationvsAngle = 100
    """Diattenuation vs. Angle"""
    PhasevsAngle = 101
    """Phase vs. Angle"""
    RetardancevsAngle = 102
    """Retardance vs. Angle"""
    ReflectionvsWavelength = 103
    """Reflection vs. Wavelength"""
    TransmissionvsWavelength = 104
    """Transmission vs. Wavelength"""
    AbsorptionvsWavelength = 105
    """Absorption vs. Wavelength"""
    DiattenuationvsWavelength = 106
    """Diattenuation vs. Wavelength"""
    PhasevsWavelength = 107
    """Phase vs. Wavelength"""
    RetardancevsWavelength = 108
    """Retardance vs. Wavelength"""
    DirectivityPlot = 109
    """Source Directivity Viewer"""
    SourcePolarViewer = 110
    """Source Polar Viewer"""
    PhotoluminscenceViewer = 111
    """Phosphors and Fluorescence Spectrum Plot"""
    SourceSpectrumViewer = 112
    """Source Spectrum Viewer"""
    RadiantSourceModelViewerSettings = 113
    """Radiant Source Model™ Viewer"""
    SurfaceDataSettings = 114
    """Surface Data"""
    PrescriptionDataSettings = 115
    """Prescription Data"""
    FileComparatorSettings = 116
    """File Comparator"""
    PartViewer = 117
    """Part Viewer"""
    ReverseRadianceAnalysis = 118
    """ReverseRadiance™ Analysis"""
    PathAnalysis = 119
    """Path Analysis"""
    FluxvsWavelength = 120
    """Flux vs. Wavelength"""
    RoadwayLighting = 121
    """Roadway Lighting Analysis"""
    SourceIlluminationMap = 122
    """Source Illumination Map"""
    ScatterFunctionViewer = 123
    """Scatter Function Viewer"""
    ScatterPolarPlotSettings = 124
    """Scatter Polar Plot"""
    ZemaxElementDrawing = 125
    """Zemax Element Drawing"""
    ShadedModel = 126
    """Shaded Model"""
    NSCShadedModel = 127
    """NSC Shaded Model"""
    NSC3DLayout = 128
    """NSC 3D Layout"""
    NSCObjectViewer = 129
    """NSC Object Viewer"""
    RayDatabaseViewer = 130
    """Ray Database Viewer"""
    ISOElementDrawing = 131
    """ISO Element Drawing"""
    SystemData = 132
    """System Data"""
    TestPlateList = 133
    """Test Plate List"""
    SourceColorChart1931 = 134
    """CIE 1931 Color Chart"""
    SourceColorChart1976 = 135
    """CIE 1976 Color Chart"""
    PrescriptionGraphic = 136
    """System Summary Graphic"""
    CriticalRayTracer = 137
    """Critical Ray Tracer"""
    ContrastLoss = 138
    CoatingListing = 139
    FullFieldAberration = 140
    SurfaceSlope = 141
    """Surface Slope"""
    SurfaceSlopeCross = 142
    """Surface Slope Cross Section"""
    QuickYield = 143
    """Quick Yield"""
    SystemCheck = 144
    ToleranceYield = 145
    """Tolerancing Yield"""
    ToleranceHistogram = 146
    """Tolerancing Histogram"""
    DiffEfficiency2D = 147
    """Diffraction Efficiency 2D"""
    DiffEfficiencyAngular = 148
    """Diffraction Efficiency Angular"""
    DiffEfficiencyChromatic = 149
    """Diffraction Efficiency Chromatic"""

class Beam(IntEnum):
    """ZOSAPI.Analysis.Beam"""
    Reference = 0
    Configuration_1 = 1
    Configuration_2 = 2
    Configuration_3 = 3
    Configuration_4 = 4
    Configuration_5 = 5
    Configuration_6 = 6
    Configuration_7 = 7
    Configuration_8 = 8
    Configuration_9 = 9
    Configuration_10 = 10
    Configuration_11 = 11
    Configuration_12 = 12
    Configuration_13 = 13
    Configuration_14 = 14
    Configuration_15 = 15
    Configuration_16 = 16
    Configuration_17 = 17
    Configuration_18 = 18
    Configuration_19 = 19
    Configuration_20 = 20

class BestFitSphereOptions(IntEnum):
    """ZOSAPI.Analysis.BestFitSphereOptions"""
    MinimumVolume = 0
    MinimumRMS = 1
    MinimumRMSWithOffset = 2

class ColorPaletteType(IntEnum):
    """ZOSAPI.Analysis.ColorPaletteType"""
    GreyScale = 0
    FalseColor = 1
    FalseColorOriginal = 2
    Viridis = 3
    Magma = 4

class DetectorViewerShowAsTypes(IntEnum):
    """ZOSAPI.Analysis.DetectorViewerShowAsTypes"""
    FullListing = 0
    AzimuthCrossSection = 1
    Text_CrossSection_Row = 1
    Text_CrossSection_Column = 2
    FluxVsWaveLength = 3
    GreyScale = 0
    GreyScale_Inverted = 1
    FalseColor = 2
    FalseColor_Inverted = 3
    TrueColor = 4
    Color_CrossSection_Row = 5
    Color_CrossSection_Column = 6
    Color_FluxVsWavelength = 7
    CrossSection = 5
    Directivity_Full = 6
    Directivity_Half = 7
    CrossSection_Row = 4
    CrossSection_Column = 5
    GeometricMtf = 6

class DetectorViewerShowDataTypes(IntEnum):
    """ZOSAPI.Analysis.DetectorViewerShowDataTypes"""
    IncidentFlux = 0
    AbsorbedFlux = 1
    AbsorbedFluxVolume = 2
    PositionSpace = 0
    AngleSpace = 1
    Polar_AngleSpace = 0
    IncoherentIrradiance = 0
    CoherentIrradiance = 1
    CoherentPhase = 2
    RadiantIntensity = 3
    RadiancePositionSpace = 4
    RadianceAngleSpace = 5
    IncoherentIlluminance = 0
    CoherentIlluminance = 1
    LuminousIntensity = 3
    LuminancePositionSpace = 4
    LuminanceAngleSpace = 5
    IncoherentFluence = 0
    CoherentFluence = 1

class ErrorType(IntEnum):
    """ZOSAPI.Analysis.ErrorType"""
    Success = 0
    InvalidParameter = 1
    InvalidSettings = 2
    Failed = 3
    AnalysisUnavailableForProgramMode = 4
    NotYetImplemented = 5

class GiaShowAsTypes(IntEnum):
    """ZOSAPI.Analysis.GiaShowAsTypes"""
    Surface = 0
    Contour = 1
    GreyScale = 2
    InverseGreyScale = 3
    FalseColor = 4
    InverseFalseColor = 5
    SpotDiagram = 6
    CrossX = 7
    CrossY = 8

class GridPlotType(IntEnum):
    """ZOSAPI.Analysis.GridPlotType"""
    Surface = 0
    Contour = 1
    GrayScale = 2
    InverseGrayScale = 3
    FalseColor = 4
    InverseFalseColor = 5

class HuygensShowAsTypes(IntEnum):
    """ZOSAPI.Analysis.HuygensShowAsTypes"""
    Surface = 0
    Contour = 1
    GreyScale = 2
    InverseGreyScale = 3
    FalseColor = 4
    InverseFalseColor = 5
    TrueColor = 6

class HuygensSurfaceMftShowAsTypes(IntEnum):
    """ZOSAPI.Analysis.HuygensSurfaceMftShowAsTypes"""
    GreyScale = 0
    InverseGreyScale = 1
    FalseColor = 2
    InverseFalseColor = 3

class IA_:
    """ZOSAPI.Analysis.IA_

    Base interface for all analysis windows. This interface can be accessed via the I_Analyses interface.
    """
    @property
    def Title(self) -> str: ...
    @property
    def GetAnalysisName(self) -> str: ...
    @property
    def AnalysisType(self) -> AnalysisIDM: ...
    @property
    def StatusMessages(self) -> IMessages: ...
    @property
    def HasAnalysisSpecificSettings(self) -> bool:
        """Gets a value indicating whether this instance has a fully-implemented settings interface available. If false, the analysis settings can only be changed via ModifySettings."""
        ...
    def Apply(self) -> IMessage:
        """Use the current settings values to re-run the analysis."""
        ...
    def ApplyAndWaitForCompletion(self) -> IMessage:
        """Re-runs the analysis with the current settings and waits for it to finish calculating."""
        ...
    def Close(self) -> None:
        """Closes this analysis; note that it will be removed from the system permanently."""
        ...
    def GetResults(self) -> ZOSAPI.Analysis.Data.IAR_:
        """Gets the result data (if available) for the current analysis."""
        ...
    def GetSettings(self) -> ZOSAPI.Analysis.Settings.IAS_:
        """Gets the settings for the current analysis."""
        ...
    def IsRunning(self) -> bool:
        """Determines whether this analysis is currently updating."""
        ...
    def Release(self) -> None:
        """Disconnect this object from the interface, freeing up any memory in use. Note that unlike Close, this method does not remove the analysis from the current system."""
        ...
    def Terminate(self) -> bool:
        """Attempt to cancel the currently running the analysis."""
        ...
    def ToFile(self, Filename: str, showSettings: bool = ..., verify: bool = ...) -> None: ...
    def WaitForCompletion(self) -> None:
        """Waits for the current analysis to finish running (if applicable)."""
        ...

class IColorTranslator:
    """ZOSAPI.Analysis.IColorTranslator"""
    @property
    def Palette(self) -> ColorPaletteType: ...
    @property
    def IsInversePalette(self) -> bool: ...
    @property
    def IsAutoScaled(self) -> bool: ...
    @property
    def NumberOfShades(self) -> int: ...
    @property
    def MinValue(self) -> float: ...
    @property
    def MaxValue(self) -> float: ...
    @property
    def IsLog(self) -> bool: ...
    @property
    def LogBase(self) -> float: ...
    @property
    def CanConvertSingleValue(self) -> bool: ...
    def GetRGB(self, fullSize: int, data: List[float]) -> Tuple[List[int], List[int], List[int]]: ...
    def GetRGB2DFloatSafe(self, vals: List[float]) -> List[float]: ...
    def GetRGB2DSafe(self, vals: List[float]) -> List[int]: ...
    def GetRGBFloat(self, fullSize: int, data: List[float]) -> Tuple[List[float], List[float], List[float]]: ...
    def GetRGBFloatSafe(self, vals: List[float]) -> List[float]: ...
    def GetRGBSafe(self, vals: List[float]) -> List[int]: ...
    def GetSingleRGB(self, x: float) -> Tuple[bool, int, int, int]: ...
    def GetSingleRGBFloat(self, x: float) -> Tuple[bool, float, float, float]: ...

class IMessage:
    """ZOSAPI.Analysis.IMessage"""
    @property
    def ErrorCode(self) -> ErrorType: ...
    @property
    def Text(self) -> str: ...

class IMessages:
    """ZOSAPI.Analysis.IMessages"""
    def AllToString(self) -> str: ...
    @overload
    def WriteLine(self, s: str, userV: int, settingsV: int) -> None: ...
    @overload
    def WriteLine(self, s: str, userV: bool, settingsV: bool) -> None: ...
    @overload
    def WriteLine(self, s: str, userV: float, settingsV: float) -> None: ...
    @overload
    def WriteLine(self, s: str, userV: str, settingsV: str) -> None: ...

class IUser2DLineData:
    """ZOSAPI.Analysis.IUser2DLineData

    Properties and methods for configuring a 2D line User Analysis plot. This interface can be accessed via the IUserAnalysisData interface.
    """
    @property
    def PlotDescription(self) -> str: ...
    @property
    def XLabel(self) -> str: ...
    @XLabel.setter
    def XLabel(self, value: str) -> None: ...
    @property
    def YLabel(self) -> str: ...
    @YLabel.setter
    def YLabel(self, value: str) -> None: ...
    @property
    def NumberOfXValues(self) -> int: ...
    @property
    def NumberOfYValues(self) -> int: ...
    @property
    def NumberOfSeries(self) -> int: ...
    @property
    def XAxisMin(self) -> float: ...
    @XAxisMin.setter
    def XAxisMin(self, value: float) -> None: ...
    @property
    def XAxisMinAuto(self) -> bool: ...
    @XAxisMinAuto.setter
    def XAxisMinAuto(self, value: bool) -> None: ...
    @property
    def XAxisMax(self) -> float: ...
    @XAxisMax.setter
    def XAxisMax(self, value: float) -> None: ...
    @property
    def XAxisMaxAuto(self) -> bool: ...
    @XAxisMaxAuto.setter
    def XAxisMaxAuto(self, value: bool) -> None: ...
    @property
    def XAxisLog(self) -> bool: ...
    @XAxisLog.setter
    def XAxisLog(self, value: bool) -> None: ...
    @property
    def XAxisReversed(self) -> bool: ...
    @XAxisReversed.setter
    def XAxisReversed(self, value: bool) -> None: ...
    @property
    def XAxisSymmetric(self) -> bool: ...
    @XAxisSymmetric.setter
    def XAxisSymmetric(self, value: bool) -> None: ...
    @property
    def YAxisMin(self) -> float: ...
    @YAxisMin.setter
    def YAxisMin(self, value: float) -> None: ...
    @property
    def YAxisMinAuto(self) -> bool: ...
    @YAxisMinAuto.setter
    def YAxisMinAuto(self, value: bool) -> None: ...
    @property
    def YAxisMax(self) -> float: ...
    @YAxisMax.setter
    def YAxisMax(self, value: float) -> None: ...
    @property
    def YAxisMaxAuto(self) -> bool: ...
    @YAxisMaxAuto.setter
    def YAxisMaxAuto(self, value: bool) -> None: ...
    @property
    def YAxisLog(self) -> bool: ...
    @YAxisLog.setter
    def YAxisLog(self, value: bool) -> None: ...
    @property
    def YAxisReversed(self) -> bool: ...
    @YAxisReversed.setter
    def YAxisReversed(self, value: bool) -> None: ...
    @property
    def YAxisSymmetric(self) -> bool: ...
    @YAxisSymmetric.setter
    def YAxisSymmetric(self, value: bool) -> None: ...
    def AddSeries(self, seriesName: str, seriesColor: ZOSAPI.Common.ZemaxColor, numberOfYValues: int, yValues: List[float]) -> None:
        """Enum parameter:
            seriesColor -> ZOSAPI.Common.ZemaxColor
        """
        ...
    def AddSeriesSafe(self, seriesName: str, seriesColor: ZOSAPI.Common.ZemaxColor, yValues: List[float]) -> None:
        """Enum parameter:
            seriesColor -> ZOSAPI.Common.ZemaxColor
        """
        ...

class IUserAnalysisData:
    """ZOSAPI.Analysis.IUserAnalysisData

    Properties and methods used to generate a User Analysis. This interface can be accessed via the IZOSAPI_Application interface. Note that this interface is only available when creating a User Analysis plugin application.
    """
    @property
    def AnalysisNumber(self) -> int:
        """Gets the position of this user analysis in the primary IOpticalSystem. Note that this number may change when other analyses are opened or closed."""
        ...
    @property
    def PlotType(self) -> UserAnalysisDataType:
        """Gets the type of this plot window."""
        ...
    @property
    def WindowTitle(self) -> str: ...
    @WindowTitle.setter
    def WindowTitle(self, value: str) -> None: ...
    @property
    def FeatureDescription(self) -> str: ...
    @FeatureDescription.setter
    def FeatureDescription(self, value: str) -> None: ...
    @property
    def HeaderData(self) -> List[str]: ...
    @HeaderData.setter
    def HeaderData(self, value: List[str]) -> None: ...
    @property
    def ShowLegend(self) -> bool: ...
    @ShowLegend.setter
    def ShowLegend(self, value: bool) -> None: ...
    @property
    def UserSettings(self) -> ZOSAPI.Common.ISettingsData: ...
    @property
    def RunAnalysisOnSettingsClosed(self) -> bool: ...
    @RunAnalysisOnSettingsClosed.setter
    def RunAnalysisOnSettingsClosed(self, value: bool) -> None: ...
    def Make2DLinePlot(self, PlotDescription: str, numValues: int, xValues: List[float]) -> IUser2DLineData:
        """Gets an interface used to configure a 2D line plot.

        Args:
            PlotDescription: The plot description.
            numValues: The number of x-values. Note that multiple series are supported, but they all must share the same x data.
            xValues: The x values.
        """
        ...
    def Make2DLinePlotSafe(self, PlotDescription: str, xValues: List[float]) -> IUser2DLineData:
        """Gets an interface used to configure a 2D line plot.

        Args:
            PlotDescription: The plot description.
            xValues: The x values.
        """
        ...
    def MakeGridPlot(self, PlotDescription: str) -> IUserGridData:
        """Gets an interface used to configure a 2D grid plot.

        Args:
            PlotDescription: The plot description.
        """
        ...
    def MakeGridRGBPlot(self, PlotDescription: str) -> IUserGridRGBData:
        """Gets an interface used to configure a 2D RGB grid plot.

        Args:
            PlotDescription: The plot description.
        """
        ...
    def MakeText(self) -> IUserTextData:
        """Gets an interface used to configure a simple text window."""
        ...

class IUserGridData:
    """ZOSAPI.Analysis.IUserGridData

    Properties and methods for configuring a 2D grid User Analysis plot. This interface can be accessed via the IUserAnalysisData interface.
    """
    @property
    def PlotDescription(self) -> str: ...
    @property
    def XLabel(self) -> str: ...
    @XLabel.setter
    def XLabel(self, value: str) -> None: ...
    @property
    def YLabel(self) -> str: ...
    @YLabel.setter
    def YLabel(self, value: str) -> None: ...
    @property
    def ValueLabel(self) -> str: ...
    @ValueLabel.setter
    def ValueLabel(self, value: str) -> None: ...
    @property
    def ShowAsType(self) -> GridPlotType: ...
    @ShowAsType.setter
    def ShowAsType(self, value: GridPlotType) -> None: ...
    @property
    def NumberOfXDataValues(self) -> int: ...
    @property
    def XDataMin(self) -> float: ...
    @property
    def XDataMax(self) -> float: ...
    @property
    def DataDX(self) -> float: ...
    @property
    def NumberOfYDataValues(self) -> int: ...
    @property
    def YDataMin(self) -> float: ...
    @property
    def YDataMax(self) -> float: ...
    @property
    def DataDY(self) -> float: ...
    @property
    def XAxisMin(self) -> float: ...
    @XAxisMin.setter
    def XAxisMin(self, value: float) -> None: ...
    @property
    def XAxisMinAuto(self) -> bool: ...
    @XAxisMinAuto.setter
    def XAxisMinAuto(self, value: bool) -> None: ...
    @property
    def XAxisMax(self) -> float: ...
    @XAxisMax.setter
    def XAxisMax(self, value: float) -> None: ...
    @property
    def XAxisMaxAuto(self) -> bool: ...
    @XAxisMaxAuto.setter
    def XAxisMaxAuto(self, value: bool) -> None: ...
    @property
    def XAxisSymmetric(self) -> bool: ...
    @XAxisSymmetric.setter
    def XAxisSymmetric(self, value: bool) -> None: ...
    @property
    def YAxisMin(self) -> float: ...
    @YAxisMin.setter
    def YAxisMin(self, value: float) -> None: ...
    @property
    def YAxisMinAuto(self) -> bool: ...
    @YAxisMinAuto.setter
    def YAxisMinAuto(self, value: bool) -> None: ...
    @property
    def YAxisMax(self) -> float: ...
    @YAxisMax.setter
    def YAxisMax(self, value: float) -> None: ...
    @property
    def YAxisMaxAuto(self) -> bool: ...
    @YAxisMaxAuto.setter
    def YAxisMaxAuto(self, value: bool) -> None: ...
    @property
    def YAxisSymmetric(self) -> bool: ...
    @YAxisSymmetric.setter
    def YAxisSymmetric(self, value: bool) -> None: ...
    @property
    def ZAxisMin(self) -> float: ...
    @ZAxisMin.setter
    def ZAxisMin(self, value: float) -> None: ...
    @property
    def ZAxisMinAuto(self) -> bool: ...
    @ZAxisMinAuto.setter
    def ZAxisMinAuto(self, value: bool) -> None: ...
    @property
    def ZAxisMax(self) -> float: ...
    @ZAxisMax.setter
    def ZAxisMax(self, value: float) -> None: ...
    @property
    def ZAxisMaxAuto(self) -> bool: ...
    @ZAxisMaxAuto.setter
    def ZAxisMaxAuto(self, value: bool) -> None: ...
    @property
    def ZAxisLog(self) -> bool: ...
    @ZAxisLog.setter
    def ZAxisLog(self, value: bool) -> None: ...
    @property
    def LogColorMap(self) -> bool: ...
    @LogColorMap.setter
    def LogColorMap(self, value: bool) -> None: ...
    @property
    def InterpolateLowResolutionContours(self) -> bool: ...
    @InterpolateLowResolutionContours.setter
    def InterpolateLowResolutionContours(self, value: bool) -> None: ...
    @property
    def XYAspectRatio(self) -> float: ...
    @XYAspectRatio.setter
    def XYAspectRatio(self, value: float) -> None: ...
    def SetData(self, totalSize: int, numXValues: int, numYValues: int, Data: List[float]) -> None: ...
    def SetDataSafe(self, Data: List[float]) -> None: ...
    def SetXDataDimensions(self, xDataMin: float, xDataMax: float) -> None: ...
    def SetYDataDimensions(self, yDataMin: float, yDataMax: float) -> None: ...

class IUserGridRGBData:
    """ZOSAPI.Analysis.IUserGridRGBData

    Properties and methods for configuring a 2D rgb grid User Analysis plot. This interface can be accessed via the IUserAnalysisData interface.
    """
    @property
    def PlotDescription(self) -> str: ...
    @property
    def XLabel(self) -> str: ...
    @XLabel.setter
    def XLabel(self, value: str) -> None: ...
    @property
    def YLabel(self) -> str: ...
    @YLabel.setter
    def YLabel(self, value: str) -> None: ...
    @property
    def ValueLabel(self) -> str: ...
    @ValueLabel.setter
    def ValueLabel(self, value: str) -> None: ...
    @property
    def NumberOfXDataValues(self) -> int: ...
    @property
    def XDataMin(self) -> float: ...
    @property
    def XDataMax(self) -> float: ...
    @property
    def DataDX(self) -> float: ...
    @property
    def NumberOfYDataValues(self) -> int: ...
    @property
    def YDataMin(self) -> float: ...
    @property
    def YDataMax(self) -> float: ...
    @property
    def DataDY(self) -> float: ...
    @property
    def XAxisMin(self) -> float: ...
    @XAxisMin.setter
    def XAxisMin(self, value: float) -> None: ...
    @property
    def XAxisMinAuto(self) -> bool: ...
    @XAxisMinAuto.setter
    def XAxisMinAuto(self, value: bool) -> None: ...
    @property
    def XAxisMax(self) -> float: ...
    @XAxisMax.setter
    def XAxisMax(self, value: float) -> None: ...
    @property
    def XAxisMaxAuto(self) -> bool: ...
    @XAxisMaxAuto.setter
    def XAxisMaxAuto(self, value: bool) -> None: ...
    @property
    def XAxisSymmetric(self) -> bool: ...
    @XAxisSymmetric.setter
    def XAxisSymmetric(self, value: bool) -> None: ...
    @property
    def YAxisMin(self) -> float: ...
    @YAxisMin.setter
    def YAxisMin(self, value: float) -> None: ...
    @property
    def YAxisMinAuto(self) -> bool: ...
    @YAxisMinAuto.setter
    def YAxisMinAuto(self, value: bool) -> None: ...
    @property
    def YAxisMax(self) -> float: ...
    @YAxisMax.setter
    def YAxisMax(self, value: float) -> None: ...
    @property
    def YAxisMaxAuto(self) -> bool: ...
    @YAxisMaxAuto.setter
    def YAxisMaxAuto(self, value: bool) -> None: ...
    @property
    def YAxisSymmetric(self) -> bool: ...
    @YAxisSymmetric.setter
    def YAxisSymmetric(self, value: bool) -> None: ...
    @property
    def XYAspectRatio(self) -> float: ...
    @XYAspectRatio.setter
    def XYAspectRatio(self, value: float) -> None: ...
    def SetData(self, fullSize: int, numXValues: int, numYValues: int, rgbData: List[float]) -> None: ...
    def SetDataRGB(self, fullSize: int, numXValues: int, numYValues: int, rData: List[float], gData: List[float], bData: List[float]) -> None: ...
    def SetDataRGBSafe(self, rData: List[float], gData: List[float], bData: List[float]) -> None: ...
    def SetDataSafe(self, rgbData: List[float]) -> None: ...
    def SetXDataDimensions(self, xDataMin: float, xDataMax: float) -> None: ...
    def SetYDataDimensions(self, yDataMin: float, yDataMax: float) -> None: ...

class IUserTextData:
    """ZOSAPI.Analysis.IUserTextData

    Properties and methods for configuring a text User Analysis window. This interface can be accessed via the IUserAnalysisData interface.
    """
    @property
    def Data(self) -> str: ...
    @Data.setter
    def Data(self, value: str) -> None: ...

class I_Analyses:
    """ZOSAPI.Analysis.I_Analyses

    Methods and interfaces for opening, closing, and retrieving analyses. This interface can be accessed via the IOpticalSystem interface.
    """
    @property
    def NumberOfAnalyses(self) -> int:
        """Gets the number of analyses open in the current system."""
        ...
    @overload
    def CloseAnalysis(self, index: int) -> bool:
        """Closes the specified analysis.

        Args:
            index: The index of the analysis (1 to NumberOfAnalyses).

        Returns:
            true if the specified analysis number is valid; otherwise, false.
        """
        ...
    @overload
    def CloseAnalysis(self, analysis: IA_) -> bool:
        """Closes the specified analysis.

        Args:
            analysis: The analysis to close.

        Returns:
            true if the analysis is valid and open; otherwise, false.
        """
        ...
    def CreateColorTranslatorAuto(self, palette: ColorPaletteType, inversePalette: bool, numberOfShades: int = ...) -> IColorTranslator:
        """Enum parameter:
            palette -> ZOSAPI.Analysis.ColorPaletteType
        """
        ...
    def CreateColorTranslatorFixed(self, minValue: float, maxValue: float, palette: ColorPaletteType, inversePalette: bool, numberOfShades: int = ...) -> IColorTranslator:
        """Enum parameter:
            palette -> ZOSAPI.Analysis.ColorPaletteType
        """
        ...
    def CreateLogColorTranslatorAuto(self, palette: ColorPaletteType, inversePalette: bool, logBase: float = ..., numberOfShades: int = ...) -> IColorTranslator:
        """Enum parameter:
            palette -> ZOSAPI.Analysis.ColorPaletteType
        """
        ...
    def CreateLogColorTranslatorFixed(self, minValue: float, maxValue: float, palette: ColorPaletteType, inversePalette: bool, logBase: float = ..., numberOfShades: int = ...) -> IColorTranslator:
        """Enum parameter:
            palette -> ZOSAPI.Analysis.ColorPaletteType
        """
        ...
    def Get_AnalysisAtIndex(self, index: int) -> IA_:
        """Retrieve the specified analysis.

        Args:
            index: The index of the analysis (1 to NumberOfAnalyses).

        Returns:
            The specified analysis if it exists; otherwise, null.
        """
        ...
    def New_Analysis(self, AnalysisType: AnalysisIDM) -> IA_:
        """Enum parameter:
            AnalysisType -> ZOSAPI.Analysis.AnalysisIDM

        Create a new analysis of the specified type.

        Args:
            AnalysisType: The type of analysis to open. See AnalysisIDM for the available options.

        Returns:
            The newly opened analysis if successful; otherwise null.
        """
        ...
    def New_Analysis_SettingsFirst(self, AnalysisType: AnalysisIDM) -> IA_:
        """Enum parameter:
            AnalysisType -> ZOSAPI.Analysis.AnalysisIDM

        Create a new analysis of the specified type, but does not run the analysis and wait for it to finish.

        Args:
            AnalysisType: The type of analysis to open. See AnalysisIDM for the available options.

        Returns:
            The newly opened analysis if successful; otherwise null.
        """
        ...
    def New_ConfigurationMatrixSpot(self) -> IA_:
        """Open a new Configuration Matrix Spot Diagram window"""
        ...
    def New_ContrastLossMap(self) -> IA_:
        """Open a new Contrast Loss Map window"""
        ...
    def New_CriticalRayTracer(self) -> IA_:
        """Open a new Critical Ray Tracer window"""
        ...
    def New_DetectorViewer(self) -> IA_:
        """Open a new Detector Viewer window"""
        ...
    def New_DiffractionEncircledEnergy(self) -> IA_:
        """Open a new Diffraction Encircled Energy window"""
        ...
    def New_ExtendedSourceEncircledEnergy(self) -> IA_:
        """Open a new Extended Source Encircled Energy window"""
        ...
    def New_FftMtf(self) -> IA_:
        """Open a new FFT MTF window"""
        ...
    def New_FftMtfMap(self) -> IA_:
        """Open a new FFT MTF Map window"""
        ...
    def New_FftMtfvsField(self) -> IA_:
        """Open a new FFT MTF vs. Field window"""
        ...
    def New_FftPsf(self) -> IA_:
        """Open a new FFT PSF window"""
        ...
    def New_FftPsfCrossSection(self) -> IA_:
        """Open a new FFT PSF Cross Section window"""
        ...
    def New_FftPsfLineEdgeSpread(self) -> IA_:
        """Open a new FFT Line/Edge Spread window"""
        ...
    def New_FftSurfaceMtf(self) -> IA_:
        """Open a new FFT Surface MTF window"""
        ...
    def New_FftThroughFocusMtf(self) -> IA_:
        """Open a new FFT Through Focus MTF window"""
        ...
    def New_FieldCurvatureAndDistortion(self) -> IA_:
        """Open a new Field Curv/Dist window"""
        ...
    def New_FileComparator(self) -> IA_:
        """Open a new File Comparator window"""
        ...
    def New_FocalShiftDiagram(self) -> IA_:
        """Open a new Focal Shift window"""
        ...
    def New_Foucault(self) -> IA_:
        """Open a new Foucault Analysis window"""
        ...
    def New_FullFieldAberration(self) -> IA_:
        """Open a new Full-Field Aberration window"""
        ...
    def New_FullFieldSpot(self) -> IA_:
        """Open a new Full Field Spot Diagram window"""
        ...
    def New_GeometricEncircledEnergy(self) -> IA_:
        """Open a new Geometric Encircled Energy window"""
        ...
    def New_GeometricImageAnalysis(self) -> IA_:
        """Opens a new Geometric Image Analysis window"""
        ...
    def New_GeometricLineEdgeSpread(self) -> IA_:
        """Open a new Line/Edge Spread window"""
        ...
    def New_GeometricMtf(self) -> IA_:
        """Open a new Geometric MTF window"""
        ...
    def New_GeometricMtfMap(self) -> IA_:
        """Open a new Geometric MTF Map window"""
        ...
    def New_GeometricMtfvsField(self) -> IA_:
        """Open a new Geometric MTF vs. Field window"""
        ...
    def New_GeometricThroughFocusMtf(self) -> IA_:
        """Open a new Through Focus Geometric MTF window"""
        ...
    def New_GridDistortion(self) -> IA_:
        """Open a new Grid Distortion window"""
        ...
    def New_GrinProfile(self) -> IA_:
        """Opens a new Grin Profile window"""
        ...
    def New_HuygensMtf(self) -> IA_:
        """Open a new Huygens MTF window"""
        ...
    def New_HuygensMtfvsField(self) -> IA_:
        """Open a new Huygens MTF vs. Field window"""
        ...
    def New_HuygensPsf(self) -> IA_:
        """Open a new Huygens PSF window"""
        ...
    def New_HuygensPsfCrossSection(self) -> IA_:
        """Open a new Huygens PSF Cross Section window"""
        ...
    def New_HuygensSurfaceMtf(self) -> IA_:
        """Open a new Huygens Surface MTF window"""
        ...
    def New_HuygensThroughFocusMtf(self) -> IA_:
        """Open a new Huygens Through Focus MTF window"""
        ...
    def New_ImageSimulation(self) -> IA_:
        """Opens a new Image Simulation window"""
        ...
    def New_Interferogram(self) -> IA_:
        """Open a new Interferogram window"""
        ...
    def New_InternalTransmissionvsWavelength(self) -> IA_:
        """Opens a new Internal Transmission vs Wavelength window"""
        ...
    def New_LateralColor(self) -> IA_:
        """Open a new Lateral Color window"""
        ...
    def New_LongitudinalAberration(self) -> IA_:
        """Open a new Longitudinal Aberration window"""
        ...
    def New_MatrixSpot(self) -> IA_:
        """Open a new Matrix Spot Diagram window"""
        ...
    def New_OpticalPathFan(self) -> IA_:
        """Open a new OPD Fan window"""
        ...
    def New_PathAnalysis(self) -> IA_:
        """Open a new Path Analysis window"""
        ...
    def New_PupilAberrationFan(self) -> IA_:
        """Open a new Pupil Aberration Fan window"""
        ...
    def New_QuickYield(self) -> IA_:
        """Opens a new Quick Yield window"""
        ...
    def New_RMSField(self) -> IA_:
        """Open a new RMS vs. Field window"""
        ...
    def New_RMSFieldMap(self) -> IA_:
        """Open a new RMS Field Map window"""
        ...
    def New_RMSFocus(self) -> IA_:
        """Open a new RMS vs. Focus window"""
        ...
    def New_RMSLambdaDiagram(self) -> IA_:
        """Open a new RMS vs. Wavelength window"""
        ...
    def New_RayFan(self) -> IA_:
        """Open a new Ray Fan window"""
        ...
    def New_RayTrace(self) -> IA_:
        """Open a new Single Ray Trace window"""
        ...
    def New_RelativeIllumination(self) -> IA_:
        """Opens a new Relative Illumination window"""
        ...
    def New_SeidelCoefficients(self) -> IA_:
        """Open a new Seidel Coefficients window"""
        ...
    def New_SeidelDiagram(self) -> IA_:
        """Open a new Seidel Diagram window"""
        ...
    def New_StandardSpot(self) -> IA_:
        """Open a new Spot Diagram window"""
        ...
    def New_SurfaceCurvature(self) -> IA_:
        """Open a new Surface Curvature window"""
        ...
    def New_SurfaceCurvatureCross(self) -> IA_:
        """Open a new Surface Curvature Cross Section window"""
        ...
    def New_SurfacePhase(self) -> IA_:
        """Open a new Surface Phase window"""
        ...
    def New_SurfacePhaseCross(self) -> IA_:
        """Open a new Surface Phase Cross Section window"""
        ...
    def New_SurfaceSag(self) -> IA_:
        """Open a new Surface Sag window"""
        ...
    def New_SurfaceSagCross(self) -> IA_:
        """Open a new Surface Sag Cross Section window"""
        ...
    def New_SurfaceSlope(self) -> IA_:
        """Opens a new Surface Slope window"""
        ...
    def New_SurfaceSlopeCross(self) -> IA_:
        """Opens a new Surface Slope Cross Section window"""
        ...
    def New_ThroughFocusSpot(self) -> IA_:
        """Open a new Through Focus Spot Diagram window"""
        ...
    def New_TolerancingHistogram(self) -> IA_:
        """Opens a new Tolerancing Histogram window"""
        ...
    def New_TolerancingYield(self) -> IA_:
        """Opens a new Tolerancing Yield window"""
        ...
    def New_WavefrontMap(self) -> IA_:
        """Open a new Wavefront Map window"""
        ...
    def New_XXXTemplateXXX(self) -> IA_: ...
    def New_ZernikeAnnularCoefficients(self) -> IA_:
        """Open a new Zernike Annular Coefficients window"""
        ...
    def New_ZernikeCoefficientsVsField(self) -> IA_:
        """Open a new Zernike Coefficients vs. Field window"""
        ...
    def New_ZernikeFringeCoefficients(self) -> IA_:
        """Open a new Zernike Fringe Coefficients window"""
        ...
    def New_ZernikeStandardCoefficients(self) -> IA_:
        """Open a new Zernike Standard Coefficients window"""
        ...
    def RunHighSamplingPOP(self, configFile: str, xSampling: POPSampling, ySampling: POPSampling, outputTextFile: str, outputBeamFileName: str, saveBeamAtAllSurfaces: bool) -> IMessage:
        """Enum parameters:
            xSampling -> ZOSAPI.Analysis.POPSampling
            ySampling -> ZOSAPI.Analysis.POPSampling

        Generates output from a POP analysis at higher sampling than normally allowed.

        Args:
            configFile: Full path to a CFG file to use for the POP settings; if no configuration file is specified default settings will be used. Note that it is recommended to save the CFG file from a text window, as not all graphic window settings are meaningful for text output.
            xSampling: Sampling override in the X-direction.
            ySampling: Sampling override in the Y-direction.
            outputTextFile: Full path to save the text output file; if ommitted no output file will be saved.
            outputBeamFileName: File name only for the output beam file; the file will be saved in the POP\\BEAMFILES directory.
            saveBeamAtAllSurfaces: Flag to save the output beam for all surfaces; if outputBeamFileName is omitted, this flag will be ignored.
        """
        ...

class POPSampling(IntEnum):
    """ZOSAPI.Analysis.POPSampling"""
    S_32 = 5
    S_64 = 6
    S_128 = 7
    S_256 = 8
    S_512 = 9
    S_1024 = 10
    S_2048 = 11
    S_4096 = 12
    S_8192 = 13
    S_16384 = 14
    S_32768 = 15
    S_65536 = 16
    S_131072 = 17
    S_262144 = 18
    S_524288 = 19
    S_1048576 = 20
    S_2097152 = 21
    S_4194304 = 22
    S_8388608 = 23
    S_16777216 = 24
    S_33554432 = 25
    S_67108864 = 26
    S_134217728 = 27
    S_268435456 = 28
    S_536870912 = 29
    S_1073741824 = 30
    S_1K = 10
    S_2K = 11
    S_4K = 12
    S_8K = 13
    S_16K = 14
    S_32K = 15
    S_64K = 16
    S_128K = 17
    S_256K = 18
    S_512K = 19
    S_1M = 20
    S_2M = 21
    S_4M = 22
    S_8M = 23
    S_16M = 24
    S_32M = 25
    S_64M = 26
    S_128M = 27
    S_256M = 28
    S_512M = 29
    S_1G = 30

class RemoveOptions(IntEnum):
    """ZOSAPI.Analysis.RemoveOptions"""
    None_ = 0
    BaseROC = 1
    BestFitSphere = 2
    BaseSag = 3

class SampleSizes(IntEnum):
    """ZOSAPI.Analysis.SampleSizes"""
    S_32x32 = 1
    S_64x64 = 2
    S_128x128 = 3
    S_256x256 = 4
    S_512x512 = 5
    S_1024x1024 = 6
    S_2048x2048 = 7
    S_4096x4096 = 8
    S_8192x8192 = 9
    S_16384x16384 = 10

class SampleSizes_ContrastLoss(IntEnum):
    """ZOSAPI.Analysis.SampleSizes_ContrastLoss"""
    S_3x3 = 1
    S_5x5 = 2
    S_7x7 = 3
    S_9x9 = 4
    S_11x11 = 5
    S_13x13 = 6
    S_15x15 = 7
    S_17x17 = 8
    S_19x19 = 9
    S_21x21 = 10
    S_23x23 = 11
    S_25x25 = 12
    S_27x27 = 13
    S_29x29 = 14
    S_31x31 = 15
    S_33x33 = 16
    S_35x35 = 17
    S_37x37 = 18
    S_39x39 = 19
    S_41x41 = 20
    S_43x43 = 21
    S_45x45 = 22
    S_47x47 = 23
    S_49x49 = 24
    S_51x51 = 25
    S_53x53 = 26
    S_55x55 = 27
    S_57x57 = 28
    S_59x59 = 29
    S_61x61 = 30
    S_63x63 = 31
    S_65x65 = 32
    S_67x67 = 33
    S_69x69 = 34
    S_71x71 = 35
    S_73x73 = 36
    S_75x75 = 37
    S_77x77 = 38
    S_79x79 = 39
    S_81x81 = 40
    S_83x83 = 41

class SampleSizes_Pow2Plus1(IntEnum):
    """ZOSAPI.Analysis.SampleSizes_Pow2Plus1"""
    S_33 = 1
    S_65 = 2
    S_129 = 3
    S_257 = 4
    S_513 = 5
    S_1025 = 6
    S_2049 = 7
    S_4097 = 8
    S_8193 = 9

class SampleSizes_Pow2Plus1_X(IntEnum):
    """ZOSAPI.Analysis.SampleSizes_Pow2Plus1_X"""
    S_33x33 = 1
    S_65x65 = 2
    S_129x129 = 3
    S_257x257 = 4
    S_513x513 = 5
    S_1025x1025 = 6
    S_2049x2049 = 7
    S_4097x4097 = 8
    S_8193x8193 = 9

class ShowAs(IntEnum):
    """ZOSAPI.Analysis.ShowAs"""
    Surface = 0
    Contour = 1
    GreyScale = 2
    InverseGreyScale = 3
    FalseColor = 4
    InverseFalseColor = 5

class SurfaceCurvatureCrossData(IntEnum):
    """ZOSAPI.Analysis.SurfaceCurvatureCrossData"""
    TangentialCurvature = 0
    SagitalCurvature = 1
    X_Curvature = 2
    Y_Curvature = 3
    TanPlusSagCurvature = 4
    XPlusYCurvature = 5

class SurfaceCurvatureData(IntEnum):
    """ZOSAPI.Analysis.SurfaceCurvatureData"""
    TangentialCurvature = 0
    SagitalCurvature = 1
    X_Curvature = 2
    Y_Curvature = 3

class SurfacePhaseData(IntEnum):
    """ZOSAPI.Analysis.SurfacePhaseData"""
    SurfacePhase = 0

class SurfaceSagData(IntEnum):
    """ZOSAPI.Analysis.SurfaceSagData"""
    SurfaceSag = 0

class SurfaceSlopeCrossData(IntEnum):
    """ZOSAPI.Analysis.SurfaceSlopeCrossData"""
    TangentialCurvature = 0
    SagitalCurvature = 1
    X_Curvature = 2
    Y_Curvature = 3
    TanPlusSagCurvature = 4
    XPlusYCurvature = 5

class SurfaceSlopeData(IntEnum):
    """ZOSAPI.Analysis.SurfaceSlopeData"""
    SurfaceSlope = 0
    TangentialSlope = 0
    SagittalSlope = 1
    XSlope = 2
    YSlope = 3

class UserAnalysisDataType(IntEnum):
    """ZOSAPI.Analysis.UserAnalysisDataType"""
    None_ = 0
    Line2D = 1
    Grid = 2
    GridRGB = 3
    Text = 4
