# Auto-generated by zosapi-stubgen — do not edit by hand.
# Re-run `zosapi-stubgen` to refresh after an OpticStudio upgrade.
from __future__ import annotations
from typing import (
    Any, Dict, Generic, Iterable, Iterator, List,
    Optional, overload, Sequence, Set, Tuple, TypeVar, Union,
)
from enum import IntEnum, IntFlag
from datetime import datetime, timedelta

import ZOSAPI.Analysis
import ZOSAPI.Editors

class FNumberComputationType(IntEnum):
    """ZOSAPI.SystemData.FNumberComputationType"""
    TracingRays = 0
    PupilSizePosition = 1

class FieldColumn(IntEnum):
    """ZOSAPI.SystemData.FieldColumn"""
    Comment = 0
    X = 1
    Y = 2
    Weight = 3
    VDX = 4
    VDY = 5
    VCX = 6
    VCY = 7
    TAN = 8
    VAN = 8

class FieldNormalizationType(IntEnum):
    """ZOSAPI.SystemData.FieldNormalizationType"""
    Radial = 0
    Rectangular = 1

class FieldPattern(IntEnum):
    """ZOSAPI.SystemData.FieldPattern"""
    UniformY = 0
    EqualAreaY = 1
    UniformX = 2
    EqualAreaX = 3
    Grid = 4
    UniformRadial = 5
    EqualAreaRadial = 6

class FieldType(IntEnum):
    """ZOSAPI.SystemData.FieldType"""
    Angle = 0
    ObjectHeight = 1
    ParaxialImageHeight = 2
    RealImageHeight = 3
    TheodoliteAngle = 4

class HuygensIntegralSettings(IntEnum):
    """ZOSAPI.SystemData.HuygensIntegralSettings"""
    Auto = 0
    Planar = 1
    Spherical = 2

class IField:
    """ZOSAPI.SystemData.IField

    System field data. This interface can be accessed via the IFields interface.
    """
    @property
    def IsActive(self) -> bool: ...
    @property
    def FieldNumber(self) -> int: ...
    @property
    def X(self) -> float: ...
    @X.setter
    def X(self, value: float) -> None: ...
    @property
    def Y(self) -> float: ...
    @Y.setter
    def Y(self, value: float) -> None: ...
    @property
    def Weight(self) -> float: ...
    @Weight.setter
    def Weight(self, value: float) -> None: ...
    @property
    def VDX(self) -> float: ...
    @VDX.setter
    def VDX(self, value: float) -> None: ...
    @property
    def VDY(self) -> float: ...
    @VDY.setter
    def VDY(self, value: float) -> None: ...
    @property
    def VCX(self) -> float: ...
    @VCX.setter
    def VCX(self, value: float) -> None: ...
    @property
    def VCY(self) -> float: ...
    @VCY.setter
    def VCY(self, value: float) -> None: ...
    @property
    def VAN(self) -> float: ...
    @VAN.setter
    def VAN(self, value: float) -> None: ...
    @property
    def TAN(self) -> float: ...
    @TAN.setter
    def TAN(self, value: float) -> None: ...
    @property
    def Comment(self) -> str: ...
    @Comment.setter
    def Comment(self, value: str) -> None: ...
    @property
    def XSolve(self) -> ZOSAPI.Editors.SolveType: ...
    @property
    def YSolve(self) -> ZOSAPI.Editors.SolveType: ...
    @property
    def Ignore(self) -> bool: ...
    @Ignore.setter
    def Ignore(self, value: bool) -> None: ...
    def GetSolveData(self, forColumn: FieldColumn) -> ZOSAPI.Editors.ISolveData:
        """Enum parameter:
            forColumn -> ZOSAPI.SystemData.FieldColumn
        """
        ...
    def GetXSolveData(self) -> ZOSAPI.Editors.ISolveData: ...
    def GetYSolveData(self) -> ZOSAPI.Editors.ISolveData: ...
    def SetFixed(self, forColumn: FieldColumn) -> ZOSAPI.Editors.SolveStatus:
        """Enum parameter:
            forColumn -> ZOSAPI.SystemData.FieldColumn
        """
        ...
    def SetPickup(self, forColumn: FieldColumn, fromField: int, fromColumn: FieldColumn, scale: float, offset: float) -> ZOSAPI.Editors.SolveStatus:
        """Enum parameters:
            forColumn -> ZOSAPI.SystemData.FieldColumn
            fromColumn -> ZOSAPI.SystemData.FieldColumn
        """
        ...
    def SetXFixed(self) -> ZOSAPI.Editors.SolveStatus: ...
    def SetXPickup(self, fromField: int, fromColumn: FieldColumn, scale: float, offset: float) -> ZOSAPI.Editors.SolveStatus:
        """Enum parameter:
            fromColumn -> ZOSAPI.SystemData.FieldColumn
        """
        ...
    def SetYFixed(self) -> ZOSAPI.Editors.SolveStatus: ...
    def SetYPickup(self, fromField: int, fromColumn: FieldColumn, scale: float, offset: float) -> ZOSAPI.Editors.SolveStatus:
        """Enum parameter:
            fromColumn -> ZOSAPI.SystemData.FieldColumn
        """
        ...

class IFields:
    """ZOSAPI.SystemData.IFields

    System Explorer - Fields Data. This interface can be accessed via the ISystemData interface.
    """
    @property
    def NumberOfFields(self) -> int:
        """Gets the number of fields currently defined in the system."""
        ...
    @property
    def Normalization(self) -> FieldNormalizationType: ...
    @Normalization.setter
    def Normalization(self, value: FieldNormalizationType) -> None: ...
    def AddField(self, X: float, Y: float, Weight: float) -> IField:
        """Add a new field, after all the current fields.

        Args:
            X: The field X value.
            Y: The field Y value.
            Weight: The field weight.

        Returns:
            The new IField if there were less than twelve fields; otherwise, null.
        """
        ...
    def ApplyFieldWizard(self, pattern: FieldPattern, numberOfYFields: int, maxFieldY: float, numberOfXFields: int, maxFieldX: float, startAt: int, overwrite: bool, includePickups: bool) -> ZOSAPI.Analysis.IMessage:
        """Enum parameter:
            pattern -> ZOSAPI.SystemData.FieldPattern

        Adds new system fields with specified in the specified pattern.

        Args:
            pattern: The new field pattern to use pattern.
            numberOfYFields: The number of y fields or arms.
            maxFieldY: The maximum field in the y-direction.
            numberOfXFields: The number of x fields or radii.
            maxFieldX: The maximum field in the x-direction.
            startAt: The field # to start inserting or overwriting at.
            overwrite: if set to true overwrite the fields data, else insert new fields.
            includePickups: if set to true add pickups after the maximum field values.

        Returns:
            null if successful, otherwise an error message
        """
        ...
    def ClearVignetting(self) -> None: ...
    def ConvertToFieldType(self, type_: FieldType) -> ZOSAPI.Analysis.IMessage:
        """Enum parameter:
            type_ -> ZOSAPI.SystemData.FieldType
        """
        ...
    def DeleteAllFields(self) -> int: ...
    def DeleteFieldAt(self, fieldNumber: int) -> bool: ...
    def DeleteFieldsAt(self, fieldNumber: int, numberOfFields: int) -> int: ...
    def GetField(self, position: int) -> IField:
        """Gets the specified field.

        Args:
            position: The field # to retrieve (1-MAX_FIELDS).

        Returns:
            The specified IField, if the position is valid; otherwise, null.
        """
        ...
    def GetFieldType(self) -> FieldType: ...
    def InsertFieldAt(self, fieldNumber: int) -> IField: ...
    def MakeEqualAreaFields(self, numberOfFields: int, maximumField: float) -> bool:
        """Replaces the existing system fields with new fields spread over an equal area.

        Args:
            numberOfFields: The number of fields.
            maximumField: The maximum field.
        """
        ...
    def RemoveField(self, position: int) -> bool:
        """Removes the specified field.

        Args:
            position: The field # to remove (1-MAX_FIELDS).

        Returns:
            true if the position is valid and there was at least two fields in the system; otherwise, false.
        """
        ...
    def SetFieldType(self, type_: FieldType) -> None:
        """Enum parameter:
            type_ -> ZOSAPI.SystemData.FieldType

        Sets the field type definition for all fields.

        Args:
            type: The new fields type.
        """
        ...
    def SetVignetting(self) -> None: ...

class ISDAdvancedData:
    """ZOSAPI.SystemData.ISDAdvancedData

    System Explorer - Advanced Data. This interface can be accessed via the ISystemData interface.
    """
    @property
    def ReferenceOPD(self) -> ReferenceOPDSetting: ...
    @ReferenceOPD.setter
    def ReferenceOPD(self, value: ReferenceOPDSetting) -> None: ...
    @property
    def ParaxialRays(self) -> ParaxialRaysSetting: ...
    @ParaxialRays.setter
    def ParaxialRays(self, value: ParaxialRaysSetting) -> None: ...
    @property
    def FNumMethod(self) -> FNumberComputationType: ...
    @FNumMethod.setter
    def FNumMethod(self, value: FNumberComputationType) -> None: ...
    @property
    def DontPrintCoordinateBreakData(self) -> bool: ...
    @DontPrintCoordinateBreakData.setter
    def DontPrintCoordinateBreakData(self, value: bool) -> None: ...
    @property
    def TurnOffThreading(self) -> bool: ...
    @TurnOffThreading.setter
    def TurnOffThreading(self, value: bool) -> None: ...
    @property
    def OPDModulo2PI(self) -> bool: ...
    @OPDModulo2PI.setter
    def OPDModulo2PI(self, value: bool) -> None: ...
    @property
    def IncludeCalculatedDataInSessionFile(self) -> bool: ...
    @IncludeCalculatedDataInSessionFile.setter
    def IncludeCalculatedDataInSessionFile(self, value: bool) -> None: ...
    @property
    def IncludeToleranceDataInSessionFile(self) -> bool: ...
    @IncludeToleranceDataInSessionFile.setter
    def IncludeToleranceDataInSessionFile(self, value: bool) -> None: ...
    @property
    def HuygensIntegralMethod(self) -> HuygensIntegralSettings: ...
    @HuygensIntegralMethod.setter
    def HuygensIntegralMethod(self, value: HuygensIntegralSettings) -> None: ...

class ISDApertureData:
    """ZOSAPI.SystemData.ISDApertureData

    System Explorer - Aperture Data. This interface can be accessed via the ISystemData interface.
    """
    @property
    def ApertureType(self) -> ZemaxApertureType: ...
    @ApertureType.setter
    def ApertureType(self, value: ZemaxApertureType) -> None: ...
    @property
    def ApertureValue(self) -> float: ...
    @ApertureValue.setter
    def ApertureValue(self, value: float) -> None: ...
    @property
    def ApodizationType(self) -> ZemaxApodizationType: ...
    @ApodizationType.setter
    def ApodizationType(self, value: ZemaxApodizationType) -> None: ...
    @property
    def ApodizationFactor(self) -> float: ...
    @ApodizationFactor.setter
    def ApodizationFactor(self, value: float) -> None: ...
    @property
    def ApodizationFactorIsUsed(self) -> bool: ...
    @property
    def SemiDiameterMargin(self) -> float: ...
    @SemiDiameterMargin.setter
    def SemiDiameterMargin(self, value: float) -> None: ...
    @property
    def SemiDiameterMarginPct(self) -> float: ...
    @SemiDiameterMarginPct.setter
    def SemiDiameterMarginPct(self, value: float) -> None: ...
    @property
    def GCRS(self) -> ISurfaceSelection: ...
    @property
    def TelecentricObjectSpace(self) -> bool: ...
    @TelecentricObjectSpace.setter
    def TelecentricObjectSpace(self, value: bool) -> None: ...
    @property
    def AFocalImageSpace(self) -> bool: ...
    @AFocalImageSpace.setter
    def AFocalImageSpace(self, value: bool) -> None: ...
    @property
    def IterateSolvesWhenUpdating(self) -> bool: ...
    @IterateSolvesWhenUpdating.setter
    def IterateSolvesWhenUpdating(self, value: bool) -> None: ...
    @property
    def FastSemiDiameters(self) -> bool: ...
    @FastSemiDiameters.setter
    def FastSemiDiameters(self, value: bool) -> None: ...
    @property
    def CheckGRINApertures(self) -> bool: ...
    @CheckGRINApertures.setter
    def CheckGRINApertures(self, value: bool) -> None: ...

class ISDEnvironmentData:
    """ZOSAPI.SystemData.ISDEnvironmentData

    System Explorer - Environment Data. This interface can be accessed via the ISystemData interface.
    """
    @property
    def AdjustIndexToEnvironment(self) -> bool: ...
    @AdjustIndexToEnvironment.setter
    def AdjustIndexToEnvironment(self, value: bool) -> None: ...
    @property
    def Temperature(self) -> float: ...
    @Temperature.setter
    def Temperature(self, value: float) -> None: ...
    @property
    def Pressure(self) -> float: ...
    @Pressure.setter
    def Pressure(self, value: float) -> None: ...

class ISDFiles:
    """ZOSAPI.SystemData.ISDFiles

    System Explorer - Files Data. This interface can be accessed via the ISystemData interface.
    """
    @property
    def CoatingFile(self) -> str: ...
    @CoatingFile.setter
    def CoatingFile(self, value: str) -> None: ...
    @property
    def ScatterProfile(self) -> str: ...
    @ScatterProfile.setter
    def ScatterProfile(self, value: str) -> None: ...
    @property
    def ABgDataFile(self) -> str: ...
    @ABgDataFile.setter
    def ABgDataFile(self, value: str) -> None: ...
    @property
    def GradiumProfile(self) -> str: ...
    @GradiumProfile.setter
    def GradiumProfile(self, value: str) -> None: ...
    def GetABgDataFiles(self) -> List[str]: ...
    def GetCoatingFiles(self) -> List[str]: ...
    def GetGradiumProfiles(self) -> List[str]: ...
    def GetScatterProfiles(self) -> List[str]: ...
    def ReloadFiles(self) -> None: ...

class ISDMaterialCatalogData:
    """ZOSAPI.SystemData.ISDMaterialCatalogData

    System Explorer - Material Catalogs Data. This interface can be accessed via the ISystemData interface.
    """
    def AddCatalog(self, catalog: str) -> bool:
        """Adds the specified material to the system.

        Args:
            catalog: The material catalog to add.
        """
        ...
    def GetAvailableCatalogs(self) -> List[str]: ...
    def GetCatalogsInUse(self) -> List[str]: ...
    def GetMaterialsInCatalog(self, catalog: str) -> List[str]: ...
    def IsCatalogInUse(self, catalog: str) -> bool: ...
    def RemoveCatalog(self, catalog: str) -> bool:
        """Removes the specified material catalog from the system.

        Args:
            catalog: The material catalog to remove.
        """
        ...

class ISDNamedFilters:
    """ZOSAPI.SystemData.ISDNamedFilters

    System Explorer - Named Filters Data. This interface can be accessed via the ISystemData interface.
    """
    @property
    def NamedFilters(self) -> str: ...
    @NamedFilters.setter
    def NamedFilters(self, value: str) -> None: ...

class ISDNonSeqData:
    """ZOSAPI.SystemData.ISDNonSeqData

    System Explorer - Non-Sequential Data. This interface can be accessed via the ISystemData interface.
    """
    @property
    def MaximumIntersectionsPerRay(self) -> int: ...
    @MaximumIntersectionsPerRay.setter
    def MaximumIntersectionsPerRay(self, value: int) -> None: ...
    @property
    def MaximumSegmentsPerRay(self) -> int: ...
    @MaximumSegmentsPerRay.setter
    def MaximumSegmentsPerRay(self, value: int) -> None: ...
    @property
    def MaximumNestedTouchingObjects(self) -> int: ...
    @MaximumNestedTouchingObjects.setter
    def MaximumNestedTouchingObjects(self, value: int) -> None: ...
    @property
    def MaximumSourceFileRaysInMemory(self) -> int: ...
    @MaximumSourceFileRaysInMemory.setter
    def MaximumSourceFileRaysInMemory(self, value: int) -> None: ...
    @property
    def MinimumRelativeRayIntensity(self) -> float: ...
    @MinimumRelativeRayIntensity.setter
    def MinimumRelativeRayIntensity(self, value: float) -> None: ...
    @property
    def MinimumAbsoluteRayIntensity(self) -> float: ...
    @MinimumAbsoluteRayIntensity.setter
    def MinimumAbsoluteRayIntensity(self, value: float) -> None: ...
    @property
    def GlueDistanceInLensUnits(self) -> float: ...
    @GlueDistanceInLensUnits.setter
    def GlueDistanceInLensUnits(self, value: float) -> None: ...
    @property
    def MissedRayDrawDistanceInLensUnits(self) -> float: ...
    @MissedRayDrawDistanceInLensUnits.setter
    def MissedRayDrawDistanceInLensUnits(self, value: float) -> None: ...
    @property
    def SimpleRaySplitting(self) -> bool: ...
    @SimpleRaySplitting.setter
    def SimpleRaySplitting(self, value: bool) -> None: ...
    @property
    def RetraceSourceRaysUponFileOpen(self) -> bool: ...
    @RetraceSourceRaysUponFileOpen.setter
    def RetraceSourceRaysUponFileOpen(self, value: bool) -> None: ...

class ISDPolarizationData:
    """ZOSAPI.SystemData.ISDPolarizationData

    System Explorer - Polarization Data. This interface can be accessed via the ISystemData interface.
    """
    @property
    def ConvertThinFilmPhaseToRayEquivalent(self) -> bool: ...
    @ConvertThinFilmPhaseToRayEquivalent.setter
    def ConvertThinFilmPhaseToRayEquivalent(self, value: bool) -> None: ...
    @property
    def Unpolarized(self) -> bool: ...
    @Unpolarized.setter
    def Unpolarized(self, value: bool) -> None: ...
    @property
    def Jx(self) -> float: ...
    @Jx.setter
    def Jx(self, value: float) -> None: ...
    @property
    def Jy(self) -> float: ...
    @Jy.setter
    def Jy(self, value: float) -> None: ...
    @property
    def XPhase(self) -> float: ...
    @XPhase.setter
    def XPhase(self, value: float) -> None: ...
    @property
    def YPhase(self) -> float: ...
    @YPhase.setter
    def YPhase(self, value: float) -> None: ...
    @property
    def Method(self) -> PolarizationMethod: ...
    @Method.setter
    def Method(self, value: PolarizationMethod) -> None: ...

class ISDRayAimingData:
    """ZOSAPI.SystemData.ISDRayAimingData

    System Explorer - Ray Aiming Data. This interface can be accessed via the ISystemData interface.
    """
    @property
    def RayAiming(self) -> RayAimingMethod: ...
    @RayAiming.setter
    def RayAiming(self, value: RayAimingMethod) -> None: ...
    @property
    def UseRayAimingCache(self) -> bool: ...
    @UseRayAimingCache.setter
    def UseRayAimingCache(self, value: bool) -> None: ...
    @property
    def UseRobustRayAiming(self) -> bool: ...
    @UseRobustRayAiming.setter
    def UseRobustRayAiming(self, value: bool) -> None: ...
    @property
    def ScalePupilShiftFactorsByField(self) -> bool: ...
    @ScalePupilShiftFactorsByField.setter
    def ScalePupilShiftFactorsByField(self, value: bool) -> None: ...
    @property
    def AutomaticallyCalculatePupilShiftsIsChecked(self) -> bool: ...
    @AutomaticallyCalculatePupilShiftsIsChecked.setter
    def AutomaticallyCalculatePupilShiftsIsChecked(self, value: bool) -> None: ...
    @property
    def PupilShiftX(self) -> float: ...
    @PupilShiftX.setter
    def PupilShiftX(self, value: float) -> None: ...
    @property
    def PupilShiftY(self) -> float: ...
    @PupilShiftY.setter
    def PupilShiftY(self, value: float) -> None: ...
    @property
    def PupilShiftZ(self) -> float: ...
    @PupilShiftZ.setter
    def PupilShiftZ(self, value: float) -> None: ...
    @property
    def PupilCompressX(self) -> float: ...
    @PupilCompressX.setter
    def PupilCompressX(self, value: float) -> None: ...
    @property
    def PupilCompressY(self) -> float: ...
    @PupilCompressY.setter
    def PupilCompressY(self, value: float) -> None: ...

class ISDTitleNotes:
    """ZOSAPI.SystemData.ISDTitleNotes

    System Explorer - Notes Data. This interface can be accessed via the ISystemData interface.
    """
    @property
    def Title(self) -> str: ...
    @Title.setter
    def Title(self, value: str) -> None: ...
    @property
    def Notes(self) -> str: ...
    @Notes.setter
    def Notes(self, value: str) -> None: ...
    @property
    def Author(self) -> str: ...
    @Author.setter
    def Author(self, value: str) -> None: ...

class ISDUnitsData:
    """ZOSAPI.SystemData.ISDUnitsData

    System Explorer - Units Data. This interface can be accessed via the ISystemData interface.
    """
    @property
    def LensUnits(self) -> ZemaxSystemUnits: ...
    @LensUnits.setter
    def LensUnits(self, value: ZemaxSystemUnits) -> None: ...
    @property
    def SourceUnitPrefix(self) -> ZemaxUnitPrefix: ...
    @SourceUnitPrefix.setter
    def SourceUnitPrefix(self, value: ZemaxUnitPrefix) -> None: ...
    @property
    def SourceUnits(self) -> ZemaxSourceUnits: ...
    @SourceUnits.setter
    def SourceUnits(self, value: ZemaxSourceUnits) -> None: ...
    @property
    def AnalysisUnitPrefix(self) -> ZemaxUnitPrefix: ...
    @AnalysisUnitPrefix.setter
    def AnalysisUnitPrefix(self, value: ZemaxUnitPrefix) -> None: ...
    @property
    def AnalysisUnits(self) -> ZemaxAnalysisUnits: ...
    @AnalysisUnits.setter
    def AnalysisUnits(self, value: ZemaxAnalysisUnits) -> None: ...
    @property
    def AfocalModeUnits(self) -> ZemaxAfocalModeUnits: ...
    @AfocalModeUnits.setter
    def AfocalModeUnits(self, value: ZemaxAfocalModeUnits) -> None: ...
    @property
    def MTFUnits(self) -> ZemaxMTFUnits: ...
    @MTFUnits.setter
    def MTFUnits(self, value: ZemaxMTFUnits) -> None: ...

class ISurfaceSelection:
    """ZOSAPI.SystemData.ISurfaceSelection"""
    @property
    def FirstAllowedSurface(self) -> int: ...
    @property
    def LastAllowedSurface(self) -> int: ...
    @property
    def ImageSurface(self) -> int: ...
    @property
    def StopSurface(self) -> int: ...
    def GetSelectedSurface(self) -> int: ...
    def SetSelectedSurface(self, Surface: int) -> bool: ...
    def UseImageSurface(self) -> bool: ...
    def UseObjectSurface(self) -> bool: ...
    def UseStopSurface(self) -> bool: ...

class ISystemData:
    """ZOSAPI.SystemData.ISystemData

    Interfaces and methods for changing all System Explorer data. This interface can be accessed via the IOpticalSystem interface.
    """
    @property
    def Aperture(self) -> ISDApertureData: ...
    @property
    def Wavelengths(self) -> IWavelengths: ...
    @property
    def Fields(self) -> IFields: ...
    @property
    def Environment(self) -> ISDEnvironmentData: ...
    @property
    def Polarization(self) -> ISDPolarizationData: ...
    @property
    def Advanced(self) -> ISDAdvancedData: ...
    @property
    def RayAiming(self) -> ISDRayAimingData: ...
    @property
    def MaterialCatalogs(self) -> ISDMaterialCatalogData: ...
    @property
    def TitleNotes(self) -> ISDTitleNotes: ...
    @property
    def Files(self) -> ISDFiles: ...
    @property
    def Units(self) -> ISDUnitsData: ...
    @property
    def NonSequentialData(self) -> ISDNonSeqData: ...
    @property
    def NamedFiltersData(self) -> ISDNamedFilters: ...

class IWavelength:
    """ZOSAPI.SystemData.IWavelength

    System wavelength data. This interface can be accessed via the IWavelengths interface.
    """
    @property
    def WavelengthNumber(self) -> int: ...
    @property
    def IsActive(self) -> bool: ...
    @property
    def IsPrimary(self) -> bool: ...
    @property
    def Wavelength(self) -> float: ...
    @Wavelength.setter
    def Wavelength(self, value: float) -> None: ...
    @property
    def Weight(self) -> float: ...
    @Weight.setter
    def Weight(self, value: float) -> None: ...
    def MakePrimary(self) -> None: ...

class IWavelengths:
    """ZOSAPI.SystemData.IWavelengths

    System Explorer - Wavelengths Data. This interface can be accessed via the ISystemData interface.
    """
    @property
    def NumberOfWavelengths(self) -> int:
        """Gets the number of wavelengths currently defined in the system."""
        ...
    def AddWavelength(self, Wavelength: float, Weight: float) -> IWavelength:
        """Add a new wavelengths, after all the current wavelengths.

        Args:
            Wavelength: The wavelength (um).
            Weight: The weight.

        Returns:
            The new IWavelength if there were less than twelve wavelengths; otherwise, null.
        """
        ...
    def GaussianQuadrature(self, minWave: float, maxWave: float, numSteps: QuadratureSteps) -> bool:
        """Enum parameter:
            numSteps -> ZOSAPI.SystemData.QuadratureSteps

        Generates a new set of system wavelengths based on a Gaussian Quadrature method.

        Args:
            minWave: The starting wavelength (microns).
            maxWave: The ending wavelength (microns).
            numSteps: The total number of wavelengths (2-24).
        """
        ...
    def GetWavelength(self, position: int) -> IWavelength:
        """Gets the specified wavelength."/>.

        Args:
            position: The wavelength * to retrieve (1-24).

        Returns:
            The specified IWavelength, if the position is valid; otherwise, null.
        """
        ...
    def RemoveWavelength(self, position: int) -> bool:
        """Removes the specified wavelength.

        Args:
            position: The wavelength # to remove (1-24).

        Returns:
            true if the position is valid and there were at least two wavelengths in the system; otherwise, false.
        """
        ...
    def SelectWavelengthPreset(self, preset: WavelengthPreset) -> bool:
        """Enum parameter:
            preset -> ZOSAPI.SystemData.WavelengthPreset

        Replaces all system wavelengths with a preset definition.

        Args:
            preset: The new preset.
        """
        ...

class ParaxialRaysSetting(IntEnum):
    """ZOSAPI.SystemData.ParaxialRaysSetting"""
    ConsiderCoordinateBreaks = 0
    IgnoreCoordinateBreaks = 1

class PolarizationMethod(IntEnum):
    """ZOSAPI.SystemData.PolarizationMethod"""
    XAxisMethod = 0
    YAxisMethod = 1
    ZAxisMethod = 2

class QuadratureSteps(IntEnum):
    """ZOSAPI.SystemData.QuadratureSteps"""
    S2 = 0
    S4 = 1
    S6 = 2
    S8 = 3
    S10 = 4
    S12 = 5

class RayAimingMethod(IntEnum):
    """ZOSAPI.SystemData.RayAimingMethod"""
    Off = 0
    Paraxial = 1
    Real = 2

class ReferenceOPDSetting(IntEnum):
    """ZOSAPI.SystemData.ReferenceOPDSetting"""
    Absolute = 0
    Infinity = 1
    ExitPupil = 2
    Absolute2 = 3

class WavelengthPreset(IntEnum):
    """ZOSAPI.SystemData.WavelengthPreset"""
    FdC_Visible = 0
    Photopic_Bright = 1
    Scotopic_Dark = 2
    HeNe_0p6328 = 3
    HeNe_0p5438 = 4
    Argon_0p4880 = 5
    Argon_0p5145 = 6
    NDYAG_1p0641 = 7
    NDGlass_1p054 = 8
    CO2_10p60 = 9
    CrLiSAF_0p840 = 10
    TiAl203_0p760 = 11
    Ruby_0p6943 = 12
    HeCadmium_0p4416 = 13
    HeCadmium_0p3536 = 14
    HeCadmium_0p3250 = 15
    t_1p014 = 16
    r_0p707 = 17
    C_0p656 = 18
    d_0p587 = 19
    F_0p486 = 20
    g_0p436 = 21
    i_0p365 = 22
    Fp_0p365 = 23
    e_0p54607 = 24
    Cp_0p6438469 = 25
    FpeCp_Visible = 26
    THz_193p10 = 27

class ZemaxAfocalModeUnits(IntEnum):
    """ZOSAPI.SystemData.ZemaxAfocalModeUnits"""
    Microradians = 0
    Milliradians = 1
    Radians = 2
    ArcSeconds = 3
    ArcMinutes = 4
    Degrees = 5

class ZemaxAnalysisUnits(IntEnum):
    """ZOSAPI.SystemData.ZemaxAnalysisUnits"""
    WattsPerMMSq = 0
    WattsPerCMSq = 1
    WattsPerinSq = 2
    WattsPerMSq = 3
    WattsPerftSq = 4

class ZemaxApertureType(IntEnum):
    """ZOSAPI.SystemData.ZemaxApertureType"""
    EntrancePupilDiameter = 0
    ImageSpaceFNum = 1
    ObjectSpaceNA = 2
    FloatByStopSize = 3
    ParaxialWorkingFNum = 4
    ObjectConeAngle = 5

class ZemaxApodizationType(IntEnum):
    """ZOSAPI.SystemData.ZemaxApodizationType"""
    Uniform = 0
    Gaussian = 1
    CosineCubed = 2

class ZemaxMTFUnits(IntEnum):
    """ZOSAPI.SystemData.ZemaxMTFUnits"""
    CyclesPerMillimeter = 0
    CyclesPerMilliradian = 1

class ZemaxSourceUnits(IntEnum):
    """ZOSAPI.SystemData.ZemaxSourceUnits"""
    Watts = 0
    Lumens = 1
    Joules = 2

class ZemaxSystemUnits(IntEnum):
    """ZOSAPI.SystemData.ZemaxSystemUnits"""
    Millimeters = 0
    Centimeters = 1
    Inches = 2
    Meters = 3

class ZemaxUnitPrefix(IntEnum):
    """ZOSAPI.SystemData.ZemaxUnitPrefix"""
    Femto = 0
    Pico = 1
    Nano = 2
    Micro = 3
    Milli = 4
    None_ = 5
    Kilo = 6
    Mega = 7
    Giga = 8
    Tera = 9
