# Auto-generated by zosapi-stubgen — do not edit by hand.
# Re-run `zosapi-stubgen` to refresh after an OpticStudio upgrade.
from __future__ import annotations
from typing import (
    Any, Dict, Generic, Iterable, Iterator, List,
    Optional, overload, Sequence, Set, Tuple, TypeVar, Union,
)
from enum import IntEnum, IntFlag
from datetime import datetime, timedelta

import ZOSAPI.Analysis
import ZOSAPI.Common
import ZOSAPI.Editors.LDE
import ZOSAPI.Editors.MCE
import ZOSAPI.Editors.MFE
import ZOSAPI.Editors.NCE
import ZOSAPI.Editors.TDE
import ZOSAPI.Preferences
import ZOSAPI.SystemData
import ZOSAPI.Tools
import ZOSAPI.Tools.General

from . import Analysis as Analysis
from . import Common as Common
from . import Editors as Editors
from . import Preferences as Preferences
from . import SystemData as SystemData
from . import Tools as Tools
from . import Wizards as Wizards

class APINetCallback(IZAPI_BaseObject, IZOSAPI_Callback):
    """ZOSAPI.APINetCallback"""
    def __init__(self) -> None: ...
    @property
    def Parent(self) -> IZAPI_BaseObject: ...
    @Parent.setter
    def Parent(self, value: IZAPI_BaseObject) -> None: ...
    @property
    def IsDisposed(self) -> bool: ...
    @IsDisposed.setter
    def IsDisposed(self, value: bool) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def IsLocal(self) -> bool: ...
    @property
    def Settings(self) -> ZOSAPI.Common.ISettingsData: ...
    @Settings.setter
    def Settings(self, value: ZOSAPI.Common.ISettingsData) -> None: ...
    @property
    def TheApp(self) -> IZOSAPI_Application: ...
    @TheApp.setter
    def TheApp(self, value: IZOSAPI_Application) -> None: ...
    def AddChild(self, child: IZAPI_BaseObject) -> None: ...
    def Clone(self) -> APINetCallback: ...
    def Copy(self, theApp: IZOSAPI_Application) -> IZOSAPI_Callback: ...
    def Disconnect(self) -> None: ...
    def Dispose(self) -> None: ...
    def Execute(self) -> int: ...
    def InitializeLifetimeService(self) -> Any: ...
    def LoadInServer(self, TheApp: IZOSAPI_Application) -> IZOSAPI_Callback: ...
    def RegisterUDOCCallback(self, TheApp: IZOSAPI_Application) -> ZOSAPI.Analysis.IMessage: ...
    def RemoveChild(self, child: IZAPI_BaseObject) -> None: ...

class IOpticalSystem:
    """ZOSAPI.IOpticalSystem

    Represent a complete optical system. A IOpticalSystem corresponds to a single .ZMX file. See IZOSAPI_Application for information on how to get or create a IOpticalSystem.
    """
    @property
    def SystemName(self) -> str:
        """Gets or sets the name of the current system."""
        ...
    @SystemName.setter
    def SystemName(self, value: str) -> None: ...
    @property
    def SystemID(self) -> int:
        """Gets a unique identifier for the current system; this can be used to differentiate between multiple IOpticalSystem instances, and to identify the relevant system in a OpticalSystemStatusChangedHandler event."""
        ...
    @property
    def Mode(self) -> SystemType:
        """Gets the current sequential/non-sequential status."""
        ...
    @property
    def SystemFile(self) -> str:
        """Gets the full path and file name for the current system."""
        ...
    @property
    def IsNonAxial(self) -> bool:
        """Gets a value indicating whether the current system is an axial, sequential system."""
        ...
    @property
    def NeedsSave(self) -> bool: ...
    @property
    def SystemData(self) -> ZOSAPI.SystemData.ISystemData:
        """Data for configuring everything in the System Explorer."""
        ...
    @property
    def LDE(self) -> ZOSAPI.Editors.LDE.ILensDataEditor:
        """Gets the lens data editor."""
        ...
    @property
    def NCE(self) -> ZOSAPI.Editors.NCE.INonSeqEditor:
        """Gets the non-sequential component editor."""
        ...
    @property
    def TDE(self) -> ZOSAPI.Editors.TDE.IToleranceDataEditor:
        """Gets the tolerance data editor."""
        ...
    @property
    def MFE(self) -> ZOSAPI.Editors.MFE.IMeritFunctionEditor:
        """Gets the merit function editor."""
        ...
    @property
    def MCE(self) -> ZOSAPI.Editors.MCE.IMultiConfigEditor:
        """Gets the multi-configuration editor."""
        ...
    @property
    def Analyses(self) -> ZOSAPI.Analysis.I_Analyses:
        """Gets the analyses for the current system."""
        ...
    @property
    def Tools(self) -> ZOSAPI.Tools.IOpticalSystemTools:
        """Gets an interface used to run various tools on the optical system."""
        ...
    @property
    def TheApplication(self) -> IZOSAPI_Application:
        """Gets the IZOSAPI_Application that owns this system."""
        ...
    @property
    def UpdateMode(self) -> LensUpdateMode:
        """Gets or sets the update mode used by the API when the system is modified. Note that this is different than the update mode saved with the current ZMX file. The default value is EditorsOnly."""
        ...
    @UpdateMode.setter
    def UpdateMode(self, value: LensUpdateMode) -> None: ...
    @property
    def SessionMode(self) -> SessionModes: ...
    @SessionMode.setter
    def SessionMode(self, value: SessionModes) -> None: ...
    @property
    def STARSubsystem(self) -> ISTARSubsystem: ...
    @property
    def IsProjectDirectory(self) -> bool: ...
    def Close(self, saveIfNeeded: bool) -> bool:
        """Closes the current system, saving if specified. Note that the PrimarySystem cannot be closed.

        Args:
            saveIfNeeded: if set to true the system will before closing (if NeedsSave is true).

        Returns:
            true if the system was closed; otherwise, false.
        """
        ...
    def ConvertToProjectDirectory(self, folderPath: str) -> bool: ...
    def CopySystem(self) -> IOpticalSystem:
        """Creates a copy of this entire system, except for any related analysis windows.

        Returns:
            A new copy of this system.
        """
        ...
    def GetCurrentStatus(self) -> str:
        """Gets the last status of the optical system. If null or the length is 0, then the system has no errors."""
        ...
    def LoadFile(self, LensFile: str, saveIfNeeded: bool) -> bool:
        """Replaces the current system with data from the specified file.

        Args:
            LensFile: The lens file.
            saveIfNeeded: if set to true the current system will be saved before loading the new one.
        """
        ...
    def MakeNonSequential(self) -> bool:
        """Makes the system non-sequential if it is not already. Note that any sequential data will be lost."""
        ...
    def MakeSequential(self) -> bool:
        """Sets the current system to sequential mode if it is not already."""
        ...
    def New(self, saveIfNeeded: bool) -> None:
        """Clears all data in the current system and resets it to a default state.

        Args:
            saveIfNeeded: if set to true the current system will be saved before it is cleared.
        """
        ...
    def Save(self) -> None:
        """Saves the current system."""
        ...
    def SaveAs(self, fileName: str) -> None:
        """Saves the current system to the specified file. All future calls to Save will use the same file.

        Args:
            fileName: Name of the file.
        """
        ...
    def TurnOffProjectDirectory(self) -> bool: ...
    def UpdateFileLists(self) -> None: ...
    def UpdateStatus(self) -> str:
        """Forces the an update of the system, and returns the current status."""
        ...

class IPreferences:
    """ZOSAPI.IPreferences"""
    @property
    def General(self) -> ZOSAPI.Preferences.IPreferencesGeneral: ...
    @property
    def Folders(self) -> ZOSAPI.Preferences.IPreferencesFolders: ...
    @property
    def IsReadOnly(self) -> bool: ...
    def ResetToDefaults(self) -> None: ...

class ISTARSubsystem:
    """ZOSAPI.ISTARSubsystem

    Controls the STAR module at the optical system level.
    """
    @property
    def UpdateMode(self) -> STARUpdateMode:
        """Gets/sets the current STAR update mode. Suspended requires manual updates using the DoManualUpdate() function."""
        ...
    @UpdateMode.setter
    def UpdateMode(self, value: STARUpdateMode) -> None: ...
    def DoManualUpdate(self) -> None:
        """Force a lens update to reflect the latest STAR configuration on all surfaces."""
        ...

class IZAPI_BaseObject:
    """ZOSAPI.IZAPI_BaseObject"""
    @property
    def Parent(self) -> IZAPI_BaseObject: ...
    def AddChild(self, child: IZAPI_BaseObject) -> None: ...
    def Disconnect(self) -> None: ...
    def RemoveChild(self, child: IZAPI_BaseObject) -> None: ...

class IZOSAPI_Application:
    """ZOSAPI.IZOSAPI_Application

    This interface contains all information about the current ZOS-API connection, as well as methods for accessing an Optical System. This interface can only be retrieved from a connection interface - IZOSAPI_Connection for more information.
    """
    @property
    def LicenseStatus(self) -> LicenseStatusType:
        """Gets the license status. Note that this displays the license edition if successful, or an error code if unsucessful."""
        ...
    @property
    def IsValidLicenseForAPI(self) -> bool:
        """Gets a value indicating whether this the API is currently useable."""
        ...
    @property
    def InitializationErrors(self) -> str:
        """Gets the initialization errors (similar to InitializationErrorCode)."""
        ...
    @property
    def InitializationErrorCode(self) -> str:
        """Gets the initialization error code for debug purposes. This should only have a value when using CreateNewApplication, and LicenseStatus is one of the errro values."""
        ...
    @property
    def Mode(self) -> ZOSAPI_Mode:
        """Gets the current connetion mode. Use this to check if Optic Studio is expecting a user operand / analysis / etc."""
        ...
    @property
    def SerialCode(self) -> str: ...
    @property
    def OpticStudioVersion(self) -> int: ...
    @property
    def ExpirationYear(self) -> int: ...
    @property
    def ExpirationMonth(self) -> int: ...
    @property
    def ExpirationDay(self) -> int: ...
    @property
    def NumberOfOpticalSystems(self) -> int:
        """Gets the current number of open optical systems. Note that there will always be at least one, the PrimarySystem."""
        ...
    @property
    def PrimarySystem(self) -> IOpticalSystem:
        """Gets the primary system. When Mode is Server, this will initially be an empty sequential system. For Plugin this will be the live optical system. For all other modes, it will be a copy of the optical system."""
        ...
    @property
    def NumberOfCPUs(self) -> int: ...
    @property
    def ProgramDir(self) -> str:
        """Gets the Program directory (e.g. C:\\Program Files\\Zemax OpticStudio)."""
        ...
    @property
    def LensDir(self) -> str:
        """Gets the Lens directory (e.g. C:\\Users\\John.Doe\\My Documents\\Zemax\\Samples). Note that this is the same as SamplesDir."""
        ...
    @property
    def ObjectsDir(self) -> str:
        """Gets the Objects directory (e.g. C:\\Users\\John.Doe\\My Documents\\Zemax\\OBJECTS)."""
        ...
    @property
    def GlassDir(self) -> str:
        """Gets the Glass directory (e.g. C:\\Users\\John.Doe\\My Documents\\Zemax\\GLASSCAT)."""
        ...
    @property
    def ZPLDir(self) -> str:
        """Gets the ZPL macros directory (e.g. C:\\Users\\John.Doe\\My Documents\\Zemax\\MACROS)."""
        ...
    @property
    def CoatingDir(self) -> str:
        """Gets the Coating directory (e.g. C:\\Users\\John.Doe\\My Documents\\Zemax\\COATINGS)."""
        ...
    @property
    def POPDir(self) -> str:
        """Gets the POP directory (e.g. C:\\Users\\John.Doe\\My Documents\\Zemax\\BEAMFILES)."""
        ...
    @property
    def ImagesDir(self) -> str:
        """Gets the Images directory (e.g. C:\\Users\\John.Doe\\My Documents\\Zemax\\IMAFILES)."""
        ...
    @property
    def SolidWorksFilesDir(self) -> str:
        """Gets the SolidWorks files directory (e.g. C:\\Users\\John.Doe\\My Documents\\Zemax\\OBJECTS\\SolidWorks Files)."""
        ...
    @property
    def AutodeskInventorFilesDir(self) -> str:
        """Gets the Autodesk Inventor files directory (e.g. C:\\Users\\John.Doe\\My Documents\\Zemax\\OBJECTS\\Inventor Files)."""
        ...
    @property
    def CreoParametricFilesDir(self) -> str:
        """Gets the Creo Parametric files directory (e.g. C:\\Users\\John.Doe\\My Documents\\Zemax\\OBJECTS\\Creo Parametric Files)."""
        ...
    @property
    def MATLABFilesDir(self) -> str:
        """Gets the MATLAB directory (e.g. C:\\Program Files\\MATLAB)."""
        ...
    @property
    def ScatterDir(self) -> str:
        """Gets the Scatter directory (e.g. C:\\Users\\John.Doe\\My Documents\\Zemax\\ScatterData)."""
        ...
    @property
    def UndoDir(self) -> str:
        """Gets the Undo directory (e.g. C:\\Users\\John.Doe\\My Documents\\Zemax\\UNDO)."""
        ...
    @property
    def SamplesDir(self) -> str:
        """Gets the full path for the current user's samples directory (in the My Documents\\Zemax\\Samples\\ folder by default)."""
        ...
    @property
    def ZemaxDataDir(self) -> str:
        """Gets the full path for the current user's Zemax directory (in the My Documents\\Zemax\\ folder by default)."""
        ...
    @property
    def OperandResults(self) -> ZOSAPI.Common.IVectorData:
        """In Operand mode, used to set the output data"""
        ...
    @property
    def OperandArgument1(self) -> float:
        """Argument 1 - Hx"""
        ...
    @property
    def OperandArgument2(self) -> float:
        """Argument 2 - Hy"""
        ...
    @property
    def OperandArgument3(self) -> float:
        """Argument 3 - Px"""
        ...
    @property
    def OperandArgument4(self) -> float:
        """Argument 4 - Py"""
        ...
    @property
    def UserAnalysisData(self) -> ZOSAPI.Analysis.IUserAnalysisData:
        """Gets the interface used to configure a User Analysis. Note that this is only available when Mode is UserAnalysis or UserAnalysisSettings."""
        ...
    @property
    def TerminateRequested(self) -> bool:
        """For a user analysis or extension, gets a value indicating if the user wishes to abort the calculation."""
        ...
    @property
    def ShowChangesInUI(self) -> bool:
        """If the Mode is Plugin, gets or sets a value indicating whether or not changes to the PrimarySystem are displayed in the OpticStudio user interface."""
        ...
    @ShowChangesInUI.setter
    def ShowChangesInUI(self, value: bool) -> None: ...
    @property
    def ProgressMessage(self) -> str:
        """If the Mode is Plugin, this controls the status message displayed in the OpticStudio progress dialog."""
        ...
    @ProgressMessage.setter
    def ProgressMessage(self, value: str) -> None: ...
    @property
    def ProgressPercent(self) -> float:
        """If the Mode is Plugin, this controls the progress percentage displayed in the OpticStudio progress dialog."""
        ...
    @ProgressPercent.setter
    def ProgressPercent(self, value: float) -> None: ...
    @property
    def CheckForUpdatesStatus(self) -> UpdateStatus:
        """Gets the check for updates status."""
        ...
    @property
    def CheckForUpdatesData(self) -> str:
        """Gets data about the newest available product."""
        ...
    @property
    def CheckForUpdatesVersion(self) -> int: ...
    @property
    def Preferences(self) -> IPreferences: ...
    @property
    def IsLoggingMessages(self) -> bool: ...
    @property
    def ZOSMajorVersion(self) -> int: ...
    @property
    def ZOSMinorVersion(self) -> int: ...
    @property
    def ZOSSPVersion(self) -> int: ...
    @property
    def IsSubscriptionLicense(self) -> bool: ...
    @property
    def IsSTARModuleEnabled(self) -> bool: ...
    def BeginMessageLogging(self) -> bool: ...
    def CheckForUpdates(self) -> None:
        """Populate the available updates status (see CheckForUpdatesStatus and CheckForUpdatesVersion)."""
        ...
    def ClearMessageLog(self) -> None: ...
    def CloseApplication(self) -> None:
        """Shut down the Optic Studio process. Note - this method only applies when running in standalone mode. Any attempt to call API members after this call successfully executes will fail."""
        ...
    def CloseSystemAt(self, pos: int, saveIfNeeded: bool) -> bool:
        """Closes the system at the specified index.

        Args:
            pos: The index for the desired system (1 to NumberOfOpticalSystems-1).
            saveIfNeeded: If set to true, the system will be saved to lens file before saving; otherwise, any changes will be lost.

        Returns:
            true if the system was closed; false otherwise.
        """
        ...
    def CopySettingsData(self, from_: ZOSAPI.Common.ISettingsData, to: ZOSAPI.Common.ISettingsData) -> bool: ...
    def CreateDataFile(self, fileName: str, type_: ZOSAPI.Tools.General.ZemaxFileTypes, data1: int, data2: int) -> ZOSAPI.Tools.General.IDataDictionary:
        """Enum parameter:
            type_ -> ZOSAPI.Tools.General.ZemaxFileTypes
        """
        ...
    def CreateNewSystem(self, mode: SystemType) -> IOpticalSystem:
        """Enum parameter:
            mode -> ZOSAPI.SystemType

        Creates a new empty optical system, in the specified mode.

        Args:
            mode: The mode, either Sequential for a sequential system, or NonSequential for a pure non-sequential file.

        Returns:
            A new, empty IOpticalSystem.
        """
        ...
    def CreateSettings(self) -> ZOSAPI.Common.ISettingsData: ...
    def CreateSettingsFromParent(self, parent: IZAPI_BaseObject) -> ZOSAPI.Common.ISettingsData: ...
    def EndMessageLogging(self) -> bool: ...
    def GetDate(self) -> str:
        """This item extracts the current date and time, in the format selected by the user in the Zemax environment dialog box.

        Returns:
            The formatted date/time
        """
        ...
    def GetSystemAt(self, pos: int) -> IOpticalSystem:
        """Gets the system at the specified index. Note that 0 will always be the same as PrimarySystem.

        Args:
            pos: The index for the desired system (0 to NumberOfOpticalSystems-1).
        """
        ...
    def LoadCCallback(self, cLib: str, callbackName: str, settings: ZOSAPI.Common.ISettingsData) -> IZOSAPI_Callback: ...
    def LoadNETCallback(self, fromAssembly: str, typeName: str, settings: ZOSAPI.Common.ISettingsData) -> IZOSAPI_Callback: ...
    def LoadNewSystem(self, LensFile: str) -> IOpticalSystem:
        """Creates a new optical system, and loads the specified lens file.

        Args:
            LensFile: The desired lens file (.ZMX file).

        Returns:
            A new IOpticalSystem if the file was successfully loaded; otherwise, null.
        """
        ...
    def OpenDataFile(self, fileName: str) -> ZOSAPI.Tools.General.IDataDictionary: ...
    def RegisterCOperandCallback(self, cLib: str, callbackName: str, settings: ZOSAPI.Common.ISettingsData) -> ZOSAPI.Analysis.IMessage: ...
    def RegisterNETOperandCallback(self, fromAssembly: str, typeName: str, settings: ZOSAPI.Common.ISettingsData) -> ZOSAPI.Analysis.IMessage: ...
    def RetrieveLogMessages(self) -> str: ...
    def RunCommand(self, command: str) -> str:
        """For internal debugging purposes only

        Args:
            command
        """
        ...
    def UpdateFileLists(self) -> None:
        """Update the cached file lists. (For example, if you've saved a 'STEP' file, you'll need to call this function before trying to use that file later in your code.)"""
        ...

class IZOSAPI_Callback:
    """ZOSAPI.IZOSAPI_Callback"""
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def IsLocal(self) -> bool: ...
    @property
    def Settings(self) -> ZOSAPI.Common.ISettingsData: ...
    @property
    def TheApp(self) -> IZOSAPI_Application: ...
    def Copy(self, app: IZOSAPI_Application) -> IZOSAPI_Callback: ...
    def Execute(self) -> int: ...

class IZOSAPI_Connection:
    """ZOSAPI.IZOSAPI_Connection

    This is the initial interface to Optic Studio. All applications that wish to use the ZOS-API must first establish a connection, using the ZOSAPI_Connection class.
    """
    @property
    def IsAlive(self) -> bool:
        """Gets a value indicating whether ZOS-API connection is still active."""
        ...
    @property
    def InitializationSettings(self) -> str:
        """For internal use only."""
        ...
    @InitializationSettings.setter
    def InitializationSettings(self, value: str) -> None: ...
    @property
    def IntializationProgress(self) -> List[int]:
        """The initialization progress can be used to help debug any initial connection problems; only applicable when using CreateNewApplication."""
        ...
    @property
    def ConnectionTimeoutSeconds(self) -> float:
        """Gets or sets the connection timeout (seconds). This is only used when launching a new OpticStudio instance, with CreateNewApplication."""
        ...
    @ConnectionTimeoutSeconds.setter
    def ConnectionTimeoutSeconds(self, value: float) -> None: ...
    @property
    def FormattingCulture(self) -> str:
        """Gets or sets the culture used when converting numeric values to/from strings. Note that this must be set before calling CreateNewApplication, and has no effect when connecting to an existing instance of OpticStudio."""
        ...
    @FormattingCulture.setter
    def FormattingCulture(self, value: str) -> None: ...
    @property
    def PreferencesFile(self) -> str:
        """For standalone ZOS-API applications, this controls the file that will be used to specify all Project Preferences settings. If no file is specified, all settings will be loaded from the OpticStudio.CFG preferences file, however any changes will not be persisted between sessions."""
        ...
    @PreferencesFile.setter
    def PreferencesFile(self, value: str) -> None: ...
    def ConnectAsExtension(self, zemaxInstance: int) -> IZOSAPI_Application:
        """Connects to an existing instance of OpticStudio in extension mode.

        Args:
            zemaxInstance: The OpticStudio instance number to connect to (0 to connect to any available instance).
        """
        ...
    def ConnectToApplication(self) -> IZOSAPI_Application:
        """Attempts to connect to Optic Studio. This will only succeed when the client application was launched by Optic Studio. Standalone applications should use CreateNewApplication."""
        ...
    def CreateNewApplication(self) -> IZOSAPI_Application:
        """Attempts to launch a new instance of Optic Studio in 'headless' mode. Note that although the Optic Studio window will not be visible, it still requires an active license. Plugins, user analyses, and user operands should instead use ConnectToApplication."""
        ...
    def CreateZemaxServer(self, applicationName: str) -> IZOSAPI_Application:
        """For internal use only

        Args:
            applicationName
        """
        ...
    def CreateZemaxServerEx(self, applicationName: str, libraryPath: str) -> IZOSAPI_Application: ...
    def GetConfigSetting(self, setting: str) -> str: ...
    def RunCommand(self, command: str) -> str:
        """For internal debugging purposes only

        Args:
            command
        """
        ...
    def SetConfigSetting(self, setting: str, Value: str) -> None: ...

class IZOSAPI_Events:
    """ZOSAPI.IZOSAPI_Events

    COM classes can inherit from this interface if they wish to receive status changed notifications. See also SystemStatusChangedEvent.
    """
    def SystemStatusChangedEvent(self, systemId: int, newStatus: str) -> None: ...

class LensUpdateMode(IntEnum):
    """ZOSAPI.LensUpdateMode"""
    None_ = 0
    EditorsOnly = 1
    AllWindows = 2

class LicenseStatusType(IntEnum):
    """ZOSAPI.LicenseStatusType"""
    Unknown = 0
    KeyNotWorking = 1
    NewLicenseNeeded = 2
    StandardEdition = 3
    ProfessionalEdition = 4
    PremiumEdition = 5
    TooManyInstances = 6
    NotAuthorized = 7
    KeyNotFound = 8
    KeyExpired = 9
    Timeout = 10
    InstanceConflict = 11
    OpticsViewer = 12
    OpticStudioHPCEdition = 13

class OpticalSystemStatusChangedHandler:
    """ZOSAPI.OpticalSystemStatusChangedHandler"""
    def __init__(self, object_: Any, method: int) -> None: ...
    def BeginInvoke(self, systemId: int, newStatus: str, callback: Any, object_: Any) -> Any: ...
    def EndInvoke(self, result: Any) -> None: ...
    def Invoke(self, systemId: int, newStatus: str) -> None: ...

class STARUpdateMode(IntEnum):
    """ZOSAPI.STARUpdateMode"""
    Normal = 0
    Suspended = 1

class SessionModes(IntEnum):
    """ZOSAPI.SessionModes"""
    FromPreferences = 0
    SessionOn = 1
    SessionOff = 2

class SystemType(IntEnum):
    """ZOSAPI.SystemType"""
    Sequential = 0
    NonSequential = 1

class UpdateStatus(IntEnum):
    """ZOSAPI.UpdateStatus"""
    CheckFailed = -2
    NotSupported = -1
    NotChecked = 0
    UpToDate = 1
    AvailableEligible = 2
    AvailableIneligible = 3

class ZOSAPI_Connection(IZOSAPI_Connection):
    """ZOSAPI.ZOSAPI_Connection"""
    def __init__(self) -> None: ...
    @property
    def TheApp(self) -> IZOSAPI_Application: ...
    @TheApp.setter
    def TheApp(self, value: IZOSAPI_Application) -> None: ...
    @property
    def IsAlive(self) -> bool: ...
    @property
    def IntializationProgress(self) -> List[int]: ...
    @property
    def ConnectionTimeoutSeconds(self) -> float: ...
    @ConnectionTimeoutSeconds.setter
    def ConnectionTimeoutSeconds(self, value: float) -> None: ...
    @property
    def InitializationSettings(self) -> str: ...
    @InitializationSettings.setter
    def InitializationSettings(self, value: str) -> None: ...
    @property
    def FormattingCulture(self) -> str: ...
    @FormattingCulture.setter
    def FormattingCulture(self, value: str) -> None: ...
    @property
    def PreferencesFile(self) -> str: ...
    @PreferencesFile.setter
    def PreferencesFile(self, value: str) -> None: ...
    SystemStatusChangedEvent: Any
    def AddInitializationProgress(self, status: int) -> None: ...
    def ConnectAsExtension(self, zemaxInstance: int) -> IZOSAPI_Application: ...
    def ConnectToApplication(self) -> IZOSAPI_Application: ...
    def CreateNewApplication(self) -> IZOSAPI_Application: ...
    def CreateZemaxServer(self, applicationName: str) -> IZOSAPI_Application: ...
    def CreateZemaxServerEx(self, applicationName: str, libraryPath: str) -> IZOSAPI_Application: ...
    def GetConfigSetting(self, setting: str) -> str: ...
    def RunCommand(self, command: str) -> str: ...
    def SetConfigSetting(self, setting: str, value: str) -> None: ...

class ZOSAPI_Mode(IntEnum):
    """ZOSAPI.ZOSAPI_Mode"""
    Server = 0
    """The connection is running in server or headless mode"""
    Operand = 1
    """User operand mode"""
    Plugin = 2
    """Extension mode"""
    UserAnalysis = 3
    """User analysis mode -- perform the calculation"""
    UserAnalysisSettings = 4
    """User analysis mode -- display/configure the analysis settings"""
