# Auto-generated by zosapi-stubgen — do not edit by hand.
# Re-run `zosapi-stubgen` to refresh after an OpticStudio upgrade.
from __future__ import annotations
from typing import (
    Any, Dict, Generic, Iterable, Iterator, List,
    Optional, overload, Sequence, Set, Tuple, TypeVar, Union,
)
from enum import IntEnum, IntFlag
from datetime import datetime, timedelta

import ZOSAPI.Common
import ZOSAPI.Editors

class IMCERow(ZOSAPI.Editors.IEditorRow):
    """ZOSAPI.Editors.MCE.IMCERow

    All data for a Multiple Configuration Editor operand. This interface can be accessed via the IMultiConfigEditor interface.
    """
    @property
    def IsActive(self) -> bool:
        """Gets a value indicating whether this instance is active (i.e. refers to a valid operand in the system)."""
        ...
    @property
    def OperandNumber(self) -> int:
        """Gets the operand number for this row."""
        ...
    @property
    def TypeName(self) -> str: ...
    @property
    def Type(self) -> MultiConfigOperandType:
        """Gets the current operand type. Use ChangeType to change the operand type."""
        ...
    @property
    def RowColor(self) -> ZOSAPI.Common.ZemaxColor: ...
    @RowColor.setter
    def RowColor(self, value: ZOSAPI.Common.ZemaxColor) -> None: ...
    @property
    def Param1(self) -> int: ...
    @Param1.setter
    def Param1(self, value: int) -> None: ...
    @property
    def Param1Enabled(self) -> bool: ...
    @property
    def Param2(self) -> int: ...
    @Param2.setter
    def Param2(self, value: int) -> None: ...
    @property
    def Param2Enabled(self) -> bool: ...
    @property
    def Param3(self) -> int: ...
    @Param3.setter
    def Param3(self, value: int) -> None: ...
    @property
    def Param3Enabled(self) -> bool: ...
    def AvailableConfigOperandTypes(self) -> List[MultiConfigOperandType]: ...
    def ChangeType(self, type_: MultiConfigOperandType) -> bool:
        """Enum parameter:
            type_ -> ZOSAPI.Editors.MCE.MultiConfigOperandType

        Changes to the specified operand type.

        Args:
            type: The type.

        Returns:
            true if the change was successful; otherwise, false.
        """
        ...
    def GetOperandCell(self, configuration: int) -> ZOSAPI.Editors.IEditorCell:
        """Gets the specified operand cell data.

        Args:
            configuration: The configuration.
        """
        ...

class IMultiConfigEditor(ZOSAPI.Editors.IEditor):
    """ZOSAPI.Editors.MCE.IMultiConfigEditor

    This interface defines all properties and methods needed to interact with the Multiple Configuration Editor. This interface can be accessed via the IOpticalSystem interface.
    """
    @property
    def RowToOperandOffset(self) -> int:
        """Offset from a row index to operand index (always 1)."""
        ...
    @property
    def NumberOfOperands(self) -> int:
        """Gets the total number of operands in the current system."""
        ...
    @property
    def FirstConfiguration(self) -> int:
        """Gets the first configuration number."""
        ...
    @property
    def LastConfiguration(self) -> int:
        """Gets the last configuration number."""
        ...
    @property
    def NumberOfConfigurations(self) -> int:
        """Gets the total number of configurations."""
        ...
    @property
    def CurrentConfiguration(self) -> int:
        """Gets the current configuration number."""
        ...
    def AddConfiguration(self, withPickups: bool) -> bool:
        """Adds a new, last configuration.

        Args:
            withPickups: if set to true add pickups from the previous configuration.
        """
        ...
    def AddOperand(self) -> IMCERow:
        """Adds a new operand to the end of the editor."""
        ...
    def CopyOperands(self, fromOperandNumber: int, NumberOfOperands: int, toOperandNumber: int) -> int:
        """Copy and paste the specified number of operands from one location to another. Note that it is okay for the source and destination to overlap.

        Args:
            fromOperandNumber: First operand number to copy (1 to NumberOfOperands).
            NumberOfOperands: The number of operands to copy.
            toOperandNumber: Row to start inserting the operands (1 to NumberOfOperands+1).

        Returns:
            The number of operands actually copied.
        """
        ...
    def CopyOperandsFrom(self, fromEditor: IMultiConfigEditor, fromOperandNumber: int, NumberOfOperands: int, toOperandNumber: int) -> int:
        """Copy and paste the specified number of operands from one location (in the specified system) to another location (in this system). Note that it is okay for the source and destination to overlap.

        Args:
            fromEditor: System to copy the operands from. Note that the NumberOfConfigurations must the same as the current system.
            fromOperandNumber: First operand number to copy (1 to NumberOfOperands).
            NumberOfOperands: The number of operands to copy.
            toOperandNumber: To operand number (1 to NumberOfOperands+1).

        Returns:
            The number of operands actually copied.
        """
        ...
    def DeleteAllConfigurations(self) -> bool:
        """Deletes all but one configuration from the system."""
        ...
    def DeleteConfiguration(self, ConfigurationNumber: int) -> bool:
        """Deletes the specified configuration (1 to NumberOfConfigurations).

        Args:
            ConfigurationNumber: The configuration to delete.
        """
        ...
    def GetOperandAt(self, OperandNumber: int) -> IMCERow:
        """Gets the specified operand data.

        Args:
            OperandNumber: The operand number (1 to NumberOfOperands).
        """
        ...
    def HideMCE(self) -> None:
        """Closes this editor in the UI. Note that this only has an effect if the Mode is Plugin."""
        ...
    def InsertConfiguration(self, ConfigurationNumber: int, withPickups: bool) -> bool:
        """Inserts a new configuration at the specified index, optionally with pickups.

        Args:
            ConfigurationNumber: The configuration number to insert at (1 to NumberOfConfigurations+1).
            withPickups: If set to true the next configuration will pickup values from the inserted configuration.
        """
        ...
    def InsertNewOperandAt(self, OperandNumber: int) -> IMCERow:
        """Inserts the a new operand at the specified location.

        Args:
            OperandNumber: The operand number (1 to NumberOfOperands+1).
        """
        ...
    def MakeSingleConfiguration(self) -> None:
        """Removes all configurations and operands. Note that this is the same as MakeSingleConfigurationOpt with an argument of false."""
        ...
    def MakeSingleConfigurationOpt(self, deleteMFEOperands: bool) -> None:
        """Removes all configurations and operands.

        Args:
            deleteMFEOperands: if set to true merit function operands for delete configurations will be removed, else MFE operands will remain.
        """
        ...
    def NextConfiguration(self) -> bool:
        """Changes to the next configuration.

        Returns:
            true if there is another available configuration; otherwise, false.
        """
        ...
    def PrevConfiguration(self) -> bool:
        """Changes to the previous configuration.

        Returns:
            true if there is another available configuration; otherwise, false.
        """
        ...
    def RemoveOperandAt(self, OperandNumber: int) -> bool:
        """Removes the specified operand.

        Args:
            OperandNumber: The operand number (1 to NumberOfOperands).
        """
        ...
    def RemoveOperandsAt(self, OperandNumber: int, numOperands: int) -> int:
        """Removes one or more operands at the specified position.

        Args:
            OperandNumber: The starting operand number (1 to NumberOfOperands).
            numOperands: The number of operands to remove.
        """
        ...
    def RunTool_MakeThermal(self, existingConfigurationIndex: int, numberOfThemalConfigs: int, minTemp: float, maxTemp: float, sortBySurface: bool) -> None:
        """Args:
            existingConfigurationIndex
            numberOfThemalConfigs
            minTemp
            maxTemp
            sortBySurface
        """
        ...
    def SetCurrentConfiguration(self, ConfigurationNumber: int) -> bool:
        """Sets the currently active configuration for the system (1 to NumberOfConfigurations).

        Args:
            ConfigurationNumber: The configuration number.

        Returns:
            true if the configuration was successfully changed; otherwise, false.
        """
        ...
    def ShowMCE(self) -> bool:
        """Shows this editor in the UI. Note that this only has an effect if the Mode is Plugin."""
        ...

class MultiConfigOperandType(IntEnum):
    """ZOSAPI.Editors.MCE.MultiConfigOperandType

    All supported Multi Configuration operand types
    """
    MOFF = 0
    AICN = 1
    AFOC = 2
    APDF = 3
    APDT = 4
    APDX = 5
    APDY = 6
    APER = 7
    APMN = 8
    APMX = 9
    APTP = 10
    CADX = 11
    CADY = 12
    CAOR = 13
    CATX = 14
    CATY = 15
    CATZ = 16
    CBDX = 17
    CBDY = 18
    CBOR = 19
    CBTX = 20
    CBTY = 21
    CBTZ = 22
    CONN = 23
    COTN = 24
    CPCN = 25
    CROR = 26
    CRSR = 27
    CRVT = 28
    CSP1 = 29
    CSP2 = 30
    CWGT = 31
    EDVA = 32
    FLTP = 33
    FLWT = 34
    FVAN = 35
    FVCX = 36
    FVCY = 37
    FVDX = 38
    FVDY = 39
    GCRS = 40
    GLSS = 41
    GPEX = 42
    GPEY = 43
    GPIU = 44
    GPJX = 45
    GPJY = 46
    GPPX = 47
    GPPY = 48
    GQPO = 49
    HOLD = 50
    IGNM = 51
    IGNR = 52
    LTTL = 53
    MABB = 54
    MCOM = 55
    MDPG = 56
    MIND = 57
    MTFU = 58
    NCOM = 59
    NCOT = 60
    NGLS = 61
    NPAR = 62
    NPOS = 63
    NPRO = 64
    PAR1 = 65
    PAR2 = 66
    PAR3 = 67
    PAR4 = 68
    PAR5 = 69
    PAR6 = 70
    PAR7 = 71
    PAR8 = 72
    PRAM = 73
    PRES = 74
    PRWV = 75
    PSCX = 76
    PSCY = 77
    PSHX = 78
    PSHY = 79
    PSHZ = 80
    PSP1 = 81
    PSP2 = 82
    PSP3 = 83
    PUCN = 84
    PXAR = 85
    RAAM = 86
    SATP = 87
    SDIA = 88
    SDRW = 89
    STPS = 90
    SWCN = 91
    TCEX = 92
    TELE = 93
    TEMP = 94
    THIC = 95
    TSP1 = 96
    TSP2 = 97
    TSP3 = 98
    UDAF = 99
    WAVE = 100
    WLWT = 101
    XFIE = 102
    YFIE = 103
    OPDR = 104
    SRTS = 105
    MCHI = 106
    IGTO = 107
    FTAN = 108
    FCMM = 109
    CHZN = 110
    MCSD = 111
