# Auto-generated by zosapi-stubgen — do not edit by hand.
# Re-run `zosapi-stubgen` to refresh after an OpticStudio upgrade.
from __future__ import annotations
from typing import (
    Any, Dict, Generic, Iterable, Iterator, List,
    Optional, overload, Sequence, Set, Tuple, TypeVar, Union,
)
from enum import IntEnum, IntFlag
from datetime import datetime, timedelta

class ICoordinateTransform:
    """ZOSAPI.Common.ICoordinateTransform"""
    @property
    def HasOffset(self) -> bool: ...
    @property
    def XOffset(self) -> float: ...
    @XOffset.setter
    def XOffset(self, value: float) -> None: ...
    @property
    def YOffset(self) -> float: ...
    @YOffset.setter
    def YOffset(self, value: float) -> None: ...
    @property
    def ZOffset(self) -> float: ...
    @ZOffset.setter
    def ZOffset(self, value: float) -> None: ...
    @property
    def HasRotation(self) -> bool: ...
    @property
    def R11(self) -> float: ...
    @R11.setter
    def R11(self, value: float) -> None: ...
    @property
    def R12(self) -> float: ...
    @R12.setter
    def R12(self, value: float) -> None: ...
    @property
    def R13(self) -> float: ...
    @R13.setter
    def R13(self, value: float) -> None: ...
    @property
    def R21(self) -> float: ...
    @R21.setter
    def R21(self, value: float) -> None: ...
    @property
    def R22(self) -> float: ...
    @R22.setter
    def R22(self, value: float) -> None: ...
    @property
    def R23(self) -> float: ...
    @R23.setter
    def R23(self, value: float) -> None: ...
    @property
    def R31(self) -> float: ...
    @R31.setter
    def R31(self, value: float) -> None: ...
    @property
    def R32(self) -> float: ...
    @R32.setter
    def R32(self, value: float) -> None: ...
    @property
    def R33(self) -> float: ...
    @R33.setter
    def R33(self, value: float) -> None: ...
    @property
    def RotationAnglesSpecified(self) -> bool: ...
    @RotationAnglesSpecified.setter
    def RotationAnglesSpecified(self, value: bool) -> None: ...
    @property
    def ThetaX(self) -> float: ...
    @ThetaX.setter
    def ThetaX(self, value: float) -> None: ...
    @property
    def ThetaY(self) -> float: ...
    @ThetaY.setter
    def ThetaY(self, value: float) -> None: ...
    @property
    def ThetaZ(self) -> float: ...
    @ThetaZ.setter
    def ThetaZ(self, value: float) -> None: ...
    def GetAngleSet(self) -> List[float]: ...
    def GetDecenterVector(self) -> List[float]: ...
    def GetMatrix_3x3(self) -> List[float]: ...
    def GetMatrix_4x4(self) -> List[float]: ...

class IMatrixData:
    """ZOSAPI.Common.IMatrixData

    Methods and properties for retrieving and/or setting a 2D array of double precision data.
    """
    @property
    def IsReadOnly(self) -> bool:
        """Gets a value indicating whether the data in this matrix can be modified."""
        ...
    @property
    def Rows(self) -> int:
        """Gets the number of rows in the 2D array."""
        ...
    @property
    def Cols(self) -> int:
        """Gets the number of cols in the 2D array."""
        ...
    @property
    def TotalLength(self) -> int:
        """Gets the total size of the 2D array (Rows * Cols)."""
        ...
    @property
    def Data(self) -> List[float]:
        """Gets or sets (if IsReadOnly is false) the data. Note that making changes to the returned array does not change the underlying data source. Use this property to replace the entire data, or use WriteData to update the data source."""
        ...
    @Data.setter
    def Data(self, value: List[float]) -> None: ...
    def GetValueAt(self, Row: int, Col: int) -> float:
        """Retrieves a single value from the 2D array. Note that accessing the data one element at a time may be much slower than retrieving the entire array at once.

        Args:
            Row: The row.
            Col: The col.
        """
        ...
    def ReadData(self, Size: int) -> List[float]:
        """Retrieve the entire data set. This method is functionally identical to using Data, however it may be easier to use from some languages.

        Args:
            Size: The size of the input array -- this must be the same as TotalLength.
            Data: The array to fill. Note that this must be allocated prior to calling ReadData.
        """
        ...
    def SetValueAt(self, Row: int, Col: int, Value: float) -> None:
        """Set a single value from the 2D array. Note that accessing the data one element at a time may be much slower than updating the entire array at once.

        Args:
            Row: The row.
            Col: The col.
            Value: The value.
        """
        ...
    def WriteData(self, Size: int, Data: List[float]) -> None:
        """Update the entire data set. This method is functionally identical to using Data, however it may be easier to use from some languages. Note that calling this method will have no effect if IsReadOnly is true.

        Args:
            Size: The size of the input array.
            Data: The new array data.
        """
        ...

class ISettingsData:
    """ZOSAPI.Common.ISettingsData

    Methods and interfaces for storing and retrieving user-defined settings. All settings are referenced via a user-defined string key, and has a specific type associated with it (e.g. a single integer, array of doubles, etc.).
    """
    @property
    def NumberOfSettings(self) -> int:
        """Gets the total number of settings currently stored via the API."""
        ...
    def GetBooleanArray(self, key: str, Size: int) -> Tuple[bool, List[bool]]: ...
    def GetBooleanValue(self, key: str) -> Tuple[bool, bool]: ...
    def GetByteArray(self, key: str, Size: int) -> Tuple[bool, List[int]]: ...
    def GetByteValue(self, key: str) -> Tuple[bool, int]: ...
    def GetDoubleArray(self, key: str, Size: int) -> Tuple[bool, List[float]]: ...
    def GetDoubleValue(self, key: str) -> Tuple[bool, float]: ...
    def GetEntryType(self, key: str) -> Tuple[bool, SettingsDataType, bool, int]:
        """Gets information about the data associated with the specified key.

        Args:
            key: The key.
            type: The of data associated with the key.
            isArray: If set to true, the data is stored as an array of SettingsDataType.
            arraySize: The number of elements of the array, or 1 if it is a single element.

        Returns:
            true if the key exists; otherwise, false.
        """
        ...
    def GetFloatArray(self, key: str, Size: int) -> Tuple[bool, List[float]]: ...
    def GetFloatValue(self, key: str) -> Tuple[bool, float]: ...
    def GetIntegerArray(self, key: str, Size: int) -> Tuple[bool, List[int]]: ...
    def GetIntegerValue(self, key: str) -> Tuple[bool, int]: ...
    def GetKeys(self) -> List[str]:
        """Gets an array of all keys currently stored."""
        ...
    def GetStringValue(self, key: str) -> Tuple[bool, str]: ...
    def SetBooleanArray(self, key: str, Size: int, val: List[bool]) -> None: ...
    def SetBooleanValue(self, key: str, val: bool) -> None: ...
    def SetByteArray(self, key: str, Size: int, val: List[int]) -> None: ...
    def SetByteValue(self, key: str, val: int) -> None: ...
    def SetDoubleArray(self, key: str, Size: int, val: List[float]) -> None: ...
    def SetDoubleValue(self, key: str, val: float) -> None: ...
    def SetFloatArray(self, key: str, Size: int, val: List[float]) -> None: ...
    def SetFloatValue(self, key: str, val: float) -> None: ...
    def SetIntegerArray(self, key: str, Size: int, val: List[int]) -> None: ...
    def SetIntegerValue(self, key: str, val: int) -> None: ...
    def SetStringValue(self, key: str, val: str) -> None: ...

class IVectorData:
    """ZOSAPI.Common.IVectorData

    Methods and properties for retrieving and/or setting a 1D array of double precision data.
    """
    @property
    def IsReadOnly(self) -> bool:
        """Gets a value indicating whether the data in this vector can be modified."""
        ...
    @property
    def Length(self) -> int:
        """Gets the length of this data vector."""
        ...
    @property
    def Data(self) -> List[float]:
        """Gets or sets the data for this vector."""
        ...
    @Data.setter
    def Data(self, value: List[float]) -> None: ...
    def GetValueAt(self, position: int) -> float:
        """Gets the value at the specified index. Note that this may be much slower than retrieving all of the data at once via the Data property or ReadData method.

        Args:
            position: The position (0 to Length-1).
        """
        ...
    def ReadData(self, Size: int) -> List[float]:
        """Populates the specified array with the data vector. Note that this is the same as using the Data property, however it may be easier to use for COM-based clients.

        Args:
            Size: The size of the input array.
            Data: The array to fill.
        """
        ...
    def SetValueAt(self, position: int, Value: float) -> None:
        """Sets the value at the specified position. Note that this may be much slower than setting all of the data at once via the Data property or WriteData method.

        Args:
            position: The position (0 to Length-1).
            Value: The new value.
        """
        ...
    def WriteData(self, Size: int, Data: List[float]) -> None:
        """Stores the specified array in the vector. Note that this is the same as using the Data property, however it may be easier to use for COM-based clients. This method will not do anything if IsReadOnly is true.

        Args:
            Size: The size of the input array.
            Data: The data to store.
        """
        ...

class SettingsDataType(IntEnum):
    """ZOSAPI.Common.SettingsDataType"""
    None_ = 0
    Integer = 1
    Double = 2
    Float = 3
    String = 4
    Byte = 5
    Boolean = 6

class ZemaxColor(IntEnum):
    """ZOSAPI.Common.ZemaxColor"""
    Default = 0
    Color1 = 1
    Color2 = 2
    Color3 = 3
    Color4 = 4
    Color5 = 5
    Color6 = 6
    Color7 = 7
    Color8 = 8
    Color9 = 9
    Color10 = 10
    Color11 = 11
    Color12 = 12
    Color13 = 13
    Color14 = 14
    Color15 = 15
    Color16 = 16
    Color17 = 17
    Color18 = 18
    Color19 = 19
    Color20 = 20
    Color21 = 21
    Color22 = 22
    Color23 = 23
    Color24 = 24

class ZemaxOpacity(IntEnum):
    """ZOSAPI.Common.ZemaxOpacity"""
    P100 = 0
    P90 = 1
    P80 = 2
    P70 = 3
    P60 = 4
    P50 = 5
    P40 = 6
    P30 = 7
    P20 = 8
    P10 = 9
    P00 = 10
