# Auto-generated by zosapi-stubgen — do not edit by hand.
# Re-run `zosapi-stubgen` to refresh after an OpticStudio upgrade.
from __future__ import annotations
from typing import (
    Any, Dict, Generic, Iterable, Iterator, List,
    Optional, overload, Sequence, Set, Tuple, TypeVar, Union,
)
from enum import IntEnum, IntFlag
from datetime import datetime, timedelta

import ZOSAPI.Analysis.Settings

class IAS_PathAnalysis(ZOSAPI.Analysis.Settings.IAS_):
    """ZOSAPI.Analysis.RayTracing.IAS_PathAnalysis"""
    @property
    def RayDatabaseFile(self) -> str: ...
    @RayDatabaseFile.setter
    def RayDatabaseFile(self, value: str) -> None: ...
    @property
    def AvailableRayDatabaseFiles(self) -> List[str]: ...
    @property
    def FirstRay(self) -> int: ...
    @FirstRay.setter
    def FirstRay(self, value: int) -> None: ...
    @property
    def LastRay(self) -> int: ...
    @LastRay.setter
    def LastRay(self, value: int) -> None: ...
    @property
    def FilterString(self) -> str: ...
    @FilterString.setter
    def FilterString(self, value: str) -> None: ...
    @property
    def GeneratePathFilters(self) -> bool: ...
    @GeneratePathFilters.setter
    def GeneratePathFilters(self, value: bool) -> None: ...
    @property
    def RelativeMinimumFlux(self) -> float: ...
    @RelativeMinimumFlux.setter
    def RelativeMinimumFlux(self, value: float) -> None: ...
    @property
    def SortBy(self) -> PathAnalysisSortType: ...
    @SortBy.setter
    def SortBy(self, value: PathAnalysisSortType) -> None: ...

class PathAnalysisSortType(IntEnum):
    """ZOSAPI.Analysis.RayTracing.PathAnalysisSortType"""
    TotalEndingFlux = 0
    NumberOfObjectsStruck = 1
    NumberOfBranches = 2
    LastObjectStruck = 3
    NumberOfUniqueObjectsStruct = 4
