# Auto-generated by zosapi-stubgen — do not edit by hand.
# Re-run `zosapi-stubgen` to refresh after an OpticStudio upgrade.
from __future__ import annotations
from typing import (
    Any, Dict, Generic, Iterable, Iterator, List,
    Optional, overload, Sequence, Set, Tuple, TypeVar, Union,
)
from enum import IntEnum, IntFlag
from datetime import datetime, timedelta

import ZOSAPI.Editors.LDE
import ZOSAPI.Editors.NCE
import ZOSAPI.SystemData

from . import LDE as LDE
from . import MCE as MCE
from . import MFE as MFE
from . import NCE as NCE
from . import TDE as TDE

class CellDataType(IntEnum):
    """ZOSAPI.Editors.CellDataType"""
    Integer = 0
    Double = 1
    String = 2

class EditorType(IntEnum):
    """ZOSAPI.Editors.EditorType"""
    LDE = 0
    """Lens Data Editor"""
    NCE = 1
    """Non-sequential Component Editor"""
    MFE = 2
    """Merit Function Editor"""
    TDE = 3
    """Tolerance Data Editor"""
    MCE = 4
    """Multiple Configuration Editor"""

class IEditor:
    """ZOSAPI.Editors.IEditor

    Base interface for all five editor types. All editors can be accessed via the IOpticalSystem interface. Note that this interface can be used to retrieve basic editor information only. For more detailed data, you should use one of the editor-specific interfaces: IOpticalSystem.LDE IOpticalSystem.NCE IOpticalSystem.MFE IOpticalSystem.MCE IOpticalSystem.TDE
    """
    @property
    def Editor(self) -> EditorType:
        """Gets the type of this editor instance."""
        ...
    @property
    def NumberOfRows(self) -> int:
        """Gets the number of rows in this editor. Note that this referes to surfaces, objects, or operands depending on editor type."""
        ...
    @property
    def MinColumn(self) -> int:
        """The minimum column index that can be used in calls to GetCellAt for any IEditorRow retrieved from this editor."""
        ...
    @property
    def MaxColumn(self) -> int:
        """The maximum column index that can be used in calls to GetCellAt for any IEditorRow retrieved from this editor."""
        ...
    def AddRow(self) -> IEditorRow:
        """Adds a new row at the end of the editor.

        Returns:
            The newly added row.
        """
        ...
    def DeleteAllRows(self) -> int:
        """Deletes all rows from the current editor.

        Returns:
            The number of rows successfully removed.
        """
        ...
    def DeleteRowAt(self, pos: int) -> bool:
        """Deletes a row at the specified index (0 to NumberOfRows-1). Note that all editors require at least one row, and some editors may require more than that.

        Args:
            pos: The index of the row to remove.

        Returns:
            true if the specified row was removed; otherwise, false.
        """
        ...
    def DeleteRowsAt(self, pos: int, numberOfRows: int) -> int:
        """Deletes one or more rows at the specified index (0 to NumberOfRows-1).

        Args:
            pos: The index of the first row to remove.
            numberOfRows: The number of rows to remove.

        Returns:
            The number of rows removed from the editor.
        """
        ...
    def GetRowAt(self, pos: int) -> IEditorRow:
        """Gets the row at the specified index (0 to NumberOfRows-1).

        Args:
            pos: The row index.
        """
        ...
    def HideEditor(self) -> None:
        """Closes this editor in the UI. Note that this only has an effect if the Mode is Plugin."""
        ...
    def InsertRowAt(self, pos: int) -> IEditorRow:
        """Inserts a new row at the specified index (0 to NumberOfRows). Note that some editors - such as the Lens Data Editor may not allow inserting new rows before the first row.

        Args:
            pos: The new row index.

        Returns:
            The new row if successful; otherwise null.
        """
        ...
    def ShowEditor(self) -> bool:
        """Shows this editor in the UI. Note that this only has an effect if the Mode is Plugin."""
        ...

class IEditorCell:
    """ZOSAPI.Editors.IEditorCell

    Interface used to get and set data for a specific cell in an editor. This interface can be accessed via: IEditorRow ILDERow INCERow IMCERow IMFERow ITDERow
    """
    @property
    def Row(self) -> IEditorRow:
        """Gets the parent row for this cell."""
        ...
    @property
    def Col(self) -> int:
        """Gets the column index for this cell."""
        ...
    @property
    def IsActive(self) -> bool:
        """Gets a value indicating whether this cell is currently active (i.e. in use by the current system)."""
        ...
    @property
    def IsReadOnly(self) -> bool:
        """Gets a value indicating whether this cell can be modified."""
        ...
    @property
    def Header(self) -> str:
        """Gets the column header for this cell."""
        ...
    @property
    def DataType(self) -> CellDataType:
        """Gets the data type of this cell."""
        ...
    @property
    def IntegerValue(self) -> int:
        """Gets or sets the integer value of this cell. Note that if DataType is not Integer, attempting to get or set a value in this way will result in an exception."""
        ...
    @IntegerValue.setter
    def IntegerValue(self, value: int) -> None: ...
    @property
    def DoubleValue(self) -> float:
        """Gets or sets the double precision value of this cell. Note that if DataType is not Double, attempting to get or set a value in this way will result in an exception."""
        ...
    @DoubleValue.setter
    def DoubleValue(self, value: float) -> None: ...
    @property
    def Value(self) -> str:
        """Gets or sets the value of this cell. Note that this method can be used regardless of the DataType."""
        ...
    @Value.setter
    def Value(self, value: str) -> None: ...
    @property
    def Solve(self) -> SolveType:
        """Gets the type of the current solve."""
        ...
    def CreateSolveType(self, type_: SolveType) -> ISolveData:
        """Enum parameter:
            type_ -> ZOSAPI.Editors.SolveType

        Creates the solve type settings for the specified solve type. Note that SetSolveData must be used to actually update the system with the solve settings.

        Args:
            type: The solve type.
        """
        ...
    def FillAvailableSolveTypes(self, Length: int) -> List[SolveType]:
        """Alternate method of retrieving available cell types, accessible via COM.

        Args:
            Length: The length of the input array (must be equal to GetNumberOfSolveTypes.
            solves: The solve type array to fill. Note that this must be allocated before calling this method.
        """
        ...
    def GetAvailableSolveTypes(self) -> List[SolveType]:
        """Gets the available solve types for this cell."""
        ...
    def GetNumberOfSolveTypes(self) -> int:
        """Gets the number of solve types allowed for this specific editor cell."""
        ...
    def GetSolveData(self) -> ISolveData:
        """Gets the current solve data. Use CreateSolveType to retrieve an interface that can be used to change the solve type. Note that the solve will not be updated until SetSolveData is called with the new settings."""
        ...
    def IsSolveTypeSupported(self, st: SolveType) -> bool:
        """Enum parameter:
            st -> ZOSAPI.Editors.SolveType

        Determines whether the specified solve type is supported by this specific cell.

        Args:
            st: The solve type.

        Returns:
            true if the input solve type can be used; otherwise false.
        """
        ...
    def MakeSolveFixed(self) -> bool:
        """Sets the solve type to Fixed.

        Returns:
            true if the change succeeded; otherwise, false
        """
        ...
    def MakeSolveVariable(self) -> bool:
        """Sets the solve type to Variable.

        Returns:
            true if the change succeeded; otherwise, false
        """
        ...
    def SetSolveData(self, Data: ISolveData) -> SolveStatus:
        """Updates the system with the new solve type settings (see also CreateSolveType and GetSolveData).

        Args:
            Data: The new solve settings.

        Returns:
            A value indicating whether or not changing the solve settings was successful.
        """
        ...

class IEditorRow:
    """ZOSAPI.Editors.IEditorRow

    Base interface for all five editor row types. General row information can be accessed via the IEditor interface. Note that this interface can be used to retrieve basic editor information only. For more detailed data, you should use one of the editor-specific interfaces: ILDERow (from GetSurfaceAt) INCERow (from GetObjectAt) IMFERow (from GetOperandAt) ITDERow (from GetOperandAt) IMCERow (from GetOperandAt)
    """
    @property
    def Editor(self) -> IEditor:
        """Gets the editor this row was retrieved from."""
        ...
    @property
    def IsValidRow(self) -> bool:
        """Gets a value indicating whether this instance is currently valid. Note that the RowIndex for this object is fixed, so removing one or more rows from the editor may cause it to be invalid."""
        ...
    @property
    def RowIndex(self) -> int:
        """Gets the index of this row in the editor."""
        ...
    @property
    def RowTypeName(self) -> str:
        """Gets the type of this row; this can be a surface for the LDE, object for the NCE, etc."""
        ...
    @property
    def Bookmark(self) -> str: ...
    @Bookmark.setter
    def Bookmark(self, value: str) -> None: ...
    def GetCellAt(self, pos: int) -> IEditorCell:
        """Gets the cell at the specified index (MinColumn to MaxColumn).

        Args:
            pos: The index of the cell to retrieve.
        """
        ...

class ISolveAplanatic(ISolveData):
    """ZOSAPI.Editors.ISolveAplanatic"""
    ...

class ISolveAutomatic(ISolveData):
    """ZOSAPI.Editors.ISolveAutomatic"""
    ...

class ISolveCenterOfCurvature(ISolveData):
    """ZOSAPI.Editors.ISolveCenterOfCurvature"""
    @property
    def RefSurface(self) -> int: ...
    @RefSurface.setter
    def RefSurface(self, value: int) -> None: ...

class ISolveChiefRayAngle(ISolveData):
    """ZOSAPI.Editors.ISolveChiefRayAngle"""
    @property
    def Angle(self) -> float: ...
    @Angle.setter
    def Angle(self, value: float) -> None: ...

class ISolveChiefRayHeight(ISolveData):
    """ZOSAPI.Editors.ISolveChiefRayHeight"""
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> None: ...

class ISolveChiefRayNormal(ISolveData):
    """ZOSAPI.Editors.ISolveChiefRayNormal"""
    ...

class ISolveCocentricRadius(ISolveData):
    """ZOSAPI.Editors.ISolveCocentricRadius"""
    @property
    def WithSurface(self) -> int: ...
    @WithSurface.setter
    def WithSurface(self, value: int) -> None: ...

class ISolveCocentricSurface(ISolveData):
    """ZOSAPI.Editors.ISolveCocentricSurface"""
    @property
    def AboutSurface(self) -> int: ...
    @AboutSurface.setter
    def AboutSurface(self, value: int) -> None: ...

class ISolveCompensator(ISolveData):
    """ZOSAPI.Editors.ISolveCompensator"""
    @property
    def RefSurface(self) -> int: ...
    @RefSurface.setter
    def RefSurface(self, value: int) -> None: ...
    @property
    def Sum(self) -> float: ...
    @Sum.setter
    def Sum(self, value: float) -> None: ...

class ISolveConfigPickup(ISolveData):
    """ZOSAPI.Editors.ISolveConfigPickup"""
    @property
    def Operand(self) -> int:
        """Gets or sets the multi-config operand to pickup from."""
        ...
    @Operand.setter
    def Operand(self, value: int) -> None: ...
    @property
    def ScaleFactor(self) -> float: ...
    @ScaleFactor.setter
    def ScaleFactor(self, value: float) -> None: ...
    @property
    def SupportsScale(self) -> bool: ...
    @property
    def Offset(self) -> float: ...
    @Offset.setter
    def Offset(self, value: float) -> None: ...
    @property
    def Configuration(self) -> int:
        """Gets or sets the configuration number to pickup from."""
        ...
    @Configuration.setter
    def Configuration(self, value: int) -> None: ...
    @property
    def SupportsOffset(self) -> bool: ...

class ISolveData:
    """ZOSAPI.Editors.ISolveData

    Base interface for all solve types. This interface can be accesed via the IEditorCell interface. Note that the _S_ properties are for convenience only and merely cast this interface to the appropriate derived interface. See the OpticStudio documentation for details on the various solve types.
    """
    @property
    def IsValid(self) -> bool:
        """Gets a value indicating whether the current solve settings are valid."""
        ...
    @property
    def Type(self) -> SolveType:
        """The solve type for this instance."""
        ...
    @property
    def _S_None(self) -> ISolveNone: ...
    @property
    def _S_Fixed(self) -> ISolveFixed: ...
    @property
    def _S_Variable(self) -> ISolveVariable: ...
    @property
    def _S_SurfacePickup(self) -> ISolveSurfacePickup: ...
    @property
    def _S_ZPLMacro(self) -> ISolveZPLMacro: ...
    @property
    def _S_MarginalRayAngle(self) -> ISolveMarginalRayAngle: ...
    @property
    def _S_MarginalRayHeight(self) -> ISolveMarginalRayHeight: ...
    @property
    def _S_ChiefRayAngle(self) -> ISolveChiefRayAngle: ...
    @property
    def _S_MarginalRayNormal(self) -> ISolveMarginalRayNormal: ...
    @property
    def _S_ChiefRayNormal(self) -> ISolveChiefRayNormal: ...
    @property
    def _S_Aplanatic(self) -> ISolveAplanatic: ...
    @property
    def _S_ElementPower(self) -> ISolveElementPower: ...
    @property
    def _S_CocentricSurface(self) -> ISolveCocentricSurface: ...
    @property
    def _S_CocentricRadius(self) -> ISolveCocentricRadius: ...
    @property
    def _S_FNumber(self) -> ISolveFNumber: ...
    @property
    def _S_ChiefRayHeight(self) -> ISolveChiefRayHeight: ...
    @property
    def _S_EdgeThickness(self) -> ISolveEdgeThickness: ...
    @property
    def _S_OpticalPathDifference(self) -> ISolveOpticalPathDifference: ...
    @property
    def _S_Position(self) -> ISolvePosition: ...
    @property
    def _S_Compensator(self) -> ISolveCompensator: ...
    @property
    def _S_CenterOfCurvature(self) -> ISolveCenterOfCurvature: ...
    @property
    def _S_PupilPosition(self) -> ISolvePupilPosition: ...
    @property
    def _S_MaterialModel(self) -> ISolveMaterialModel: ...
    @property
    def _S_MaterialSubstitute(self) -> ISolveMaterialSubstitute: ...
    @property
    def _S_MaterialOffset(self) -> ISolveMaterialOffset: ...
    @property
    def _S_Automatic(self) -> ISolveAutomatic: ...
    @property
    def _S_Maximum(self) -> ISolveMaximum: ...
    @property
    def _S_PickupChiefRay(self) -> ISolvePickupChiefRay: ...
    @property
    def _S_ObjectPickup(self) -> ISolveObjectPickup: ...
    @property
    def _S_ConfigPickup(self) -> ISolveConfigPickup: ...
    @property
    def _S_ThermalPickup(self) -> ISolveThermalPickup: ...
    @property
    def _S_FieldPickup(self) -> ISolveFieldPickup: ...
    @property
    def _S_DuplicateSag(self) -> ISolveDuplicateSag: ...
    @property
    def _S_InvertSag(self) -> ISolveInvertSag: ...

class ISolveDuplicateSag:
    """ZOSAPI.Editors.ISolveDuplicateSag"""
    @property
    def Surface(self) -> int: ...
    @Surface.setter
    def Surface(self, value: int) -> None: ...

class ISolveEdgeThickness(ISolveData):
    """ZOSAPI.Editors.ISolveEdgeThickness"""
    @property
    def Thickness(self) -> float: ...
    @Thickness.setter
    def Thickness(self, value: float) -> None: ...
    @property
    def RadialHeight(self) -> float: ...
    @RadialHeight.setter
    def RadialHeight(self, value: float) -> None: ...

class ISolveElementPower(ISolveData):
    """ZOSAPI.Editors.ISolveElementPower"""
    @property
    def Power(self) -> float: ...
    @Power.setter
    def Power(self, value: float) -> None: ...

class ISolveFNumber(ISolveData):
    """ZOSAPI.Editors.ISolveFNumber"""
    @property
    def FNumber(self) -> float: ...
    @FNumber.setter
    def FNumber(self, value: float) -> None: ...

class ISolveFieldPickup(ISolveData):
    """ZOSAPI.Editors.ISolveFieldPickup"""
    @property
    def Field(self) -> int: ...
    @Field.setter
    def Field(self, value: int) -> None: ...
    @property
    def ScaleFactor(self) -> float: ...
    @ScaleFactor.setter
    def ScaleFactor(self, value: float) -> None: ...
    @property
    def Offset(self) -> float: ...
    @Offset.setter
    def Offset(self, value: float) -> None: ...
    @property
    def Column(self) -> ZOSAPI.SystemData.FieldColumn: ...
    @Column.setter
    def Column(self, value: ZOSAPI.SystemData.FieldColumn) -> None: ...
    def IsPickupFromCurrentColumn(self) -> bool: ...
    def MakePickupFromCurrentColumn(self) -> None: ...

class ISolveFixed(ISolveData):
    """ZOSAPI.Editors.ISolveFixed"""
    ...

class ISolveInvertSag:
    """ZOSAPI.Editors.ISolveInvertSag"""
    @property
    def Surface(self) -> int: ...
    @Surface.setter
    def Surface(self, value: int) -> None: ...

class ISolveMarginalRayAngle(ISolveData):
    """ZOSAPI.Editors.ISolveMarginalRayAngle"""
    @property
    def Angle(self) -> float: ...
    @Angle.setter
    def Angle(self, value: float) -> None: ...

class ISolveMarginalRayHeight(ISolveData):
    """ZOSAPI.Editors.ISolveMarginalRayHeight"""
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> None: ...
    @property
    def PupilZone(self) -> float: ...
    @PupilZone.setter
    def PupilZone(self, value: float) -> None: ...

class ISolveMarginalRayNormal(ISolveData):
    """ZOSAPI.Editors.ISolveMarginalRayNormal"""
    ...

class ISolveMaterialModel(ISolveData):
    """ZOSAPI.Editors.ISolveMaterialModel"""
    @property
    def IndexNd(self) -> float: ...
    @IndexNd.setter
    def IndexNd(self, value: float) -> None: ...
    @property
    def VaryIndex(self) -> bool: ...
    @VaryIndex.setter
    def VaryIndex(self, value: bool) -> None: ...
    @property
    def AbbeVd(self) -> float: ...
    @AbbeVd.setter
    def AbbeVd(self, value: float) -> None: ...
    @property
    def VaryAbbe(self) -> bool: ...
    @VaryAbbe.setter
    def VaryAbbe(self, value: bool) -> None: ...
    @property
    def dPgF(self) -> float: ...
    @dPgF.setter
    def dPgF(self, value: float) -> None: ...
    @property
    def VarydPgF(self) -> bool: ...
    @VarydPgF.setter
    def VarydPgF(self, value: bool) -> None: ...

class ISolveMaterialOffset(ISolveData):
    """ZOSAPI.Editors.ISolveMaterialOffset"""
    @property
    def NdOffset(self) -> float: ...
    @NdOffset.setter
    def NdOffset(self, value: float) -> None: ...
    @property
    def VdOffset(self) -> float: ...
    @VdOffset.setter
    def VdOffset(self, value: float) -> None: ...

class ISolveMaterialSubstitute(ISolveData):
    """ZOSAPI.Editors.ISolveMaterialSubstitute"""
    @property
    def Catalog(self) -> str: ...
    @Catalog.setter
    def Catalog(self, value: str) -> None: ...

class ISolveMaximum(ISolveData):
    """ZOSAPI.Editors.ISolveMaximum"""
    ...

class ISolveNone(ISolveData):
    """ZOSAPI.Editors.ISolveNone

    This solve type is only used for cells that do not support any type of solve. For most cells, use ISolveFixed instead.
    """
    ...

class ISolveObjectPickup(ISolveData):
    """ZOSAPI.Editors.ISolveObjectPickup"""
    @property
    def Object(self) -> int: ...
    @Object.setter
    def Object(self, value: int) -> None: ...
    @property
    def ScaleFactor(self) -> float: ...
    @ScaleFactor.setter
    def ScaleFactor(self, value: float) -> None: ...
    @property
    def SupportsScale(self) -> bool: ...
    @property
    def Offset(self) -> float: ...
    @Offset.setter
    def Offset(self, value: float) -> None: ...
    @property
    def SupportsOffset(self) -> bool: ...
    @property
    def Column(self) -> ZOSAPI.Editors.NCE.ObjectColumn: ...
    @Column.setter
    def Column(self, value: ZOSAPI.Editors.NCE.ObjectColumn) -> None: ...
    def IsPickupFromCurrentColumn(self) -> bool: ...
    def MakePickupFromCurrentColumn(self) -> None: ...

class ISolveOpticalPathDifference(ISolveData):
    """ZOSAPI.Editors.ISolveOpticalPathDifference"""
    @property
    def OPD(self) -> float: ...
    @OPD.setter
    def OPD(self, value: float) -> None: ...
    @property
    def PupilZone(self) -> float: ...
    @PupilZone.setter
    def PupilZone(self, value: float) -> None: ...

class ISolvePickupChiefRay(ISolveData):
    """ZOSAPI.Editors.ISolvePickupChiefRay"""
    @property
    def Field(self) -> int: ...
    @Field.setter
    def Field(self, value: int) -> None: ...
    @property
    def Wavelength(self) -> int: ...
    @Wavelength.setter
    def Wavelength(self, value: int) -> None: ...

class ISolvePosition(ISolveData):
    """ZOSAPI.Editors.ISolvePosition"""
    @property
    def FromSurface(self) -> int: ...
    @FromSurface.setter
    def FromSurface(self, value: int) -> None: ...
    @property
    def Length(self) -> float: ...
    @Length.setter
    def Length(self, value: float) -> None: ...

class ISolvePupilPosition(ISolveData):
    """ZOSAPI.Editors.ISolvePupilPosition"""
    ...

class ISolveSurfacePickup(ISolveData):
    """ZOSAPI.Editors.ISolveSurfacePickup"""
    @property
    def Surface(self) -> int: ...
    @Surface.setter
    def Surface(self, value: int) -> None: ...
    @property
    def ScaleFactor(self) -> float: ...
    @ScaleFactor.setter
    def ScaleFactor(self, value: float) -> None: ...
    @property
    def SupportsScale(self) -> bool: ...
    @property
    def Offset(self) -> float: ...
    @Offset.setter
    def Offset(self, value: float) -> None: ...
    @property
    def SupportsOffset(self) -> bool: ...
    @property
    def Column(self) -> ZOSAPI.Editors.LDE.SurfaceColumn: ...
    @Column.setter
    def Column(self, value: ZOSAPI.Editors.LDE.SurfaceColumn) -> None: ...
    def IsPickupFromCurrentColumn(self) -> bool: ...
    def MakePickupFromCurrentColumn(self) -> None: ...

class ISolveThermalPickup(ISolveData):
    """ZOSAPI.Editors.ISolveThermalPickup"""
    @property
    def Configuration(self) -> int: ...
    @Configuration.setter
    def Configuration(self, value: int) -> None: ...

class ISolveVariable(ISolveData):
    """ZOSAPI.Editors.ISolveVariable"""
    ...

class ISolveZPLMacro(ISolveData):
    """ZOSAPI.Editors.ISolveZPLMacro"""
    @property
    def Macro(self) -> str: ...
    @Macro.setter
    def Macro(self, value: str) -> None: ...
    def GetAvailableMacros(self) -> List[str]: ...

class ReflectTransmitCode(IntEnum):
    """ZOSAPI.Editors.ReflectTransmitCode"""
    Success = 0
    NoReflectDataInFile = 1
    NoTransmitDataInFile = 2

class SampleSides(IntEnum):
    """ZOSAPI.Editors.SampleSides"""
    Front = 0
    Back = 1

class Samplings(IntEnum):
    """ZOSAPI.Editors.Samplings"""
    FiveDegrees = 0
    TwoDegrees = 1
    OneDegree = 2

class SolveStatus(IntEnum):
    """ZOSAPI.Editors.SolveStatus"""
    Success = 0
    InvalidSolveType = 1
    InvalidRow = 2
    InvalidColumn = 3
    PostSurfaceStopOnly = 4
    InvalidMacro = 5
    Failed = 10000

class SolveType(IntEnum):
    """ZOSAPI.Editors.SolveType

    All solve types available. Note that only a portion of the types are available for any given IEditorCell.
    """
    None_ = 0
    Fixed = 1
    Variable = 2
    SurfacePickup = 3
    """Lens Data Editor pickup solve."""
    ZPLMacro = 4
    MarginalRayAngle = 5
    MarginalRayHeight = 6
    ChiefRayAngle = 7
    MarginalRayNormal = 8
    ChiefRayNormal = 9
    Aplanatic = 10
    ElementPower = 11
    CocentricSurface = 12
    CocentricRadius = 13
    FNumber = 14
    ChiefRayHeight = 15
    EdgeThickness = 16
    OpticalPathDifference = 17
    Position = 18
    Compensator = 19
    CenterOfCurvature = 20
    PupilPosition = 21
    MaterialSubstitute = 22
    MaterialOffset = 23
    MaterialModel = 24
    Automatic = 25
    Maximum = 26
    PickupChiefRay = 27
    ObjectPickup = 28
    """Non-sequential Component Editor pickup solve."""
    ConfigPickup = 29
    """Multiple Configuration Editor pickup solve."""
    ThermalPickup = 30
    MarginPercent = 31
    CA_fill = 32
    DIA_fill = 33
    ConcentricSurface = 12
    ConcentricRadius = 13
    DuplicateSag = 34
    InvertSag = 35
    FieldPickup = 10000
