# Auto-generated by zosapi-stubgen — do not edit by hand.
# Re-run `zosapi-stubgen` to refresh after an OpticStudio upgrade.
from __future__ import annotations
from typing import (
    Any, Dict, Generic, Iterable, Iterator, List,
    Optional, overload, Sequence, Set, Tuple, TypeVar, Union,
)
from enum import IntEnum, IntFlag
from datetime import datetime, timedelta

import ZOSAPI.Analysis.Settings

class IAS_Fan(ZOSAPI.Analysis.Settings.IAS_):
    """ZOSAPI.Analysis.Settings.Fans.IAS_Fan"""
    @property
    def Field(self) -> ZOSAPI.Analysis.Settings.IAS_Field: ...
    @property
    def Surface(self) -> ZOSAPI.Analysis.Settings.IAS_Surface: ...
    @property
    def Wavelength(self) -> ZOSAPI.Analysis.Settings.IAS_Wavelength: ...
    @property
    def NumberOfRays(self) -> int: ...
    @NumberOfRays.setter
    def NumberOfRays(self, value: int) -> None: ...
    @property
    def PlotScale(self) -> float: ...
    @PlotScale.setter
    def PlotScale(self, value: float) -> None: ...
    @property
    def CheckApertures(self) -> bool: ...
    @CheckApertures.setter
    def CheckApertures(self, value: bool) -> None: ...
    @property
    def VignettedPupil(self) -> bool: ...
    @VignettedPupil.setter
    def VignettedPupil(self, value: bool) -> None: ...
    @property
    def UseDashes(self) -> bool: ...
    @UseDashes.setter
    def UseDashes(self, value: bool) -> None: ...
    @property
    def Sagittal(self) -> SagittalAberrationComponent: ...
    @Sagittal.setter
    def Sagittal(self, value: SagittalAberrationComponent) -> None: ...
    @property
    def Tangential(self) -> TangentialAberrationComponent: ...
    @Tangential.setter
    def Tangential(self, value: TangentialAberrationComponent) -> None: ...

class SagittalAberrationComponent(IntEnum):
    """ZOSAPI.Analysis.Settings.Fans.SagittalAberrationComponent"""
    Aberration_X = 0
    Aberration_Y = 1

class TangentialAberrationComponent(IntEnum):
    """ZOSAPI.Analysis.Settings.Fans.TangentialAberrationComponent"""
    Aberration_Y = 0
    Aberration_X = 1
