# Auto-generated by zosapi-stubgen — do not edit by hand.
# Re-run `zosapi-stubgen` to refresh after an OpticStudio upgrade.
from __future__ import annotations
from typing import (
    Any, Dict, Generic, Iterable, Iterator, List,
    Optional, overload, Sequence, Set, Tuple, TypeVar, Union,
)
from enum import IntEnum, IntFlag
from datetime import datetime, timedelta

import ZOSAPI
import ZOSAPI.Tools

class ACISExportVersion(IntEnum):
    """ZOSAPI.Tools.General.ACISExportVersion"""
    Current = 0
    V25 = 1
    V26 = 2
    V27 = 3
    V28 = 4
    V29 = 5
    V30 = 6

class ArchiveFileStatus(IntEnum):
    """ZOSAPI.Tools.General.ArchiveFileStatus"""
    Okay = 0
    UnableToOpen = -1
    InvalidFile = -2
    InvalidVersion = -3

class CADAngularToleranceType(IntEnum):
    """ZOSAPI.Tools.General.CADAngularToleranceType"""
    Low = 0
    Medium = 1
    High = 2
    Presentation = 3

class CADFileType(IntEnum):
    """ZOSAPI.Tools.General.CADFileType"""
    IGES = 0
    STEP = 1
    SAT = 2
    STL = 3
    SAB = 4
    ASAT = 5
    ASAB = 6
    MODEL = 7
    CATPART = 8
    CATPRODUCT = 9
    XCGM = 10

class CADToleranceType(IntEnum):
    """ZOSAPI.Tools.General.CADToleranceType"""
    N_TenEMinus4 = 0
    N_TenEMinus5 = 1
    N_TenEMinus6 = 2
    N_TenEMinus7 = 3

class DataTypes(IntEnum):
    """ZOSAPI.Tools.General.DataTypes"""
    NotSet = 0
    Boolean = 1
    Integer = 2
    IntegerArray = 3
    IntegerMatrix = 4
    Float = 5
    FloatArray = 6
    FloatMatrix = 7
    Double = 8
    DoubleArray = 9
    DoubleMatrix = 10
    String = 11
    StringArray = 12
    StringMatrix = 13
    ByteArray = 14
    Dictionary = 15
    Serializable = 16
    File = 17

class EntryCompressionModes(IntEnum):
    """ZOSAPI.Tools.General.EntryCompressionModes"""
    Auto = 0
    On = 1
    Off = 2

class IComputeRMSSpotSize(ZOSAPI.Tools.ISystemTool):
    """ZOSAPI.Tools.General.IComputeRMSSpotSize"""
    @property
    def UseGaussianQuadrature(self) -> bool: ...
    @property
    def UseRectangularArray(self) -> bool: ...
    @property
    def NumberOfRings(self) -> int: ...
    @property
    def NumberOfArms(self) -> int: ...
    @property
    def ObscuredFration(self) -> float: ...
    @property
    def GridSampling(self) -> int: ...
    @property
    def DeleteVignetted(self) -> bool: ...
    @property
    def AssumeAxialSymmetry(self) -> bool: ...
    @AssumeAxialSymmetry.setter
    def AssumeAxialSymmetry(self, value: bool) -> None: ...
    @property
    def IgnoreLateralColor(self) -> bool: ...
    @IgnoreLateralColor.setter
    def IgnoreLateralColor(self, value: bool) -> None: ...
    @property
    def NumberOfConfigurations(self) -> int:
        """Gets the number of output configurations."""
        ...
    @property
    def NumberOfFields(self) -> int:
        """Gets the number of output fields."""
        ...
    @property
    def RMSSpotRadii(self) -> List[float]:
        """Gets all output RMS spot radii (in lens units). Note that there will be (NumberOfConfigurations) rows by (NumberOfFields) columns."""
        ...
    def GetSpotRadius(self, configuration: int, field: int) -> float:
        """Gets the output RMS spot radius for the given configuration and field (in lens units).

        Args:
            configuration: The configuration (1 to NumberOfConfigurations).
            field: The field (1 to NumberOfFields).
        """
        ...
    def SetMethodGaussianQuadrature(self, numberOfRings: int, numberOfArms: int, obscuredFraction: float) -> None:
        """Sets the pupil integration method to Gaussian quadrature.

        Args:
            numberOfRings: The number of rings (1 - 20).
            numberOfArms: The number of arms (6, 8, 10, 12).
            obscuredFraction: The obscured fraction (0.0 - 1.0).
        """
        ...
    def SetMethodRectangularArray(self, gridSampling: int, deleteVignetted: bool) -> None:
        """Sets the pupil integration method to grid sampling.

        Args:
            gridSampling: The grid sampling (NxN, where N must be an even number from 4 - 204).
            deleteVignetted: if set to true delete vignetted rays.
        """
        ...

class ICreateArchive(ZOSAPI.Tools.ISystemTool):
    """ZOSAPI.Tools.General.ICreateArchive

    Interfaces and methods for creating a ZAR file. This interface can be accessed via the IOpticalSystemTools interface.
    """
    @property
    def UseDataCompression(self) -> bool: ...
    @UseDataCompression.setter
    def UseDataCompression(self, value: bool) -> None: ...
    def GetArchiveFileName(self) -> str:
        """Get the file name of the output archive. This will have a default value only if the default file did not already exist.

        Returns:
            The full path and name of the archive.
        """
        ...
    def SetArchiveFileName(self, fullFileName: str) -> bool:
        """Set the file name of the output archive, including extension. Note that the output directory must exist prior to this call.

        Args:
            fullFileName: Full path and name of the file.

        Returns:
            true if the specified name is valid; otherwise, false.
        """
        ...

class IDataDictionary:
    """ZOSAPI.Tools.General.IDataDictionary"""
    @property
    def FileName(self) -> str: ...
    @property
    def FileType(self) -> ZemaxFileTypes: ...
    @property
    def FileVersion(self) -> int: ...
    @property
    def FileData1(self) -> int: ...
    @property
    def FileData2(self) -> int: ...
    @property
    def Keys(self) -> List[str]: ...
    @property
    def NumberOfEntries(self) -> int: ...
    @property
    def Entries(self) -> List[IDataEntry]: ...
    def Close(self) -> None: ...
    def CreateEntry(self, key: str) -> IDataEntry: ...
    def GetEntry(self, key: str) -> IDataEntry: ...
    def GetKey(self, keyIndex: int) -> str: ...
    def Save(self) -> None: ...

class IDataEntry:
    """ZOSAPI.Tools.General.IDataEntry"""
    @property
    def DataType(self) -> DataTypes: ...
    @property
    def IsSet(self) -> bool: ...
    @property
    def Key(self) -> str: ...
    @property
    def CompressionMode(self) -> EntryCompressionModes: ...
    @CompressionMode.setter
    def CompressionMode(self, value: EntryCompressionModes) -> None: ...
    def Delete(self) -> None: ...
    def GetBooleanValue(self) -> bool: ...
    def GetByteArray(self) -> List[int]: ...
    def GetDoubleArray(self) -> List[float]: ...
    def GetDoubleMatrix(self) -> List[float]: ...
    def GetDoubleValue(self) -> float: ...
    def GetFile(self, fileName: str) -> None: ...
    def GetFloatArray(self) -> List[float]: ...
    def GetFloatMatrix(self) -> List[float]: ...
    def GetFloatValue(self) -> float: ...
    def GetIntegerArray(self) -> List[int]: ...
    def GetIntegerMatrix(self) -> List[int]: ...
    def GetIntegerValue(self) -> int: ...
    def GetSerializableValue(self) -> Any: ...
    def GetStringArray(self) -> List[str]: ...
    def GetStringMatrix(self) -> List[str]: ...
    def GetStringValue(self) -> str: ...
    def SetBooleanValue(self, val: bool) -> bool: ...
    def SetByteArray(self, val: List[int]) -> bool: ...
    def SetDoubleArray(self, val: List[float]) -> bool: ...
    def SetDoubleMatrix(self, val: List[float]) -> bool: ...
    def SetDoubleValue(self, val: float) -> bool: ...
    def SetFile(self, fileName: str) -> bool: ...
    def SetFloatArray(self, val: List[float]) -> bool: ...
    def SetFloatMatrix(self, val: List[float]) -> bool: ...
    def SetFloatValue(self, val: float) -> bool: ...
    def SetIntegerArray(self, val: List[int]) -> bool: ...
    def SetIntegerMatrix(self, val: List[int]) -> bool: ...
    def SetIntegerValue(self, val: int) -> bool: ...
    def SetSerializableValue(self, val: Any) -> bool: ...
    def SetStringArray(self, val: List[str]) -> bool: ...
    def SetStringMatrix(self, val: List[str]) -> bool: ...
    def SetStringValue(self, val: str) -> bool: ...

class IExportCAD(ZOSAPI.Tools.ISystemTool):
    """ZOSAPI.Tools.General.IExportCAD

    Interfaces and methods for exporting the current system to various CAD formats. This interface can be accessed via the IOpticalSystemTools interface.
    """
    @property
    def FirstSurface(self) -> int:
        """Gets or sets the first surface to include in the CAD file (0 to NumberOfSurfaces-2)."""
        ...
    @FirstSurface.setter
    def FirstSurface(self, value: int) -> None: ...
    @property
    def LastSurface(self) -> int:
        """Gets or sets the last surface to include in the CAD file (1 to NumberOfSurfaces-1)."""
        ...
    @LastSurface.setter
    def LastSurface(self, value: int) -> None: ...
    @property
    def CanChangeSurface(self) -> bool:
        """Gets a value indicating whether the surface is modifiable. For non-sequential systems, the surface will be fixed at surface 1."""
        ...
    @property
    def FirstObject(self) -> int:
        """Gets or sets the first object to include in the CAD file (1 to NumberOfObjects). Note that this settings is only valid for pure non-sequential systems."""
        ...
    @FirstObject.setter
    def FirstObject(self, value: int) -> None: ...
    @property
    def LastObject(self) -> int:
        """Gets or sets the last object to include in the CAD file (1 to NumberOfObjects)."""
        ...
    @LastObject.setter
    def LastObject(self, value: int) -> None: ...
    @property
    def SequentialSettingsEnabled(self) -> bool:
        """Gets a value indicating whether or not the sequential-only settings are used. These settings include: RayPattern NumberOfRays Wavelength SetWavelengthAll Field SetFieldAll DeleteVignetted"""
        ...
    @property
    def RayPattern(self) -> RayPatternType: ...
    @RayPattern.setter
    def RayPattern(self, value: RayPatternType) -> None: ...
    @property
    def NumberOfRays(self) -> int: ...
    @NumberOfRays.setter
    def NumberOfRays(self, value: int) -> None: ...
    @property
    def Wavelength(self) -> int: ...
    @Wavelength.setter
    def Wavelength(self, value: int) -> None: ...
    @property
    def Field(self) -> int: ...
    @Field.setter
    def Field(self, value: int) -> None: ...
    @property
    def DeleteVignetted(self) -> bool: ...
    @DeleteVignetted.setter
    def DeleteVignetted(self, value: bool) -> None: ...
    @property
    def RayLayer(self) -> int:
        """Gets or sets the ray layer (0 to 20)."""
        ...
    @RayLayer.setter
    def RayLayer(self, value: int) -> None: ...
    @property
    def LensLayer(self) -> int:
        """Gets or sets the lens layer (0 to 20)."""
        ...
    @LensLayer.setter
    def LensLayer(self, value: int) -> None: ...
    @property
    def DummyThickness(self) -> float: ...
    @DummyThickness.setter
    def DummyThickness(self, value: float) -> None: ...
    @property
    def SplineSegments(self) -> SplineSegmentsType: ...
    @SplineSegments.setter
    def SplineSegments(self, value: SplineSegmentsType) -> None: ...
    @property
    def FileType(self) -> CADFileType: ...
    @FileType.setter
    def FileType(self, value: CADFileType) -> None: ...
    @property
    def Tolerance(self) -> CADToleranceType: ...
    @Tolerance.setter
    def Tolerance(self, value: CADToleranceType) -> None: ...
    @property
    def AngularTolerance(self) -> CADAngularToleranceType: ...
    @AngularTolerance.setter
    def AngularTolerance(self, value: CADAngularToleranceType) -> None: ...
    @property
    def Configuration(self) -> int:
        """Gets the current configuration setting. Use one of the following methods to change the configuration setting: SetSingleConfiguration SetConfigurationAllByLayer SetConfigurationAllByFile SetConfigurationAllAtOnce"""
        ...
    @property
    def ExportDummySurfaces(self) -> bool: ...
    @ExportDummySurfaces.setter
    def ExportDummySurfaces(self, value: bool) -> None: ...
    @property
    def SurfacesAsSolids(self) -> bool: ...
    @SurfacesAsSolids.setter
    def SurfacesAsSolids(self, value: bool) -> None: ...
    @property
    def ScatterNSCRays(self) -> bool: ...
    @ScatterNSCRays.setter
    def ScatterNSCRays(self, value: bool) -> None: ...
    @property
    def SplitNSCRays(self) -> bool: ...
    @SplitNSCRays.setter
    def SplitNSCRays(self, value: bool) -> None: ...
    @property
    def UsePolarization(self) -> bool: ...
    @UsePolarization.setter
    def UsePolarization(self, value: bool) -> None: ...
    @property
    def OutputFileName(self) -> str: ...
    @OutputFileName.setter
    def OutputFileName(self, value: str) -> None: ...
    @property
    def AutoNameFaces(self) -> bool: ...
    @AutoNameFaces.setter
    def AutoNameFaces(self, value: bool) -> None: ...
    @property
    def FileVersion(self) -> ACISExportVersion: ...
    @FileVersion.setter
    def FileVersion(self, value: ACISExportVersion) -> None: ...
    def SetConfigurationAllAtOnce(self) -> None: ...
    def SetConfigurationAllByFile(self) -> None: ...
    def SetConfigurationAllByLayer(self) -> None: ...
    def SetCurrentConfiguration(self) -> None: ...
    def SetFieldAll(self) -> None: ...
    def SetSingleConfiguration(self, ConfigurationNumber: int) -> None:
        """Set it to export a single configuration of the current system.

        Args:
            ConfigurationNumber: The configuration number (0 to NumberOfConfigurations). Use 0 for the current configuration.
        """
        ...
    def SetWavelengthAll(self) -> None: ...

class ILensCatalogLens:
    """ZOSAPI.Tools.General.ILensCatalogLens"""
    @property
    def Vendor(self) -> str: ...
    @property
    def LensName(self) -> str: ...
    @property
    def EFL(self) -> float: ...
    @property
    def EPD(self) -> float: ...
    @property
    def Shape(self) -> LensShape: ...
    @property
    def Type(self) -> LensType: ...
    @property
    def NumberOfElements(self) -> int: ...
    @property
    def Telecentric(self) -> bool: ...
    def InsertLensNonSeq(self) -> bool:
        """Convert this lens to non-sequential components, and add them to the end of the current system. Note that this will fail if the current system is sequential.

        Returns:
            true if the lens was inserted; otherwise false.
        """
        ...
    def InsertLensSeq(self, atSurface: int, ignoreObject: bool, reverseSurfGeom: bool) -> bool:
        """Inserts this lens into the current sequential system, at the specific surface. Note that this will fail if the current system is not sequential.

        Args:
            atSurface: Position to insert the lens.
            ignoreObject
            reverseSurfGeom: Change sign of surface geometry in mirror space.

        Returns:
            true if the lens was inserted; otherwise false.
        """
        ...
    def LoadLens(self, saveIfNeeded: bool) -> None:
        """Loads this lens. Note that the current system will be replaced entirely.

        Args:
            saveIfNeeded: If set to true, the current system will be saved (if needed) before loading the new lens.
        """
        ...
    def LoadNewLensNonSeq(self) -> ZOSAPI.IOpticalSystem:
        """Creates a new non-sequential system from this lens.

        Returns:
            The new system
        """
        ...
    def LoadNewLensSeq(self) -> ZOSAPI.IOpticalSystem:
        """Creates a new sequential system from this lens.

        Returns:
            The new system
        """
        ...

class ILensCatalogs(ZOSAPI.Tools.ISystemTool):
    """ZOSAPI.Tools.General.ILensCatalogs

    Interfaces and methods for searching the available Lens Catalogs. This interface can be accessed via the IOpticalSystemTools interface.
    """
    @property
    def SelectedVendor(self) -> str:
        """Gets or sets the current vendor to be used for the search."""
        ...
    @SelectedVendor.setter
    def SelectedVendor(self, value: str) -> None: ...
    @property
    def UseEFL(self) -> bool:
        """Use the MinEFL and MaxEFL effective focal length criteria in the search."""
        ...
    @UseEFL.setter
    def UseEFL(self, value: bool) -> None: ...
    @property
    def MinEFL(self) -> float:
        """Minimum effective focal length"""
        ...
    @MinEFL.setter
    def MinEFL(self, value: float) -> None: ...
    @property
    def MaxEFL(self) -> float:
        """Maximum effective focal length"""
        ...
    @MaxEFL.setter
    def MaxEFL(self, value: float) -> None: ...
    @property
    def UseEPD(self) -> bool:
        """Use the MinEPD and MaxEPD entrance pupil diameter criteria in the search."""
        ...
    @UseEPD.setter
    def UseEPD(self, value: bool) -> None: ...
    @property
    def MinEPD(self) -> float:
        """Minimum entrance pupil diameter"""
        ...
    @MinEPD.setter
    def MinEPD(self, value: float) -> None: ...
    @property
    def MaxEPD(self) -> float:
        """Maximum entrance pupil diameter"""
        ...
    @MaxEPD.setter
    def MaxEPD(self, value: float) -> None: ...
    @property
    def IncShapeEqui(self) -> bool: ...
    @IncShapeEqui.setter
    def IncShapeEqui(self, value: bool) -> None: ...
    @property
    def IncShapeBi(self) -> bool: ...
    @IncShapeBi.setter
    def IncShapeBi(self, value: bool) -> None: ...
    @property
    def IncShapePlano(self) -> bool: ...
    @IncShapePlano.setter
    def IncShapePlano(self, value: bool) -> None: ...
    @property
    def IncShapeMeniscus(self) -> bool: ...
    @IncShapeMeniscus.setter
    def IncShapeMeniscus(self, value: bool) -> None: ...
    @property
    def IncTypeSpherical(self) -> bool: ...
    @IncTypeSpherical.setter
    def IncTypeSpherical(self, value: bool) -> None: ...
    @property
    def IncTypeGRIN(self) -> bool: ...
    @IncTypeGRIN.setter
    def IncTypeGRIN(self, value: bool) -> None: ...
    @property
    def IncTypeAspheric(self) -> bool: ...
    @IncTypeAspheric.setter
    def IncTypeAspheric(self, value: bool) -> None: ...
    @property
    def IncTypeToroidal(self) -> bool: ...
    @IncTypeToroidal.setter
    def IncTypeToroidal(self, value: bool) -> None: ...
    @property
    def NumberOfElements(self) -> int:
        """Gets or sets the number of elements to use in the search."""
        ...
    @NumberOfElements.setter
    def NumberOfElements(self, value: int) -> None: ...
    @property
    def MatchingLenses(self) -> int:
        """Gets the number matching lenses. You must first call one of the Run methods to perform the search first."""
        ...
    @property
    def LensesForVendor(self) -> int:
        """Gets the number of lenses for current vendor (selected via SelectedVendor)."""
        ...
    def GetAllVendors(self) -> List[str]: ...
    def GetResult(self, index: int) -> ILensCatalogLens:
        """Gets the specified search result.

        Args:
            index: The index (0 to MatchingLenses-1).
        """
        ...
    def SetNumberOfElementsAny(self) -> None:
        """Do not use the NumberOfElements search criteria."""
        ...

class IQuickAdjust(ZOSAPI.Tools.ISystemTool):
    """ZOSAPI.Tools.General.IQuickAdjust

    Interfaces and methods for running the Quick Adjust tool. This interface can be accessed via the IOpticalSystemTools interface.
    """
    @property
    def AdjustSurface(self) -> int:
        """Gets or sets the adjust surface."""
        ...
    @AdjustSurface.setter
    def AdjustSurface(self, value: int) -> None: ...
    @property
    def SurfaceParameter(self) -> QuickAdjustType: ...
    @SurfaceParameter.setter
    def SurfaceParameter(self, value: QuickAdjustType) -> None: ...
    @property
    def Criterion(self) -> QuickAdjustCriterion: ...
    @Criterion.setter
    def Criterion(self, value: QuickAdjustCriterion) -> None: ...
    @property
    def EvaluateSurface(self) -> int:
        """Gets or sets the surface at which to evaluate the criterion."""
        ...
    @EvaluateSurface.setter
    def EvaluateSurface(self, value: int) -> None: ...
    def SetEvaluateSurfaceImage(self) -> None:
        """Sets EvaluateSurface to 0."""
        ...

class IQuickFocus(ZOSAPI.Tools.ISystemTool):
    """ZOSAPI.Tools.General.IQuickFocus

    Interfaces and methods for running the Quick Focus tool. This interface can be accessed via the IOpticalSystemTools interface.
    """
    @property
    def UseCentroid(self) -> bool: ...
    @UseCentroid.setter
    def UseCentroid(self, value: bool) -> None: ...
    @property
    def Criterion(self) -> QuickFocusCriterion: ...
    @Criterion.setter
    def Criterion(self, value: QuickFocusCriterion) -> None: ...

class IRestoreArchive(ZOSAPI.Tools.ISystemTool):
    """ZOSAPI.Tools.General.IRestoreArchive

    Interfaces and methods for restoring a ZAR file. This interface can be accessed via the IOpticalSystemTools interface.
    """
    @property
    def ArchiveFile(self) -> str:
        """Gets the name of the currently selected input archive."""
        ...
    @property
    def NumberOfFilesInArchive(self) -> int:
        """Gets the number of files stored in the specified archive."""
        ...
    @property
    def ExtractAllFilesToProjectDirectory(self) -> bool: ...
    @ExtractAllFilesToProjectDirectory.setter
    def ExtractAllFilesToProjectDirectory(self, value: bool) -> None: ...
    def GetFileNameInArchive(self, fileNumber: int) -> str:
        """Gets the file name for the specified file in the archive.

        Args:
            fileNumber: The file number (0 - NumberOfFilesInArchive-1).
        """
        ...
    def GetOutputFolder(self) -> str:
        """Gets the currently selected output folder."""
        ...
    def SetFileName(self, archiveFile: str) -> ArchiveFileStatus:
        """Sets the name of the input archive.

        Args:
            archiveFile: The full path to the archive file.

        Returns:
            The results from trying to read the archive.
        """
        ...
    def SetFileOverwrite(self, fileNumber: int, allowOverwrite: bool) -> None:
        """Sets a flag determining whether the file at the specified index will be overwritten if it already exists.

        Args:
            fileNumber: The file number (see GetFileNameInArchive).
            allowOverwrite: if set to true the file will be overwritten; otherwise it will be skipped.
        """
        ...
    def SetFilesAllOverwrite(self) -> None:
        """All files will be overwritten if they exist."""
        ...
    def SetFilesNoOverwrite(self) -> None:
        """No files will be overwritten."""
        ...
    def SetOutputFolder(self, folder: str) -> bool:
        """Sets the desired output folder.

        Args:
            folder: The folder.

        Returns:
            true if the specified folder is valid and exists; otherwise, false.
        """
        ...

class IScale(ZOSAPI.Tools.ISystemTool):
    """ZOSAPI.Tools.General.IScale

    Interfaces and methods for Scaling the Currently active Lens System. This interface can be accessed via the IOpticalSystemTools interface.
    """
    @property
    def ScaleFactor(self) -> float:
        """How much do we scale the System."""
        ...
    @ScaleFactor.setter
    def ScaleFactor(self, value: float) -> None: ...
    @property
    def FirstComponent(self) -> int:
        """Which is the First Surface/Object to Scale."""
        ...
    @FirstComponent.setter
    def FirstComponent(self, value: int) -> None: ...
    @property
    def LastComponent(self) -> int:
        """Which is the Last Surface/Object to Scale."""
        ...
    @LastComponent.setter
    def LastComponent(self, value: int) -> None: ...
    @property
    def ScaleToUnit(self) -> ScaleToUnits:
        """To which unit type are we Scaling."""
        ...
    @ScaleToUnit.setter
    def ScaleToUnit(self, value: ScaleToUnits) -> None: ...
    @property
    def ScaleByFactor(self) -> bool:
        """How much do we scale the System using 'ScaleFactor'."""
        ...
    @ScaleByFactor.setter
    def ScaleByFactor(self, value: bool) -> None: ...
    @property
    def ScaleByUnits(self) -> bool:
        """Scale from the Current Unit to this new Unit. ScaleFactor comes from the coversion from one metric to another. If true, ScaleByUnits is set to false and vice versa."""
        ...
    @ScaleByUnits.setter
    def ScaleByUnits(self, value: bool) -> None: ...
    @property
    def NumberOfComponents(self) -> int:
        """How many components are in the 'Avaiable Component List'. If true, ScaleByFactor is set to false and vice versa."""
        ...
    def GetComponentAt(self, idx: int) -> str:
        """Get the 'Avaiable Component List' at index 'idx'.

        Args:
            idx: Get the idx-th Component.

        Returns:
            The idx-th Component
        """
        ...

class LensShape(IntEnum):
    """ZOSAPI.Tools.General.LensShape"""
    Unknown = 0
    Equi = 1
    Bi = 2
    Plano = 3
    Meniscus = 4

class LensType(IntEnum):
    """ZOSAPI.Tools.General.LensType"""
    Other = 0
    Spherical = 1
    GRIN = 2
    Aspheric = 3
    Toroidal = 4

class QuickAdjustCriterion(IntEnum):
    """ZOSAPI.Tools.General.QuickAdjustCriterion"""
    SpotSizeRadial = 0
    SpotSizeXOnly = 1
    SpotSizeYOnly = 2
    AngularRadial = 3
    AngularXOnly = 4
    AngularYOnly = 5

class QuickAdjustType(IntEnum):
    """ZOSAPI.Tools.General.QuickAdjustType"""
    Radius = 0
    Thickness = 1

class QuickFocusCriterion(IntEnum):
    """ZOSAPI.Tools.General.QuickFocusCriterion"""
    SpotSizeRadial = 0
    SpotSizeXOnly = 1
    SpotSizeYOnly = 2
    RMSWavefront = 3

class RayPatternType(IntEnum):
    """ZOSAPI.Tools.General.RayPatternType"""
    XYFan = 0
    XFan = 1
    YFan = 2
    Ring = 3
    List = 4
    Random = 5
    Grid = 6
    SolidRing = 7

class ScaleToUnits(IntEnum):
    """ZOSAPI.Tools.General.ScaleToUnits"""
    Millimeters = 0
    Centimeters = 1
    Inches = 2
    Meters = 3

class SplineSegmentsType(IntEnum):
    """ZOSAPI.Tools.General.SplineSegmentsType"""
    N_016 = 0
    N_032 = 1
    N_064 = 2
    N_128 = 3
    N_256 = 4
    N_512 = 5

class ZemaxFileTypes(IntEnum):
    """ZOSAPI.Tools.General.ZemaxFileTypes"""
    Unknown = 0
    LMX = 1
    User = 2
